Handle errors during applying of setup section
wirenboard/wb-mqtt-serial pull request #121
Opened 2020-09-07 06:28 UTC by PeteK12

After service startup all devices are marked as disconnected. So the service will try to apply all setup sections. The devce is marked as connected if all setup registers are written successfully.

2020-09-07 08:38 UTC, evgeny-boger requested changes

2020-09-07 08:38 UTC, evgeny-boger commented on src/serial_device.h
>      virtual void Prepare();
EndSession зря выбросил, оно используется в некоторых протоколах.

2020-09-07 08:38 UTC, evgeny-boger commented on src/serial_device.h
> -    // Ends communication session with the device. Called before communicating with another device
EndSession зря выбросил, оно используется в некоторых протоколах. См. тикет 27934

2020-09-07 08:38 UTC, evgeny-boger commented on src/serial_client.cpp
> +                        auto wrote = device->WriteSetupRegisters();
тоже, кажется, неправильная логика. А если один из setup-регистров не существует, например? В девайс будут в цикле писаться все setup-регистры заново. Надо как минимум на TransientException наверное делать проверку, а, возможно, вообще хранить статусы по всем регистрам.

2020-09-07 09:15 UTC, PeteK12 commented on src/serial_client.cpp
> +                        auto wrote = device->WriteSetupRegisters();
Почему регистр может не существовать? Если чего-то нет, то как мы можем потом доверять показаниям остальных регистров? Если это какая-то настройка, которая коэффициенты внутренние правит или логику работы устройства? Я исходил из того, что если не смогли настроить как надо, то либо пробовать повторно, либо пользователь увидит, что устройство не работает и полезет разбираться. В общем случае мы же не знаем на что эти настройки влияют.

2020-09-07 10:00 UTC, evgeny-boger commented on src/serial_client.cpp
> +                        auto wrote = device->WriteSetupRegisters();
Ну сценарий там примерно такой: в новой прошивке появилась какая-нибудь коррекция температуры, у пользователя прошивка старая - регистра нет.

Понятно, что нужно очень громко дать пользователю знать. Но вот стоит ли отключать устройство в таком случае - это как минимум спорно. 

И предложенная реализация плохо даёт пользователю знать: он увидит сообщения об отключении устройства, ошибки записи setup-регистров, бесконечные попытки записать один регистр. То есть сообщения "вы тут настройку попросили, а у вас устройство это не умеет" там не будет. Всё равно пользователь ничего не поймёт и пойдёт в саппорт.

2020-09-14 22:29 UTC, evgeny-boger commented on src/devices/modbus_io_device.cpp
> +bool TModbusIODevice::WriteSetupRegisters()
копипаста же?

2020-09-15 04:41 UTC, PeteK12 commented
Да. Вынес общую часть

2020-09-15 07:50 UTC, evgeny-boger commented on src/modbus_common.cpp
> +                    if (modbusException.code() != Modbus::ERR_ILLEGAL_DATA_ADDRESS) {
1) т.е. если тут illegal data address то вообще никакого сообщения в логе не будет?
2) Почему не использовать класс TransientException/не-TransientException, зачем отдельно делать коды для модбаса?

в соседней задаче с отключением несуществующих регистров при опросе, наверное, тебе нужно будет сделать для модбаса Transient/Permanent, можно после неё было бы влить.

2020-09-15 08:06 UTC, PeteK12 commented on src/modbus_common.cpp
> +                    if (modbusException.code() != Modbus::ERR_ILLEGAL_DATA_ADDRESS) {
1. Да, сейчас добавлю.
2. Потому что TSerialDeviceTransientErrorException - всё что ни попадя, а договаривались пропускать только конкретно ERR_ILLEGAL_DATA_ADDRESS.

2020-09-15 09:27 UTC, evgeny-boger commented on src/modbus_common.cpp
> +                    if (modbusException.code() != Modbus::ERR_ILLEGAL_DATA_ADDRESS) {
ну как раз ERR_ILLEGAL_DATA_ADDRESS - это должен быть не Transient, а Permanent.
Блин, сейчас кстати вспомнил, что illegal function - так же по смыслу должен обрабатываться. В общем мне пока кажется, что это какая-то общая логика. Влить можно и отдельно, но потом стоит объединить и два раза один и тот же список не держать.

2020-09-15 10:21 UTC, PeteK12 commented
@evgeny-boger Вот так? Если честно, мне не нравится как сейчас исключения в поекте используются. Они сделаны как часть нормальной логики работы программы. Документации нет, что и какие исключения может выкинуть - хз. Изменил иерархию и логику появления исключений, не знаешь, вдруг где-то по коду надо catch'ей наставить. Я таки придерживаюсь того, что исключения - это неожиданное поведение. Если ожидаешь, что в каком-то месте могут быть ошибки, напиши код так, чтобы вызывающая сторона явно видела, что может быть ошибка и её тип.

2020-09-15 10:32 UTC, evgeny-boger commented
да, так. 

Ну нравятся или не нравятся исключения - это вкусовщина. Мне тоже не нравится, когда исключения используются в нормальной работе. Но вот переделывать готовый проект из-за этого или, тем более, делать куски проекта по-другому - это неоправданная трата ресурсов. С Persistent/Transient error, например, протаскивать коды ошибки по всей цепочке вызовов было бы весьма тяжело. Если делать без исключений, то была бы другая архитектура. Да и вообще сейчас довольно логично: исключения возникают где угодно, а ловятся только serial_driver-ом. Можно это документенировать и жить спокойно.

Ещё в плюсах же есть exception specifications у методов, давай их везде расставим для порядка? Там не так много, кажется, возможных исключений.

2020-09-15 11:04 UTC, PeteK12 commented
exception specifications порезали в C++17 фактически осталось только noexcept и throw() без типов исключений. Не вижу смысла это прописывать

2020-09-24 16:22 UTC, evgeny-boger approved these changes

2020-09-25 04:59 UTC, merged