Feature/speed up
wirenboard/wb-mqtt-serial pull request #123
Opened 2020-09-11 10:16 UTC by PeteK12

* Separate response and frame timeouts for port and devices are added 
* All delays before requests are counted from last received or written message 
* Timeouts calculation according to port speed
* delay_ms is removed
* response_timeout_ms and frame_timeout_ms are set for all devices

2020-09-15 12:00 UTC, evgeny-boger requested changes

2020-09-15 12:00 UTC, evgeny-boger commented on src/serial_config.cpp
> +        if (device_config->FrameTimeout.count() < 0) {
может ругануться на то, что delay_ms больше не поддерживается, если он есть в конфиге или шаблоне?
Клиенты, к сожалению, его иногда использовали.

2020-09-16 11:21 UTC, PeteK12 commented on test/fake_serial_port.cpp
> +    Sleep(us);
Я убрал метод Sleep, точнее переименовал в SleepSinceLastInteraction.

2020-09-16 11:24 UTC, PeteK12 commented on src/serial_device.cpp
> +            //FIXME: Why is it here?
Это я себе осталял пометку, когда в первый раз смотрел, где и какие задержки. Это задержка перед отправкой запроса, там следующей строкой ReadRegister, который подразумевает посылку в шину.

2020-09-16 11:30 UTC, PeteK12 commented on src/file_descriptor_port.cpp
> +        selectTimeout = frameTimeout;
Комментарий добавил. А старый был хоть и большой, но странный. То, что там предлагают сделать, у нас сделано. Т.е. мы делаем задержку в FrameTimeout перед опросом устройства. Ну и сам код задержки после комментария тоже странноват. Берётся задержка в мс, переводится в число, и это число применяется уже как микросекунды. В результате реальная задержка в 1000 раз меньше.

2020-09-16 11:30 UTC, PeteK12 commented on src/file_descriptor_port.cpp
> +    LastInteraction = std::chrono::high_resolution_clock::now();
Да. У нас это system_clock, переделал на steady

2020-09-16 11:33 UTC, PeteK12 commented on src/modbus_common.cpp
> +                if (config->RequestDelay.count()) {
GuardInterval совсем не понятен из названия. Тем более что он был описан только в Readme. Если RequestDelay тоже не очень, то давай назовём иначе.

2020-09-16 11:34 UTC, PeteK12 commented on src/serial_port.cpp
> +        serial.flags |= ASYNC_LOW_LATENCY;
Это я пытался заставить драйвер быстрее отдавать полученные байтики программе. Правда без толку. Убрал

2020-09-16 11:34 UTC, PeteK12 commented on README.md
> +                    "frame_timeout_ms": 100,{
Поправил

2020-09-16 11:43 UTC, PeteK12 commented on src/serial_config.cpp
> +        if (device_config->FrameTimeout.count() < 0) {
Добавил сообщение в лог

2020-09-24 10:20 UTC, merged