Feature/modbus tcp
wirenboard/wb-mqtt-serial pull request #128
Opened 2020-10-01 10:00 UTC by PeteK12

Добавил поддержку MODBUS TCP. 
Сделал единый класс TModbusDevice и класс, описывающий потокол для него. 
Убрал нагромождение шаблонов при работе с класами-протоколами.
В модбасе выделил работу с PDU и заголовками пакетов, чтобы не дублировать код для MODBUS TCP.
Привёл схему к виду, при котором WebUI позволяет настроить каналы произвольных MODBUS устройств.

2020-10-04 12:08 UTC, evgeny-boger requested changes
см. комментарии. Плюс перед вливанием нужно будет поправить историю.

2020-10-04 12:08 UTC, evgeny-boger commented on src/serial_config.cpp
> +        return (protocolName == "modbus") || (protocolName == "modbus_io");
почему не сделать свойством класса-протокола?

2020-10-05 13:33 UTC, PeteK12 commented on src/devices/modbus_device.cpp
> +            if (GetName().find("io") != std::string::npos) {
Мне это тоже не сильно нравится. Как вариант можно TModbusIODevice от TModbusDevice от наследовать, т.к. там 90% идентичный код.

2020-10-05 13:34 UTC, PeteK12 commented on src/file_descriptor_port.cpp
> +    size_t nb = 0;
Поправил

2020-10-05 13:35 UTC, PeteK12 commented on src/poll_plan.cpp
> +    if (Queue.empty()) {
Если не собрали очередь на опрос, то тут можно зависнуть на всегда. Это случалось, если не удавалось открыть порт.

2020-10-05 13:36 UTC, PeteK12 commented on src/serial_config.cpp
> +        return (protocolName == "modbus") || (protocolName == "modbus_io");
Можно

2020-10-30 08:29 UTC, merged