Parameters were added in WB-MSW v3 template
wirenboard/wb-mqtt-serial pull request #177
Opened 2021-05-05 03:42 UTC by ExplorerOL

2021-05-06 15:03 UTC, evgeny-boger requested changes

2021-05-06 15:03 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-mr3.json
> +                        "Par_Input0_Mode": {
1) надо `snake_case`, не `CamelCase`, и уж тем более не `snake_Camel_Case`
2) не надо начинать параметры с `par_`
3) не надо их делать безумно длинными. Название идёт только в конфиг, там его человек должен прочитать или сам написать. Это должно быть `input0_mode` или `in0_mode`

2021-05-06 15:03 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-mr3.json
> +                        "Par_Input0_Debouncing": {
`in0_debounce_ms`

в названии хороший тон указывать единицы, если они нетривиальные. Чтобы пользователь не лез в документацию вспоминать - миллисекунды тут или наносекунды.

2021-05-06 15:03 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-mr3.json
> +                        "Par_Input1_Mode": {
кажется у нас под это есть shift и stide и вообще subdevices делались, чтобы указывать много однотипных кусков. Посмотреть можно в шаблоне MAI11, возможно обойдётся без копипасты.

2021-05-07 04:41 UTC, closed without merging

2021-05-07 06:22 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mr3.json
> -                "title": "Input 0 mode",
"title": "Input 0 Mode",

Вот так правильно?