"reg_type", "format" and "order" fields
wirenboard/wb-mqtt-serial pull request #181
Opened 2021-05-06 06:08 UTC by PeteK12

"reg_type", "format" and "order" fields are added to parameters in device templates

2021-05-06 13:27 UTC, evgeny-boger reviewed
может сделать на это тесты?

2021-05-07 04:56 UTC, PeteK12 commented
Добавил тест и поправил замечания Дмитрия.

2021-05-10 14:55 UTC, PeteK12 commented
Добавил "scale" и "offset" для параметров. Фактически сейчас настройки параметров могут иметь все те же поля, что и регистры канала, но часть не имеет смысла для настроек.
Вынес функции преобразования числа к значению регистра и обратно из TRegisterHandler, чтобы их можно было использовать и в настройках.

2021-05-10 15:09 UTC, evgeny-boger approved these changes

2021-05-11 13:46 UTC, webconn requested changes

2021-05-11 13:46 UTC, webconn commented on src/register.cpp
> +    if (reg.Offset == 0) {
Не очень понятно, для чего здесь столько повторяющегося кода, отличающегося только наличием `Scale`. Не так уж много мы сэкономим по времени на эти операции, у нас FPU есть.

Плюс, хоть здесь это не проявится скорее всего, сравнивать double и float с константами в общем случае - скользкая дорожка, у меня ёкнуло )

2021-05-11 13:46 UTC, webconn commented on src/register.cpp
> +        return strtoull(str, end, base);
А это правильно, что для int64 мы используем функцию `*ull`, а для uint64 - `*ll`?
Если тут опечатка, можно сразу и тест на это кинуть, ну чтобы неповадно было.

2021-05-11 13:46 UTC, webconn commented on src/register.cpp
> +    return WBMQTT::StringFormat("%.15g", RoundValue(reg.Scale * val + reg.Offset, reg.RoundTo));
Неочевидно, почему T в этом случае обязательно приведётся к double и это будет правильно. Но даже если так, давай вместо этого вызовем `ToScaledTextValue<double>` для явности

2021-05-11 13:46 UTC, webconn commented on src/register.cpp
> +            if (v & 0x800000) // fix sign (TBD: test)
покрыть тестом и убрать коммент? )

2021-05-11 13:46 UTC, webconn commented on src/register.cpp
> +template<typename T> std::string ToScaledTextValue(const TRegisterConfig& reg, T val)
Имена тут внутри путают, тут есть функции `ToScaledTextValue` и `GetScaledValue`, которые применяют противоположные преобразования (со scale и offset).

Вроде нормальная идея про MasterValue/SlaveValue, в контексте можно разобраться, какое преобразование нужно. Можно было бы уже до конца эти имена использовать и для функций помельче

2021-05-11 14:07 UTC, PeteK12 commented on src/register.cpp
> +        return strtoull(str, end, base);
Да, косяк. Причём и тест есть.

2021-05-11 17:46 UTC, evgeny-boger commented on src/register.cpp
> +    if (reg.Offset == 0) {
>у нас FPU есть

ну если бы мы с нуля разрабатывали, то ок, а так сознательно ухудшать существующий работающий код - не нужно.

2021-05-11 20:27 UTC, webconn commented on src/register.cpp
> +    if (reg.Offset == 0) {
Ну тут ещё поди вспомни, что существующий код, а что новое, когда оно по репозиторию ползает туда-сюда :)

2021-05-12 05:21 UTC, PeteK12 commented on src/register.cpp
> +    if (reg.Offset == 0) {
Вот оригинальный код. Лежал в register_handler.h. Названия методов я не менял. Логика его работы осталась та же.
```cpp
template<>
inline uint64_t TRegisterHandler::FromScaledTextValue(const std::string& str) const
{
    if (Reg->Scale == 1 && Reg->Offset == 0) {
        return std::stoull(str);
    } else {
        return round((RoundValue(stod(str), Reg->RoundTo) - Reg->Offset) / Reg->Scale);
    }
}
```
Кстати, есть ещё один момент, double имеет 52 бита мантиссы, а uint64_t все 64 бита использует. Если всё делать через double, часть значений просто округлится. Но я согласен, что сравнивать double в константой в общем случае противоречивое решение.

2021-05-12 10:19 UTC, webconn commented on src/register.cpp
> +    if (reg.Offset == 0) {
> double имеет 52 бита мантиссы, а uint64_t все 64 бита использует. Если всё делать через double, часть значений просто округлится.

О, а вот об этом я не подумал, это довод в пользу сохранения того, что есть.

2021-05-12 11:59 UTC, PeteK12 commented
1. Добавил возможность задавать в качестве значения параметра число с плавающей точкой.
2. Сделал тест на S24
3. Вернул проверки как в старом коде. Разница только в том, что отдельно проверяются числа в hex и в dec. Старый код вызывал функцию с автоопределением, там если 0 в начале считалось, что число по основанию 8. Плюс добавил проверку, что на знак числа после преобразований для uint64_t.

2021-05-12 12:06 UTC, webconn approved these changes

2021-05-20 05:02 UTC, closed without merging

2021-05-20 05:17 UTC, PeteK12 commented
Сделал rebase https://github.com/wirenboard/wb-mqtt-serial/pull/190