Feature/neva124
wirenboard/wb-mqtt-serial pull request #182
Opened 2021-05-06 16:00 UTC by PeteK12

2021-05-06 17:29 UTC, evgeny-boger requested changes
PR с шаблоном не принят, потому что шаблон не доделан. Можно убрать отсюда шаблон и это влить сейчас.

2021-05-07 04:20 UTC, PeteK12 commented
Как тогда Борис делает чемодан с этим шаблоном?

2021-05-20 22:49 UTC, evgeny-boger requested changes

2021-05-20 22:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "A energy, 3 month ago",
months

2021-05-20 22:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "enabled" : false
обсуждали сегодня, включить по-умолчанию

2021-05-20 22:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
в каком формате там приходят данные?

2021-05-20 22:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Time",
И эти тоже

2021-05-21 10:18 UTC, gavrus87 commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
yymmdd

2021-05-21 10:19 UTC, gavrus87 commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Time",
hhmmss

2021-05-21 11:28 UTC, poglazoff commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
![image](https://user-images.githubusercontent.com/1129843/119130356-c9b9c380-ba40-11eb-9408-0427706b696a.png)
Там численное значение, которое у нас нормально выглядит

2021-05-21 11:31 UTC, PeteK12 commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
Может, доработаем? Добавлю пару типов регистров, и оно будет выдаваться красиво.

2021-05-21 17:00 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
это же ещё тип в конвенции нужно добавлять, думать в каком формате в MQTT добавлять.
@PeteK12 у тебя есть идеи как?

2021-05-25 04:38 UTC, PeteK12 commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
Да, в конвенции надо добавить. Договориться, что в топик писаться будет строкой в формате, например, UTC DD-MM-YYYY HH:MM:SS (25-05-2021 04:28:19). Тогда старые версии web-интерфейса, просто строку человекочитаемую выведут. Проблема в том, что счётчики отдают время в локальном часовом поясе. И никак нельзя узнать, что это за пояс. Так что стоит предусмотреть вариант того, что в MQTT может быть или не быть признак часового пояса. Если есть, то отображать в часовом поясе браузера, если нет - как передали, без преобразования.

2021-05-25 09:20 UTC, webconn commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
`date -R` и в часовом поясе контроллера по умолчанию, ящитаю. Ну или в конфиге явно прописывать.

```
$ date -R
Tue, 25 May 2021 12:19:55 +0300
```

2021-05-25 09:35 UTC, PeteK12 commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
Для счётчиков таки важно то время, которое они внутри себя видят. Пересчитывать в часовой пояс контроллера не стоит, да и не всегда возможно. Вот конкретно для счётчиков я б вообще просто `text` отдал, без доработки конвенции.

2021-05-25 10:04 UTC, webconn commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
Так я не предлагаю пересчитывать время, просто добавлять запись о том, в каком часовом поясе считает счётчик.

2021-05-25 10:12 UTC, PeteK12 commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
Не все отдают часовой пояс. Точнее, я не помню тех, что отдают :)

2021-05-25 10:16 UTC, webconn commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
Ну так вот это можно было бы как раз дописывать в настройки wb-mqtt-serial, ведь пользователь при установке наверняка знает, в каком часовом поясе стоит контроллер :)

2021-05-25 16:10 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-neva-mt124.json
> +                "name": "Date",
проблема надуманная, реальных клиентов и задач на это нет. Оставляем сейчас числом, ничего не думаем и не делаем.

2021-05-27 09:52 UTC, webconn approved these changes

2021-06-01 06:43 UTC, PeteK12 commented
Сделал rebase https://github.com/wirenboard/wb-mqtt-serial/pull/198

2021-06-01 06:43 UTC, closed without merging