Parameters added in MSW v3 template
wirenboard/wb-mqtt-serial pull request #184
Opened 2021-05-07 12:27 UTC by ExplorerOL

2021-05-08 21:37 UTC, evgeny-boger requested changes

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "title": "CO₂ Force Calibration",
это нельзя делать параметром, это надо сделать каналом, выключенным по-умолчанию.
Запись единички в регистр приводит к калибровке по текущему уровню. Если это сделать параметром, то писаться будет каждый раз при запуске wb-mqtt-serial и калибровка будет портится.

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                        "co2_manual_calibration": {
этого регистра больше нет, надо убрать

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                        "co2_autocalibration_period_d": {
и этого больше нет

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "Temperature*100",
зачем так делать? у нас же scale для каналов есть.

Этот регистр (и влажность) особый случай: мы в прошивке 4.2 сделали доступной температуру с точностью до 0.01C, но так как у кого-то датчики с прошивкой меньше 4.2, мы не поменяли это в регистре.
Я бы, наверное, сейчас это просто убрал отсюда.

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "Learn to ROM17",
тут точно пробелов не было перед цифрами раньше?
Обязательно надо сравнить до буквы список каналов со старым шаблоном и с этим, существующие каналы не должны никак переименоваться.

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "title": "Noise Averaging Time (*10 ms)",
@PeteK12 а в параметры scale и format приделать будет насколько тяжело?

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                        "motion_avrg_period_s": {
avg

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "MCU voltage",
большие буковки

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "Number of successful readings of temperature and humidity sensor",
1) не надо такое безумно длинное название канала
2) Это надо не в HW info, в вообще в какой-то debug выносить

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "Baseline of VOC sensor",
VOC Baseline

это в блок с VOC

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "VOC sensor raw reading",
VOC Raw

это в блок Debug

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "VOC sensor version",
и это в блок Debug

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "VOC sensor version",
VOC Version

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "Motion sensor raw reading",
и это в блок Debug
и переименовать

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                        "packet_response_delay_ms": {
rs485_response_delay_ms

2021-05-08 21:37 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "title": "RS485 Packet Response Delay (ms)",
Слово packet здесь лишнее и бесполезное, RS-485 через дефис

2021-05-08 21:40 UTC, evgeny-boger requested changes
а где регистры:

86, 87, 92, 93, 100 - нужны в debug как каналы

2021-05-10 06:47 UTC, PeteK12 requested changes

2021-05-10 06:47 UTC, PeteK12 commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "LED Period (s)",
Я бы тут добавил ещё "id": "LED period". Т.к. в текущем виде "LED Period (s)" будет в названии топика. И в остальных названиях каналов я бы тоже убрал единицы измерения и множители.

2021-05-10 06:47 UTC, PeteK12 commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "title": "Noise Averaging Time (*10 ms)",
format уже есть, scale - пару строк добавить

2021-05-10 08:26 UTC, PeteK12 commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "title": "Noise Averaging Time (*10 ms)",
А чё-то я поспешил, scale - не пару строк.

2021-05-10 13:15 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "LED Period (s)",
оно так и было LED Period (s) раньше, так что менять уже поздно

2021-05-10 14:05 UTC, PeteK12 commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "LED Period (s)",
Тогда в новых каналах посмотреть, чтоб не появилось

2021-05-11 05:51 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "Learn to ROM17",
В исходном шаблоне пробелов не было.

2021-05-11 08:19 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                        "motion_avrg_period_s": {
Исправил

2021-05-11 08:21 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "Number of successful readings of temperature and humidity sensor",
Сделал

2021-05-11 08:21 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "Baseline of VOC sensor",
Сделал

2021-05-11 08:23 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "VOC sensor raw reading",
Сделал

2021-05-11 08:24 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "name": "Motion sensor raw reading",
Сделал

2021-05-11 08:25 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                            "title": "RS485 Packet Response Delay (ms)",
Сделал

2021-05-19 12:49 UTC, evgeny-boger requested changes

2021-05-19 12:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "title": "Air Parameters",
Давай группу в "Air Quality" переименуем

2021-05-19 12:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "title": "CO₂ Autocalibration Mode",
CO₂ Baseline Calibration

"off"
"automatic"

мы сюда ещё будем в будущем добавлять режимы

2021-05-19 12:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "default": 2000,
по-умолчанию 5000

2021-05-19 12:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "title": "TH Compensation (deg)",
Self-Heating Compensation (°C)

2021-05-19 12:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "title": "Averaging Time (ms)",
Low-pass Filter Time Constant (ms)

2021-05-19 12:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "title": "Averaging Time (s)",
Low-pass Filter Time Constant (s)

2021-05-19 12:49 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "name": "MCU Voltage",
давай это в debug

2021-05-19 13:03 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "title": "Air Parameters",
Сделал

2021-05-19 13:05 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "title": "CO₂ Autocalibration Mode",
Сделал

2021-05-19 13:05 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "default": 2000,
Сделал

2021-05-19 13:12 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "title": "TH Compensation (deg)",
Сделал

2021-05-19 13:14 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "title": "Averaging Time (ms)",
Сделал

2021-05-19 13:15 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "title": "Averaging Time (s)",
Сделал

2021-05-19 13:16 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "name": "MCU Voltage",
Сделал

2021-05-19 13:58 UTC, evgeny-boger approved these changes
ждём попадания групп и min/max/scale в master и вливаем

2021-05-21 11:16 UTC, merged