Parameters were added in MR6C template
wirenboard/wb-mqtt-serial pull request #186
Opened 2021-05-12 09:25 UTC by ExplorerOL

2021-05-24 13:14 UTC, evgeny-boger requested changes

2021-05-24 13:14 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-mr6c.json
> +                "turn off all relays after power off",
after power on

2021-05-24 13:14 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-mr6c.json
> +                "save last relay state after power off"
то же самое

2021-05-24 13:14 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-mr6c.json
> +                "title": "State After Power Off",
State After Power On

2021-05-24 13:14 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-mr6c.json
> +                "device_type": "input 1"
а зачем для каждого входа здесь отдельный device_type?

2021-05-24 13:22 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mr6c.json
> +                "device_type": "input 1"
Входы сделаны как subdevices, поэтому указал "device_type"

2021-05-24 13:35 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mr6c.json
> +                "turn off all relays after power off",
Сделал

2021-05-24 13:35 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mr6c.json
> +                "save last relay state after power off"
Сделал

2021-05-31 03:59 UTC, evgeny-boger requested changes
Input X counter нужно включить по-умолчанию - они используются в правилах для обработки нажатия на кнопки

всё остальное отлично, делай так же во всех шаблонах реле

2021-05-31 13:47 UTC, ExplorerOL commented
> Коллеги, я очень ценю гранулярность в коммитах и всё такое, но от такого обилия коммитов сходит с ума почта у всех подписанных и билдсервер :)
> Хочу попросить либо делать все эти правки в отдельной веточке, которую в итоге потом влить в эту (можно даже со слиянием коммитов), либо просто пушить их пачками, а не по одному.

Ясно, постараюсь пушить в следующий раз не по одному.

2021-06-15 19:04 UTC, evgeny-boger requested changes
в master уже есть режимы входов и они называются in0_mode, а не input0_mode.
Надо такое название параметра и оставить для совместимости - вдруг кто-то из пользователей уже успел попользоваться.

2021-06-17 13:35 UTC, merged