Template WB-MSv2 with parameters
wirenboard/wb-mqtt-serial pull request #202
Opened 2021-06-04 10:48 UTC by ExplorerOL

2021-06-22 23:17 UTC, evgeny-boger requested changes

2021-06-22 23:17 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-ms_v2.json
> +                "address": 0,
а зачем ты здесь поменял адрес?

2021-06-23 05:20 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-ms_v2.json
> +                "address": 0,
Распределил каналы по аналогии с MSWv3 (там были использованы каналы с более низкой точностью). Не обратил внимание, что здесь каналы с повышенной точностью уже были использованы. Переделал.

2021-06-23 13:07 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-ms_v2.json
> +                "address": 0,
лучше про это явно писать, если такие изменения делаешь. Логика была такая: MS **v.2** выходил уже тогда, когда в прошивке была поддержка каналов с повышенной точностью.

А с MSW v.3 есть шанс получить клиента с древней прошивкой, где это ещё не поддерживается.

2021-07-06 07:22 UTC, wb-adegtyarev commented
Мне нравится.

2021-08-14 13:19 UTC, merged