Template M1W2 DI with parameters
wirenboard/wb-mqtt-serial pull request #208
Opened 2021-06-08 06:51 UTC by ExplorerOL

2021-07-08 07:54 UTC, wb-adegtyarev commented
Предлагаю опрос параметров **External Sensor 1 OK** и **External Sensor 2 OK** по умолчанию отключить — для обычного пользователя смысла в них мало, а место в Devices и время опроса занимает.

В остальном мне нравится.

2021-07-10 14:12 UTC, evgeny-boger requested changes
External Sensor  OK

надо отключить, да

2021-07-12 13:44 UTC, ExplorerOL commented
Отключил по умолчанию каналы External Sensor X OK

2021-07-19 17:40 UTC, evgeny-boger requested changes
если честно, по-моему мы какую-то ерунду сделали. У нас есть одна железка - WB-M1W2. Раньше у нас нельзя было делать субдевайсы, группы, параметры и т.д., поэтому у нас было два шаблона: просто M1W2, когда подключены 1-Wire датчики и M1W2 DI, когда подключены дискретные входы.

Потом Пётр добавил режим входа в M1W2 DI, но почему-то не добавил в M1W2. 
А теперь ты в этом шаблоне M1W2-DI обратно эти параметры убираешь, получается.

Это всё как-то совершенно непонятно. У нас должен быть шаблон, где я могу выбрать режим каждого входа. В зависимости от режима, должен появляться либо канал с температурой, либо с состоянием дискретного входа.
Этот шаблон должен быть один и называться просто M1W2. 

M1W2 DI мы либо делаем полной копией и пишем в комментариях внутри, что это полная копия, оставленная для совместимости, либо просто не трогаем и всё.

2021-07-20 11:10 UTC, ExplorerOL commented
Да, в таком случае, думаю, лучше шаблон M1W2-DI вообще не трогать. Создам ветку для изменения шаблона M1W2, а эту тогда, наверное, можно будет удалить.

2021-07-20 11:28 UTC, closed without merging