Template MIR v2 with parameters
wirenboard/wb-mqtt-serial pull request #210
Opened 2021-06-08 13:10 UTC by ExplorerOL

2021-07-08 08:06 UTC, wb-adegtyarev commented
Выглядит хорошо, но есть вопрос — стоит ли включать сразу все каналы из секции IR Commands и параметр External Temperature Sensor OK?

2021-07-11 10:48 UTC, evgeny-boger requested changes
Sensor OK отключить
количество банков, включенных по умолчанию, ограничить десятью.

2021-07-12 13:57 UTC, ExplorerOL commented
Канал External Sensor OK и ИК каналы 11-20 сделал выключенным по умолчанию

2021-07-12 20:53 UTC, evgeny-boger requested changes
а почему кстати 20 банков? У нас разве не больше в MIR реально?

2021-07-13 04:41 UTC, ExplorerOL commented
20 банков было в шаблоне до изменения. Я оставил это количество.

2021-08-14 14:21 UTC, merged