Template MDM3 with parameters
wirenboard/wb-mqtt-serial pull request #214
Opened 2021-06-10 07:34 UTC by ExplorerOL

2021-06-10 09:19 UTC, nikitoz236 requested changes

2021-06-10 09:19 UTC, nikitoz236 commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                    "disable communication between inputs and output",
disable button control?

2021-06-10 09:19 UTC, nikitoz236 commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "title": "Channel 1 Min Value",
(us)

2021-06-10 09:19 UTC, nikitoz236 commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "title": "Channel 1 Max Value",
(us)

2021-06-10 09:19 UTC, nikitoz236 commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "name": "Channel 1 Actual Value",
(us)

2021-06-10 09:19 UTC, nikitoz236 commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "name": "Zero-cross Offset",
(us)

2021-06-10 09:19 UTC, nikitoz236 commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "readonly": true,
их можно записывать и это может быть даже полезно. покрайнеймере в документации они RW

2021-06-10 09:19 UTC, nikitoz236 commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +            },
нам точно нравится группировка гдее входы тамже где и каналы? ведь это более широкая сущность. ими можно опрашивать дискретные сигналы и по мимо прочего управлчть выходами. хотя совершенно не настаиваю. возможно если входы будут отдельной групой то в каналах будет пусто. но там вродебы как очень много настроек. такчто я бы подумал чтобы вынести входы в отдельную группу. но не настаиваю.

2021-06-10 09:29 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "readonly": true,
Я бы лучше назвал Channel 1 Raw Phase или Raw Duty, а то по Value не понятно, что это всё-таки такое

2021-06-10 12:31 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                    "disable communication between inputs and output",
Предлагаю так: "contol disabled"

2021-06-11 13:46 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                    "disable communication between inputs and output",
Переделал

2021-06-11 13:48 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "title": "Channel 1 Min Value",
добавил

2021-06-11 13:48 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "title": "Channel 1 Max Value",
добавил

2021-06-11 13:49 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "name": "Channel 1 Actual Value",
добавил

2021-06-11 13:49 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "name": "Zero-cross Offset",
добавил

2021-06-11 13:57 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "readonly": true,
Поменял название

2021-06-11 15:24 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +            },
Я выделил входы в отдельную группу. В диммере MRGBW-D тоже так сделать, видимо, придется, так как там есть вход, управляющий яркостью всех каналов. Но группировка "где входы, там и каналы" мне больше нравится.

2021-06-25 15:45 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "name": "Zero-cross Offset (us)",
думаю `Zero-Cross`, большая буква

2021-06-28 11:57 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mdm3.json
> +                "name": "Zero-cross Offset (us)",
Поправил

2021-06-29 14:05 UTC, brainroot reviewed
Годно, работает

2021-07-09 05:52 UTC, wb-adegtyarev commented
Посмотрел, субъективные замечания:
1. Может Input N counter по умолчанию выключим? Мало кому нужно, а их опрос линию нагружает.
2. Channel N Control Type — может Channel N Control Mode? В карте регистров написано «Режим диммирования канала».
3. Channel 1 Increase Rate — я плохо знаю английский и для меня как-то неочевидно, в карте регистров «Скорость канала при увеличении яркости».

В остальном всё понятно и удобно.

2021-08-15 18:46 UTC, evgeny-boger approved these changes

2021-08-15 18:57 UTC, merged