Energomera CE102M support is added
wirenboard/wb-mqtt-serial pull request #236
Opened 2021-07-14 06:25 UTC by KraPete

2021-07-14 09:37 UTC, evgeny-boger requested changes
отлично, спасибо!

Проверял Неву с другими счётчиками на стенде с этим кодом долго? Я вижу, что тут закрытие сессии добавилось, и в этих местах с невой раньше были проблемы.

2021-07-14 09:37 UTC, evgeny-boger commented on src/devices/neva_device.cpp
> -    if (reg->TypeName == "obis_cdef_pf") {
может сделать эти obis_cdef_* deprecated, а шаблоны и документацию переписать в унифицированном с энергомерой виде? Типа чтобы было 

```
address: "100700FF()"
```

2021-07-14 09:37 UTC, evgeny-boger commented on src/devices/energomera_iec_mode_c_device.cpp
> +    class TStringRegisterAddress: public IRegisterAddress
не надо ли этот класс и класс ниже вынести в какое-то общее место из устройства энергомера?

2021-07-14 09:37 UTC, evgeny-boger commented on src/devices/energomera_iec_mode_c_device.cpp
> +uint64_t TEnergomeraIecModeCDevice::GetRegisterValue(const TRegister& reg, const std::string& value)
а эта энергомера не отдаёт несколько чисел через запятую, как нева?

2021-07-14 10:26 UTC, KraPete commented
> отлично, спасибо!
> 
> Проверял Неву с другими счётчиками на стенде с этим кодом долго? Я вижу, что тут закрытие сессии добавилось, и в этих местах с невой раньше были проблемы.

Прям с этим кодом не долго, но закрытие сессии и раньше делалось. В том виде я пару дней гонял, проблем не увидел. Раньше закрытие сессии не попадало в тесты, я добавил, чтоб проверялось.

2021-07-14 10:31 UTC, KraPete commented on src/devices/neva_device.cpp
> -    if (reg->TypeName == "obis_cdef_pf") {
Я думал про это, но надо будет аналог obis_cdef_temp, obis_cdef_pf, т.к. они хитро разбираются. Плюс obis_cdef_N тоже неваспецефичные. У энергомеры, например, не список через запятую, а каждый элемент в скобках и разделён через CRLF. Т.е. выигрыша почти нет.

2021-07-14 10:34 UTC, KraPete commented on src/devices/energomera_iec_mode_c_device.cpp
> +uint64_t TEnergomeraIecModeCDevice::GetRegisterValue(const TRegister& reg, const std::string& value)
Отдаёт, только не через запятую, а каждый элемент в скобочках и разделённый через CRLF. Делать ещё кучу типов регистров не захотелось. Хотя, если с невой унифицировать, можно добавить что-то типа "array1", "array2" и везде использовать. Но классы протоколов всё равно разные будут.

2021-07-14 10:35 UTC, KraPete commented on src/devices/energomera_iec_mode_c_device.cpp
> +    class TStringRegisterAddress: public IRegisterAddress
Вынесу

2021-07-14 11:44 UTC, evgeny-boger commented on src/devices/energomera_iec_mode_c_device.cpp
> +uint64_t TEnergomeraIecModeCDevice::GetRegisterValue(const TRegister& reg, const std::string& value)
а у нас нигде не понадобилась в шаблонах? Тут же нет поддержки этого в драйвере. 

Мне кажется, стоит добавить, кажется несложно.

Унифицировать драйвера тогда не надо, но вот запись регистров в шаблонах - может быть удобно унифицировать.

2021-07-14 14:05 UTC, KraPete commented
Добавил общие типы для ответов со списками. Старые оставил, чтоб не ломать настройки клиентов, если кто-то использовал явно.

2021-07-14 15:54 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-energomera-ce102m.json
> +        "address": "ET0PE()"
я что-то запутался. А на `ET0PE(5)` оно именно `ET0PE(5)` и отправляло по шине и получало одно число в ответе?

2021-07-14 16:15 UTC, KraPete commented on wb-mqtt-serial-templates/config-energomera-ce102m.json
> +        "address": "ET0PE()"
Да. А если параметр не указывать, то 6 значений. Т.е. вместо нескольких запросов всё в одном.

2021-07-15 08:52 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-energomera-ce102m.json
> +        "address": "ET0PE()"
а зачем тогда так делать в шаблоне? Оно же всё равно на каждый параметр отдельный запрос отправит

2021-07-15 10:07 UTC, KraPete commented on wb-mqtt-serial-templates/config-energomera-ce102m.json
> +        "address": "ET0PE()"
Нет, оно отправит один запрос за цикл опроса, остальное из кэша подтянется.
https://github.com/wirenboard/wb-mqtt-serial/blob/4fdf7606c7a8313bdc7991e413b939bc05837a57/src/iec_common.cpp#L271

2021-07-15 12:43 UTC, evgeny-boger reviewed
видимо если до последнего коммита тесты не ломались, то их нужно какие-то добавить

2021-07-15 13:41 UTC, KraPete commented
@evgeny-boger Done

2021-07-15 23:29 UTC, evgeny-boger approved these changes

2021-07-16 07:24 UTC, KraPete commented
Rebase https://github.com/wirenboard/wb-mqtt-serial/pull/239

2021-07-16 07:24 UTC, closed without merging