Separate Energomera CE301 and CE303 templates
wirenboard/wb-mqtt-serial pull request #246
Opened 2021-07-23 13:59 UTC by Lethaquell

2021-07-26 12:07 UTC, evgeny-boger requested changes
Возможно стоит CE301/303 оставить с тем же device_type, как сейчас, но убрать реактивную энергию. CE303 добавить.

Ещё нужно добавить этот шаблон в список в README.

2021-07-26 12:07 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-energomera-ce301.json
> +  "device_type": "Energomera CE301",
надо понимать, что вот это всё-таки сломает конфиги людям. В конфиге указывается device_type. Если оно уже было в стабильном репозитории, то так делать нельзя.

2021-07-27 09:45 UTC, evgeny-boger reviewed
проверил, что в интерфейсе выбора шаблона в веб-интерфейсе отображается именно этот title?

2021-07-27 10:27 UTC, Lethaquell commented
Залил конфиги напрямую в WB.
Работа по конфигу **CE301** _(бывший CE301/CE303)_:
_id *543 - CE303, id *623 - CE301_
![Screenshot from 2021-07-27 13-23-32](https://user-images.githubusercontent.com/8237884/127138953-a289c746-fa2e-4259-aa4b-569c06a75e41.png)
![Screenshot from 2021-07-27 13-20-02](https://user-images.githubusercontent.com/8237884/127138972-74df2f8e-db69-4185-a2f6-7af3837595f6.png)
![Screenshot from 2021-07-27 13-23-14](https://user-images.githubusercontent.com/8237884/127139136-d47cd81a-4eea-4514-9704-92bb056cd476.png)
Перекинул **СЕ303** на новый отдельный шаблон:
![Screenshot from 2021-07-27 13-23-52](https://user-images.githubusercontent.com/8237884/127139234-15992103-7cdc-4aca-903f-4d2f416557c5.png)
![Screenshot from 2021-07-27 13-20-44](https://user-images.githubusercontent.com/8237884/127139239-65db3c3c-2c92-4932-be20-093735c16464.png)

2021-07-27 11:28 UTC, merged