Template DANFOSS-FC51 was added
wirenboard/wb-mqtt-serial pull request #251
Opened 2021-08-04 13:33 UTC by ExplorerOL

2021-08-04 14:11 UTC, poglazoff commented on debian/changelog
> +  * Template for DANFOSS-FC51 was added
А здесь и дальше название не должно быть `Danfoss FC 51`?

2021-08-04 14:24 UTC, ExplorerOL commented on debian/changelog
> +  * Template for DANFOSS-FC51 was added
Я делал по аналогии с нашими шаблонами. Там, например, WB-MR6C.

2021-08-04 14:29 UTC, poglazoff commented on debian/changelog
> +  * Template for DANFOSS-FC51 was added
Это потому что у нас устройство называется как раз `WB-MR6C`. А для других устройств мы пишем так, как они называются. Например, https://github.com/wirenboard/wb-mqtt-serial/blob/master/wb-mqtt-serial-templates/config-energomera-ce308.json

2021-08-05 12:39 UTC, evgeny-boger requested changes

2021-08-05 12:39 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-danfoss-fc51.json
> +    "title": "Danfoss FC51",
он с пробелом в оригинале, тут должно быть FC 51

2021-08-05 12:39 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-danfoss-fc51.json
> +        "name": "Danfoss FC51",
и в этой строчке тоже

2021-08-05 15:14 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-danfoss-fc51.json
> +    "title": "Danfoss FC51",
Исправил

2021-08-05 15:14 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-danfoss-fc51.json
> +        "name": "Danfoss FC51",
Исправил. Также соответствующим образом подправил поля "title" и "id"

2021-08-08 03:05 UTC, evgeny-boger approved these changes

2021-08-14 11:53 UTC, merged