Config's setup section priority is raised
wirenboard/wb-mqtt-serial pull request #265
Opened 2021-09-02 13:14 UTC by KraPete

Rebase of https://github.com/wirenboard/wb-mqtt-serial/pull/261

Setup registers in config have higher priority than setup registers with same addresses from device templates.

2021-09-02 13:20 UTC, webconn approved these changes

2021-09-02 13:22 UTC, webconn commented
@evgeny-boger можешь глянуть тоже? Вопрос идейный

2021-09-02 19:33 UTC, evgeny-boger requested changes
а я хочу подробное сообщение об ошибке, как в чате писал. Получится?

2021-09-03 15:45 UTC, evgeny-boger approved these changes

2021-09-06 04:20 UTC, merged