Danfoss AK-PC 351 template was added
wirenboard/wb-mqtt-serial pull request #297
Opened 2021-09-15 14:11 UTC by ExplorerOL

Объединил в один шаблон режим ввода уставок и мониторинга по температуре и давлению. По давлению каналы отключил по умолчанию. Параметры не добавлял.

2021-09-16 19:09 UTC, evgeny-boger requested changes

2021-09-16 19:09 UTC, evgeny-boger commented on wb-mqtt-serial-templates/config-danfoss-ak-pc-351.json
> +                "name": "Compressor Control Status",
а что именно в этих переменных лежит понятно?

2021-09-17 05:27 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-danfoss-ak-pc-351.json
> +                "name": "Compressor Control Status",
В этих переменных хранится статус работы компрессора и испарителя: остановлен, работает, авария, ожидание.

2021-09-17 06:40 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-danfoss-ak-pc-351.json
> +                "name": "Compressor Reference Pressure ",
убрал

2021-09-17 06:40 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-danfoss-ak-pc-351.json
> +                "name": "Condencer Actual Pressure",
исправил

2021-11-10 20:02 UTC, closed without merging