Bus load and poll interval metrics
wirenboard/wb-mqtt-serial pull request #298
Opened 2021-09-16 06:41 UTC by KraPete

2021-09-16 17:10 UTC, webconn commented on src/metrics.cpp
> +    const microseconds IntervalDuration(60000000);
`seconds(60)` выглядело бы не так устрашающе

2021-09-16 17:56 UTC, webconn requested changes
Я пока только код смотрел, ещё разверну на контроллере и посмотрю, что получится

2021-09-16 17:56 UTC, webconn commented on src/metrics.cpp
> +    const microseconds IntervalDuration(60000000);
`seconds(60)` выглядело бы не так устрашающе

2021-09-16 17:56 UTC, webconn commented on test/metrics_test.cpp
> +    t += std::chrono::seconds(15*60);
`minutes(15)` :)

2021-09-16 17:56 UTC, webconn commented on src/serial_client.cpp
> +        Metrics.StartPoll("wb-mqtt-serial", std::chrono::steady_clock::now());
Стоит вынести эту строку в константу. А чем это отличается от `idle`, что тут замеряется?

2021-09-16 17:56 UTC, webconn commented on src/serial_client.cpp
> +        Metrics.StartPoll(handler->Device()->DeviceConfig()->Id + "/Command", std::chrono::steady_clock::now());
Напрашивается перенос `steady_clock::now()` в значение по умолчанию, или в перегруженную функцию, а то повторяется везде и выглядит громоздко

2021-09-16 17:56 UTC, webconn commented on src/serial_client.cpp
> +    Metrics.StartPoll("idle", std::chrono::steady_clock::now());
`idle` лучше в константу

2021-09-16 17:56 UTC, webconn commented on README.md
> +        "name": "Device/Channel",
Не написал про `port`, это ж важно )

2021-09-16 17:56 UTC, webconn commented on src/metrics.cpp
> +    if (!IntervalStartTime.time_since_epoch().count()) {
Чуть выше ты проверяешь пустоту по другому: ` == steady_clock::time_point()`, и та проверка мне кажется  аккуратней

2021-09-16 17:56 UTC, webconn commented on src/metrics.cpp
> +            RotateChunks();
Интересно прикинуть, доставит ли это неудобства, если у нас какой-то канал долго будет в отключке (например, обесточили Vout), а потом включится

2021-09-17 04:47 UTC, KraPete commented on src/serial_client.cpp
> +        Metrics.StartPoll("wb-mqtt-serial", std::chrono::steady_clock::now());
"idle" - это `this_thread::sleep`
"wb-mqtt-serial" - это публикация в MQTT и всякие действия, несвязанные с запросами на шине
"имя устройства" - это открытие и закрытие сессии с запросами по шине для конкретного устройста

2021-09-17 04:48 UTC, KraPete commented on README.md
> +        "name": "Device/Channel",
Да! Забыл. Добавлю

2021-09-17 04:53 UTC, KraPete commented on src/metrics.cpp
> +            RotateChunks();
Некоторое неудобство может быть, если у нас есть канал с очень большим периодом опроса, тогда да, тут цикл покрутится.

2021-09-17 05:50 UTC, KraPete commented on src/metrics.cpp
> +            RotateChunks();
Поправил

2021-09-17 05:50 UTC, KraPete commented on src/metrics.cpp
> +    if (!IntervalStartTime.time_since_epoch().count()) {
Сделал как выше

2021-09-17 05:50 UTC, KraPete commented on src/serial_client.cpp
> +    Metrics.StartPoll("idle", std::chrono::steady_clock::now());
Добавил

2021-09-17 05:50 UTC, KraPete commented on src/serial_client.cpp
> +        Metrics.StartPoll(handler->Device()->DeviceConfig()->Id + "/Command", std::chrono::steady_clock::now());
Добавил значение по умолчанию

2021-09-17 05:50 UTC, KraPete commented on src/serial_client.cpp
> +        Metrics.StartPoll("wb-mqtt-serial", std::chrono::steady_clock::now());
Добавил константу

2021-09-17 05:50 UTC, KraPete commented on test/metrics_test.cpp
> +    t += std::chrono::seconds(15*60);
Поменял

2021-09-17 05:51 UTC, KraPete commented on src/metrics.cpp
> +    const microseconds IntervalDuration(60000000);
Поменял

2021-09-20 16:27 UTC, webconn reviewed
Попробовал у себя на контроллере, результат понравился. Приятное ощущение большего понимания происходящего. Одно небольшое предложение всё же оставлю, и думаю, что это надо вливать и тестировать

2021-09-20 16:27 UTC, webconn commented on src/serial_client.cpp
> +    Metrics.StartPoll(dev->DeviceConfig()->Id + "/" + MakeChannelNamesString(range->RegisterList()));
Предлагаю тут сразу сделать что-то машиночитаемое, чтобы в JSON превращалось во что-то вроде

```json
{
  "device": "...",
  "controls": [ "...", "...", "..." ]
}
```

вместо строки с неожиданным форматированием, а то потом парсить будет сложно

2021-09-20 18:51 UTC, evgeny-boger commented on src/serial_client.cpp
> +    Metrics.StartPoll(dev->DeviceConfig()->Id + "/" + MakeChannelNamesString(range->RegisterList()));
а я за то, чтобы это был прямо список из "dev_id/ctrl_id". С этим потом всё работает, да и глазами оно удобнее смотреть.

2021-09-30 10:40 UTC, KraPete commented
Тест добавил и сделал отдельные метрки для начала и конца сессии опроса устройства

2021-09-30 10:50 UTC, webconn approved these changes
Для обкатки сойдёт, думаю. В будущем эти метрики, не связанные непосредственно с опросами, я бы как-то отдельно от всего отправлял, или помечал их специально (а то сейчас можно запросто назвать регистр "Start session" и получить коллизию)

2021-09-30 11:01 UTC, KraPete commented
Rebase https://github.com/wirenboard/wb-mqtt-serial/pull/317

2021-09-30 11:01 UTC, closed without merging