Unique hash ids are generated for all translations from templates
wirenboard/wb-mqtt-serial pull request #315
Opened 2021-09-29 13:08 UTC by KraPete

Thus translation collisions are eliminated

2021-09-29 17:38 UTC, webconn requested changes

2021-09-29 17:38 UTC, webconn commented on src/confed_schema_generator.cpp
> +        return "t" + std::to_string(std::hash<std::string>()(deviceType + msg));
Мне не очень нравится, что прямо в схему в title пишется только хеш, и если JSON editor взглючит, все эти строки станут нечитаемыми. Предлагаю выводить исходный `msg`, но добавлять к нему в конце несколько первых символов хеша, это не сломает новую логику + оставит читаемость в случае, если что-то сломается

2021-09-29 17:38 UTC, webconn commented on src/confed_schema_generator.cpp
> +        std::string AddHashedTranslation(const std::string& msg)
Название функции путает, кажется, что на выходе будет уже переведённая строка. `AddHashedTranslationKey`, может, было бы лучше

2021-09-30 06:37 UTC, KraPete commented on src/confed_schema_generator.cpp
> +        return "t" + std::to_string(std::hash<std::string>()(deviceType + msg));
Тогда мы получим дублирование строк в схеме. Строка будет как ключ и как сама строка. У нас и так схема огромная выходит. В запросе перевода нет сложной логики, если оно сломается, то будет сломано вообще всё вокруг.

2021-09-30 06:51 UTC, KraPete commented on src/confed_schema_generator.cpp
> +        std::string AddHashedTranslation(const std::string& msg)
Фактически в функции мы добавляем перевод в список. `AddHashedTranslationKey` тоже не отражает сути. Добавил комментарий

2021-09-30 06:51 UTC, KraPete commented on debian/changelog
> +    Translations from one template will note be used for strings from other template.
Исправил

2021-10-01 08:16 UTC, webconn commented on src/confed_schema_generator.cpp
> +        return "t" + std::to_string(std::hash<std::string>()(deviceType + msg));
Ну вот я заглянул в сгенерированную схему, а там половина сообщений нормальным текстом записана, а вторая - циферками. До хешей раньше ведь были полные сообщения, и ничего, а так просто хвост из 4 циферок к каждому ключу добавить, не должно взрывным образом увеличить схему.

Впрочем, это правда лирика, я тоже не могу придумать ситуации, когда это наглухо сломается (ну разве что старый homeui, который не осилит в переводы)

2021-10-01 08:17 UTC, webconn approved these changes

2021-10-05 06:24 UTC, KraPete commented
Rebase https://github.com/wirenboard/wb-mqtt-serial/pull/320

2021-10-05 06:24 UTC, closed without merging