Cityron ПУ-3 template was added
wirenboard/wb-mqtt-serial pull request #366
Opened 2021-12-16 07:11 UTC by ExplorerOL

2021-12-17 07:44 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Selected Mode": "Выбранный режим",
Просто _Режим_

2021-12-17 07:44 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Cooling Mode Allowed": "Режим охлаждения разрешен",
Охлаждение

2021-12-17 07:44 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Heating Mode Allowed": "Режим нагрева разрешен",
Нагрев

2021-12-17 07:44 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Ventilation Mode Allowed": "Режим вентиляции разрешен",
Вентиляция

2021-12-17 07:44 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Auto Mode Allowed": "Автоматический режим разрешен",
Автоматический режим

2021-12-17 07:44 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Panel On": "Панель включена",
Статус панели

2021-12-17 07:44 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Filter Alarm": "Ошибка фильтра",
Решили, что будет _Заменить фильтр_

2021-12-17 07:44 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Additional Temperature": "Дополнительная температура",
Основная и дополнительная температура: всё равно мало о чём говорит без объяснения и экспериментов. Но лучше не придумал.

2021-12-17 13:50 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Filter Alarm": "Ошибка фильтра",
исправил

2021-12-17 13:50 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Panel On": "Панель включена",
исправил

2021-12-17 13:50 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Auto Mode Allowed": "Автоматический режим разрешен",
Скорректировал

2021-12-17 13:51 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Ventilation Mode Allowed": "Режим вентиляции разрешен",
Скорректировал

2021-12-17 13:51 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Heating Mode Allowed": "Режим нагрева разрешен",
Скорректировал

2021-12-17 13:51 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Cooling Mode Allowed": "Режим охлаждения разрешен",
Скорректировал

2021-12-17 13:51 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "Selected Mode": "Выбранный режим",
исправил

2021-12-17 14:15 UTC, wb-adegtyarev approved these changes

2021-12-20 05:08 UTC, KraPete requested changes
А точно все регистры доступны для записи? Не надо расставить `readonly`?

2021-12-20 05:08 UTC, KraPete commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +        "guard_interval_us": 5000,
Из каких соображений выбраны frame_timeout_ms и guard_interval_us?

2021-12-20 05:08 UTC, KraPete commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +        "max_read_registers": 1,
Можно не писать, по умолчанию и так 1.

2021-12-20 05:08 UTC, KraPete commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "format": "s16",
Минуты могут быть отрицательными? Это и остальных параметров времени касается.

2021-12-20 05:54 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +        "guard_interval_us": 5000,
frame_timeout_ms выбран по аналогии с датчиком MSW.v3. Так как высокая скорость опроса тут не требуется, указал с запасом.
guard_interval_us выбран для соответствия стандарту Modbus RTU при работе на скорости 9600 бит/с.

2021-12-20 06:00 UTC, KraPete commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +        "guard_interval_us": 5000,
1. Если надо frame_timeout_ms просто по стандарту, то не надо его писать вообще.
2. А, если его не адавать, устройство будет рпаботать?

2021-12-20 06:04 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +        "max_read_registers": 1,
Указал явно для акцентирования внимания и для того, что если настройки по умолчанию изменятся, то ничего не сломается.

2021-12-20 06:07 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +        "guard_interval_us": 5000,
Да, все регистры доступны для записи и чтения, проверил.

2021-12-20 06:26 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +        "guard_interval_us": 5000,
Да, если не указывать frame_timeout_ms, то все работает, ошибок нет. Тогда уберу эту опцию.

2021-12-20 06:27 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +        "max_read_registers": 1,
Убрал.

2021-12-20 06:39 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-cityron-pu-3.json
> +                "format": "s16",
Исправил. Хотя там значения, выходящие за реально возможные записать не получится.

2021-12-20 06:54 UTC, KraPete approved these changes

2021-12-20 08:57 UTC, merged