Added WB-MRGBW-D fw3 template
wirenboard/wb-mqtt-serial pull request #367
Opened 2021-12-17 07:36 UTC by pgasheev

2021-12-17 16:28 UTC, wb-adegtyarev reviewed
Оставил комментарии и предложения

2021-12-17 16:28 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
> +
Тут тёплое с мягким спуталось.
Нажатия могут быть или короткие и длинные, или быстрые и долгие.

Мне нравится Короткие и Длинные

2021-12-17 16:28 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
> +
Где-то выше hue было написано большими буквами, как HUE — лучше привести к одному виду.

2021-12-17 16:28 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
> +
Может как-то получится перефразировать? Задание странно звучит для непрограммиста.

2021-12-17 16:28 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
> +
В двух предыдущих блоках ошибка в окончании: 
Выключить каналов… → Выключить каналы
Переключить каналов → Переключить каналы

2021-12-17 16:28 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
> +
Вопрос про Задание я написал ниже.

2021-12-20 12:15 UTC, wb-adegtyarev approved these changes

2021-12-22 15:12 UTC, ExplorerOL requested changes

2021-12-22 15:12 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
> +
Вот это имя канала лучше исправить. Спецсимволы лучше не использовать, единицы измерения тоже под вопросам или хотя бы в скобках. Это еще в название канала MQTT уедет, при использовании в правилах будут проблемы. Можно имя канала MQTT задавать отдельно полем "id". Но тогда возникает некоторая путаница: видно название одно, а имя канала другое.

другие поля "name" тоже надо проверить на отсутствие спецсимволов (я больше не нашел) и на предмет их краткости.

2021-12-22 15:12 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
> +                            "name": "Channels 3, 4 (G_W)",
Нужно уточнить про использование запятых в названиях каналов. Думаю, это нехорошо

2021-12-22 15:15 UTC, ExplorerOL requested changes
Оставил комментарии по шаблону в коде.

2021-12-24 15:00 UTC, ExplorerOL reviewed
добавил несколько пожеланий

2021-12-27 08:56 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
> +
> Тогда "Saturation RGB Strip" или "RGB Strip Saturation". Александр (@wb-adegtyarev ), что думаешь?

RGB Strip Saturation — думаю, что хорошо

2021-12-27 14:38 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
> +
Предлагаю вариант Hue, так как Hue - не аббревиатура.

2021-12-28 12:25 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3.json
> +
Для задела на будущее я бы оставил просто fw3. Если появится прошивка 3.1, то будет уже не точно

2021-12-28 12:26 UTC, ExplorerOL approved these changes
В целом все нормально.
Для задела на будущее я бы оставил просто fw3 в описаниях шаблона на английском и русском. Если появится прошивка 3.1, то будет уже не точно

2021-12-30 11:00 UTC, pgasheev commented
Rebase #371

2021-12-30 11:00 UTC, closed without merging