Feature/38428 add write address for channels
wirenboard/wb-mqtt-serial pull request #382
Opened 2022-01-31 07:17 UTC by rkochkin

2022-01-31 11:27 UTC, KraPete commented
1. В чём был смысл делать `enum class` для формата регистра? В любом случае это стоит оформить отдельным коммитом, иначе основные изменения по задаче теряются на фоне массового добавления типа.
2. Надо тест на `write_address`, что он корректно парсится из конифига и, что запросы в модбас корректно формируются.

2022-01-31 11:27 UTC, KraPete requested changes

2022-01-31 11:27 UTC, KraPete commented on src/serial_config.h
> +                                             const std::string& jsonPropertyName = "address");
Лучше это вынести к константам, где `write_address` лежит.

2022-01-31 11:27 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +              "title": "Write Address",
Надо перевод

2022-01-31 11:29 UTC, KraPete commented
Ещё в идеале бы сделать так, чтоб `write_address` бвл доступен из homeui только у тех протоколов, которые умеют его использовать.

2022-02-03 07:54 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +              "title": "Write Address",
Сделал

2022-02-03 07:54 UTC, rkochkin commented on src/serial_config.h
> +                                             const std::string& jsonPropertyName = "address");
Сделал

2022-02-03 09:39 UTC, rkochkin commented
> 1. В чём был смысл делать `enum class` для формата регистра? В любом случае это стоит оформить отдельным коммитом, иначе основные изменения по задаче теряются на фоне массового добавления типа.

Формат регистра много где используется в методах. Область видимости очень широка. Вместо enum формата регистра можно подставить int или другой enum и компилятор  пропустит эту логическую ошибку. 
Если необходимо преобразование в int, это делается явно через static_cast, что добавляет наглядности.
Нужно стремиться уменьшать область видимости.

Ну и, как о рекомендации, здесь сказано:
[CppCoreGuidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enum3-prefer-class-enums-over-plain-enums)

2022-02-04 08:45 UTC, KraPete commented
> Ну и, как о рекомендации, здесь сказано:
> [CppCoreGuidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#enum3-prefer-class-enums-over-plain-enums)

Это то ясно, я скорее про то, зачем это делать именно в это PR. Была ли критическая необходимость? Иначе лучше это отдельным PR оформить.

2022-02-07 07:14 UTC, webconn reviewed
Надо тесты добавить, да, в остальном вроде хорошо.
И в будущем лучше рефакторинг оформлять отдельным коммитом.

2022-02-07 13:00 UTC, closed without merging