Feature/38428 add write address for channels rebase1
wirenboard/wb-mqtt-serial pull request #388
Opened 2022-02-07 11:40 UTC by rkochkin

Является перебазированным PR от:
https://github.com/wirenboard/wb-mqtt-serial/pull/382

* Добавил в схему и в парсер конфига обработку адреса записи ("write_address") для modbus устройства
* Добавил функциональность: если для modbus устройства установлена опция write_address, то запись в регистр осуществляется по адресу записи. Если опция write_address не установлена, то чтение и запись происходит по одному и тому же адресу("address").

Убрал рефакторинг в отдельную ветку.

2022-02-07 13:47 UTC, KraPete requested changes
Сделай, пожалуйста, отдельный тест с одним регистром, у которого есть `write_address`. Сейчас оно размазано по куче спец тестов, и не ясно, что проверяется. Там и так портянки, которые сложно поддерживать.

2022-02-07 13:47 UTC, KraPete commented on src/serial_config.h
> +TRegisterBitsAddress LoadRegisterBitsAddress(const Json::Value& register_data);
Я б вообще выкинул эту функцию, и явно с параметрами вызывал везде. Комментариев нет, не ясно чем эти функции отличаются.

2022-02-07 16:46 UTC, rkochkin commented
> Сделай, пожалуйста, отдельный тест с одним регистром, у которого есть `write_address`. Сейчас оно размазано по куче спец тестов, и не ясно, что проверяется. Там и так портянки, которые сложно поддерживать.

Сделал отдельные тесты для регистра, у которого есть write_address

2022-02-08 05:12 UTC, KraPete reviewed
Всё таки стоит сделать так, чтобы `write_address` в homeui только у modbus устройств был доступен для редактирования

2022-02-08 05:12 UTC, KraPete commented on test/modbus_test.cpp
> +    SerialPort->Close();
Это можно не делать

2022-02-08 05:34 UTC, rkochkin commented on test/modbus_test.cpp
> +    SerialPort->Close();
Не делать SerialPort->Close()?

2022-02-08 05:41 UTC, rkochkin commented
> Всё таки стоит сделать так, чтобы `write_address` в homeui только у modbus устройств был доступен для редактирования

А в какую сторону копать? Нужно менять код в [homeui](https://github.com/wirenboard/homeui) и в частности в json editor-е?

2022-02-08 08:55 UTC, KraPete commented on test/modbus_test.cpp
> +    SerialPort->Close();
Да

2022-02-08 08:56 UTC, KraPete commented
> > Всё таки стоит сделать так, чтобы `write_address` в homeui только у modbus устройств был доступен для редактирования
> 
> А в какую сторону копать? Нужно менять код в [homeui](https://github.com/wirenboard/homeui) и в частности в json editor-е?

Нет. Это можно сделать схемой в wb-mqtt-serial

2022-02-09 14:44 UTC, rkochkin commented on test/modbus_test.cpp
> +    SerialPort->Close();
Сделал

2022-02-10 05:37 UTC, KraPete requested changes
Ты сделал для произвольного модбас устройства, надо ещё в коде генерации схемы по шаблону для модбас устройств это же добавить.

2022-02-10 05:37 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +        { "$ref": "#/definitions/compoundRegisterChannel" }
Ещё надо это сделать отдельно для модбаса

2022-02-10 13:26 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +        { "$ref": "#/definitions/compoundRegisterChannel" }
Сделал compoundRegisterChannel отдельно для modbus. Подсхема идентична compoundRegisterChannel

2022-02-10 13:30 UTC, KraPete commented
> Ты сделал для произвольного модбас устройства, надо ещё в коде генерации схемы по шаблону для модбас устройств это же добавить.

Они разные, т.к. у subreg в случае modbus появляется write_address

2022-02-11 07:46 UTC, rkochkin commented
> > Ты сделал для произвольного модбас устройства, надо ещё в коде генерации схемы по шаблону для модбас устройств это же добавить.
> 
> Они разные, т.к. у subreg в случае modbus появляется write_address

Да, понял. Добавил write_address для субрегистров.

2022-02-11 12:04 UTC, KraPete commented on test/TModbusIntegrationTest.Errors.dat
> +Publish: /devices/modbus-sample/controls/Holding U16 with write_address/meta/error: 'r' (QoS 1, retained)
Зачем это тут, если сделал отдельный тест?

2022-02-11 12:04 UTC, KraPete commented on test/TModbusIntegrationTest.MaxReadRegisters.dat
> +EnqueueHoldingReadU16ResponseWithWriteAddress()
И тут?

2022-02-11 12:05 UTC, KraPete commented on test/TModbusIntegrationTest.Poll.dat
> +EnqueueHoldingReadU16ResponseWithWriteAddress()
И тут?

2022-02-11 12:05 UTC, KraPete commented on test/TModbusIntegrationTest.Write.dat
> +EnqueueHoldingWriteU16ResponseWithWriteAddress()
И тут?

2022-02-11 12:05 UTC, KraPete commented on test/configs/config-modbus-test.json
> +                "name" : "Holding U16 with write_address",
Всё таки надо абсолютно отдельный тест.

2022-02-11 12:07 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +          "title": "bits",
Вот, кстати, вопрос: "А что будет, когда я укажу адрес 111:10:11?"

2022-02-11 12:08 UTC, KraPete commented on src/devices/modbus_device.h
> +                         "#/definitions/common_channel_modbus"),
Есть ещё modbus_io_device

2022-02-11 13:14 UTC, rkochkin commented on test/configs/config-modbus-test.json
> +                "name" : "Holding U16 with write_address",
Хорошо. Вычищу проверку write_address из интеграционных тестов и сделаю отдельную.

2022-02-11 13:15 UTC, rkochkin commented on src/devices/modbus_device.h
> +                         "#/definitions/common_channel_modbus"),
Для `modbus_io_device` тоже сделать `write_address`?

2022-02-11 13:25 UTC, rkochkin commented on test/TModbusIntegrationTest.Errors.dat
> +Publish: /devices/modbus-sample/controls/Holding U16 with write_address/meta/error: 'r' (QoS 1, retained)
Потому что сперва добавил проверку write_address в TModbusIntegrationTest,  и понеслось... массовое изменение логов и тестов.

2022-02-14 10:48 UTC, rkochkin commented on test/TModbusIntegrationTest.Errors.dat
> +Publish: /devices/modbus-sample/controls/Holding U16 with write_address/meta/error: 'r' (QoS 1, retained)
Убрал

2022-02-14 10:49 UTC, rkochkin commented on test/configs/config-modbus-test.json
> +                "name" : "Holding U16 with write_address",
Сделал

2022-02-15 08:20 UTC, rkochkin commented on src/devices/modbus_device.h
> +                         "#/definitions/common_channel_modbus"),
Для modbus_io устройств не надо делать отдельный write_addres из-за того что в этой опции пока нет необходимости.

2022-02-15 09:29 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +          "title": "bits",
Сейчас для этого случая используются настройки смещения и ширины из адреса для чтения.

2022-02-17 09:42 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +          "title": "bits",
Перенёс решение в перебазированную на новый мастер ветку: https://github.com/wirenboard/wb-mqtt-serial/pull/395

2022-02-17 09:44 UTC, rkochkin commented
Перебазировал в https://github.com/wirenboard/wb-mqtt-serial/pull/395

2022-02-17 09:44 UTC, closed without merging