Cityron PU-3 template correction
wirenboard/wb-mqtt-serial pull request #391
Opened 2022-02-08 14:47 UTC by ExplorerOL

2022-02-08 15:47 UTC, KraPete requested changes

2022-02-08 15:47 UTC, KraPete commented on debian/changelog
> +  * Cityron PU-3 template was corrected
Думаю, лучше написать, что конкретно изменили

2022-02-09 05:32 UTC, ExplorerOL commented on debian/changelog
> +  * Cityron PU-3 template was corrected
Сделал

2022-02-09 05:33 UTC, KraPete approved these changes

2022-02-09 05:52 UTC, merged