Scheduler more accurate maintains read period
wirenboard/wb-mqtt-serial pull request #403
Opened 2022-02-25 13:35 UTC by KraPete

2022-02-26 19:51 UTC, evgeny-boger commented
что-то какой-то огромный diff, тут точно всё правильно?

2022-02-28 05:38 UTC, KraPete commented
Long read

1. В первой реализации я не хотел сильно лезть в код тестов и сделал в цикле TSerialClient выборку из очереди планировщика, обработку, а уже потом перепланирование и помещение регистров обратно в очередь. К сожалению, это дало проблемы с соблюдением периода опроса, т.к. регистры не перепланировались во время.
Сейчас я сделал в цикле опрос только одного интервала регистров (т.е. последовательности, которую можно опросить за раз, не выезжая за отведённое время).
2. Это улучшило стабильность, но дало другую проблему. У нас несколько протоколов имеют внутренний кэш, который используется в цикле, чтобы не делать повторные запросы на уже полученные данные. Например, когда несколько наших регистров содержатся в одном ответе от устройства. Пришлось рефакторить этот код:
  - Надо собрать такие регистры в кучу и как-то дать понять, что их можно опросить вместе. К счастью, у них в адресе есть либо номер команды, либо адрес для устройства. К сожалению, прямо адрес регистра использовать нельзя, т.к. в него ещё и смещение или индекс упакованы. Пришлось для таких протоклов править код чтения регистров. Адрес выделяется из описания в шаблоне и помещается в адрес регистра, а всякие упакованные вещи идут в поля смещения и длины регистра. 
  - У TRegister BitOffset и BitWidth переименовал в DataOffset и DataWidth, т.к. в них теперь лежат данные, описанные выше.
  - Теперь регистры корректно сортируются в очерди планировщика по адресу, удобному для группировки.
  - Вместо operator< в IRegisterAddress добавил Compare, он аналогичен operator<=> из нового стандарта, им удобно сравнивать адреса.
  - Сделал класс интервала регистров, который смотрит в адрес и позволяет группировать регистры с одинаковым адресом. Он используется там, где нет специфики.
  - EndPollCycle переименовал в InvalidateReadCache и перенёс его вызов в конец чтения интервала.
  - Поправил код тестов, т.к. вместо одного вызова цикла чтения теперь их нужно делать несколько, чтобы прочитать все регистры.
3. Нашёл ещё одну особенность. Если до опорса высокоприоритетного регистра есть хоть чть чуть времени, хоть 1мс, то я начинаю опрос низкоприоритетного регистра. Это вызывает увеличение интервала опроса. Переделал код планировщика и выбора регистров. Теперь, если времени для опроса одного низкоприоритетеного регистра недостаточно, запускается ожидание следующего высокоприоритетного регистра.
4. Это не работает в ситуации, когда надо принудительно отдать шину низкоприоритетным регистрам. Поэтому добавил флаг о том, что регистр надо просить даже, если по времени это больше, чем есть до следующего высокоприоритетного.
5. Добавил передачу текущего времени в метод цикла опроса из вне. Это позволит сделать тесты без борьбы с нестабильными временами публикации и т.п.

2022-02-28 08:57 UTC, webconn requested changes

2022-02-28 08:57 UTC, webconn commented on src/poll_plan.h
>      void AccumulateNext(std::chrono::steady_clock::time_point time, TAccumulator& accumulator)
Тут бы тоже привести в порядок время, а то непонятно, что за time сюда входит

2022-02-28 08:57 UTC, webconn commented on src/poll_plan.h
> +                if (HighPriorityTime > 10 * MaxLowPriorityLag) { // Prevent overflow
Давай вынесем отсюда эту магическую константу и опишем, на что она влияет, если не получается от неё избавиться. Или это отладка?

2022-02-28 08:57 UTC, webconn commented on src/serial_client.cpp
> +std::chrono::steady_clock::time_point TSerialClient::WaitForPollAndFlush(
Как-то интуитивно мне не нравится эта идея перекладывать время туда-сюда, лучше уж блокирующий вызов убрать из начала цикла опроса, если мы хотим облегчить тестирование последнего

2022-02-28 08:57 UTC, webconn commented on src/serial_port_driver.h
> +    void Cycle(std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now());
Вот я про это к вопросу про `WaitForPollAndFlush`, не очень нравится это место. Либо делать что-то блокирующее в конце цикла, либо выносить за его пределы, либо просто внутри `Cycle` явно вызывать `now`

2022-02-28 08:57 UTC, webconn commented on src/serial_client.h
> +    void Cycle(std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now());
Я за то, чтобы добавить явный вызов `now` там, где он нужен

2022-02-28 08:57 UTC, webconn commented on src/serial_client.cpp
> +        // TODO: mark all ranges as read error
Это сложно?

2022-02-28 09:31 UTC, KraPete commented on src/serial_client.cpp
> +        // TODO: mark all ranges as read error
Не убрал. Оно уже не нужно

2022-02-28 10:56 UTC, KraPete commented on src/devices/lls_device.cpp
> +    uint8_t cmd = GetUint32RegisterAddress(reg->GetAddress());
Теперь это делается при парсинге адреса и в адресе лежит номер команды

2022-02-28 10:56 UTC, KraPete commented on src/poll_plan.h
> +#include <iostream>
Убрал

2022-02-28 12:48 UTC, KraPete commented on src/serial_port_driver.h
> +    void Cycle(std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now());
Вернул как было

2022-03-02 06:43 UTC, webconn commented on src/poll_plan.h
> +    /**
Тут вдруг пустой док-коммент появился, это запланировано было?

2022-03-02 06:43 UTC, webconn commented on src/poll_plan.h
> +    void AccumulateNext(std::chrono::steady_clock::time_point currentTime, TAccumulator& accumulator)
`currentTime` - это по смыслу `now`? Или время начала цикла опроса? Понятней не стало :(

2022-03-04 07:51 UTC, KraPete commented on src/poll_plan.h
> +    void AccumulateNext(std::chrono::steady_clock::time_point currentTime, TAccumulator& accumulator)
Добавил коментарии и пару методов перименовал

2022-03-04 07:56 UTC, webconn approved these changes

2022-03-04 10:32 UTC, closed without merging

2022-03-04 10:41 UTC, KraPete commented
Rebase https://github.com/wirenboard/wb-mqtt-serial/pull/408