Feature/46686 add separate address
wirenboard/wb-mqtt-serial pull request #417
Opened 2022-03-24 09:58 UTC by rkochkin

Добавил возможность указания адреса записи, без необходимости указывать адрес чтения. В этом случае канал переводится в режим write-only.

2022-03-25 04:07 UTC, KraPete requested changes

2022-03-25 04:07 UTC, KraPete commented on src/register.cpp
> +    if (WriteOnly) {
Кажется, что тут грабельки положили. 
1. Нет нигде упоминания о том, что GetAddress вернёт неожиданно не адрес для чтения, а адрес для записи.
2. Код, который читает регистры, радостно сделает запрос по этому адресу, вместо вменяемого сообщения об ошибке или вообще исключения регистра из опроса.

2022-03-25 04:07 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +          "pattern": "^(0x[A-Fa-f\\d]+|\\d+|)$",
Навреное, стоит с коллегами обсудить как это в UI должно выглядеть. И обязательно в схему, которая проверяет шаблоны добавить правила, проверяющие, что хоть один адрес задан.

2022-03-25 09:39 UTC, rkochkin commented on src/register.cpp
> +    if (WriteOnly) {
1. Согласен, что некрасиво. Но это минимальный способ без переделывания архитектуры добавить эту функциональность. Дёргание адреса чтения разбросано по всему коду. Можно отловить все вызовы и добавить условие по WriteOnly.
3. Если выставлен флаг WriteOnly регистр не добавляется в Sheduller и не опрашивается. Хотя да, при "ручном" считывание поведение не определено.

@KraPete как лучше поступить? Отловить все вызовы?

2022-03-25 11:05 UTC, KraPete commented on src/register.cpp
> +    if (WriteOnly) {
Думаю надо добавить условие по WriteOnly. Но вообще, да, я б переделал архитектуру так, чтоб в протоколы, которые не умеют в WriteAddress приходил объект класса без этого поля. Правда это такой хороший рефакторинг.

2022-04-04 10:34 UTC, rkochkin commented on src/register.cpp
> +    if (WriteOnly) {
Добавил условие по WriteOnly. Добавил исключение, если  происходит попытка обращения к адресу чтения для WriteOnly регистра.

2022-04-04 10:35 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +          "pattern": "^(0x[A-Fa-f\\d]+|\\d+|)$",
Сделал

2022-04-11 05:43 UTC, KraPete requested changes

2022-04-11 05:43 UTC, KraPete commented on src/serial_config.cpp
> +                else if ((registers[i]->AccessType == TRegisterConfig::EAccessType::READ_ONLY) !=
Тут стоит сравнивать AccessType, иначе сейчас можно в один канал объединить регистры которые можно читать и писать и те, которые можно только писать.

2022-04-13 11:43 UTC, rkochkin commented on src/serial_config.cpp
> +                else if ((registers[i]->AccessType == TRegisterConfig::EAccessType::READ_ONLY) !=
Исправил

2022-04-13 12:33 UTC, KraPete approved these changes

2022-04-13 13:30 UTC, merged