46378 Add array type for channel
wirenboard/wb-mqtt-serial pull request #424
Opened 2022-04-15 09:36 UTC by rkochkin

2022-05-27 08:22 UTC, KraPete commented on src/register_value.h
> +    explicit TRegisterValue(uint64_t value);
Зачем explicit? Из-за этого куча изменений в PR только для вызова конструктора.

2022-05-27 14:14 UTC, rkochkin commented on src/register_value.h
> +    explicit TRegisterValue(uint64_t value);
Хотелось избавится от неявных преобразований. Согласен, что это повлекло за собой много изменений кода в устройствах. @KraPete не повлечёт ли это какие либо нежелательные эффекты? 
В принципе можно убрать explicit и уменьшить количество изменений.

2022-05-30 05:12 UTC, KraPete commented on src/register_value.h
> +    explicit TRegisterValue(uint64_t value);
Думаю, что не повлечёт.

2022-05-30 08:03 UTC, rkochkin commented on src/register_value.h
> +    explicit TRegisterValue(uint64_t value);
Убрал explicit из конструктора

2022-05-31 12:23 UTC, webconn reviewed
Я запутался по поводу того, фиксирован ли у нас размер строки, а ещё не понял, для чего строка разворачивается в контейнере

2022-05-31 12:23 UTC, webconn commented on src/register_value.cpp
> +    auto max = std::max(Value.size(), other.Value.size());
Где-то нужна такая сложная проверка, чтобы с допустимым разным размером?

2022-06-03 07:08 UTC, rkochkin commented on src/register_handler.cpp
> +    TRegisterValue tempValue; // must be volatile
Потребности в volatile я тоже здесь не вижу. @KraPete можешь объяснить, пожалуйста, для чего был этот volatile?

2022-06-03 07:25 UTC, KraPete commented on src/register_handler.cpp
> +    TRegisterValue tempValue; // must be volatile
Внизу 2 участка закрытых мьютексом, между ними запись. Мне нужно было, чтобы компилятор не оптимизировал это место, тупо подставив `ValueToSet` в WriteRegister, а сделал реальное присвоение во временную переменную в первом участке с мьютексом.

2022-06-03 07:27 UTC, KraPete commented on src/register_handler.cpp
> +    TRegisterValue tempValue; // must be volatile
В соседне PR я это место переписал нафиг. Так что тут, может, и не сильно важно.

2022-06-03 07:36 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +        "string_data_size": {
Строка в контейнере фиксированная, просто вычитывается и записывается в неё определённое количество символов.

2022-06-03 07:41 UTC, rkochkin commented on src/modbus_common.cpp
> +                // TODO: Need to add data offset function to write array
Я думаю что не нужен, но нужно избавится от дублирования кода.
Создал задачу для этого:
https://wirenboard.bitrix24.ru/company/personal/user/204/tasks/task/view/49682/

2022-06-03 07:41 UTC, rkochkin commented on src/modbus_common.cpp
> +        // TODO Add offset
Убрал комментарий. Создал задачу:
https://wirenboard.bitrix24.ru/company/personal/user/204/tasks/task/view/49682/

2022-06-03 07:41 UTC, rkochkin commented on src/devices/uniel_device.cpp
> +    } else
Сделал

2022-06-03 07:41 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +          "title": "String Size",
Сделал

2022-06-07 11:14 UTC, rkochkin commented on src/register_value.h
> +typedef uint16_t TRegisterWord;
Поправил

2022-06-07 11:14 UTC, rkochkin commented on test/serial_client_test.cpp
> +    EXPECT_EQ('r', static_cast<char>(Device->Registers[27]));
Добавил

2022-06-07 17:20 UTC, webconn commented on src/modbus_common.cpp
> +        auto valueArray = value.Get<std::vector<TRegisterWord>>();
Надо это преобразовывать не в коде контейнера, а в коде протокола modbus. То есть, здесь вытаскиваем string, и преобразуем функцией, которая где-то здесь лежит

2022-06-07 17:20 UTC, webconn commented on src/modbus_common.cpp
> +                r |= TRegisterValue{mask & (data >> localBitOffset)} << bitsWritten;
Тут стоит сделать так: взять весь for как он был раньше, который обрабатывает значение (`for (auto reg: range.RegisterList()) {`), перенести его в метод в духе `ParseResponseUint64`, а тут сделать if, который для строки вызовет другой парсер, который будет сильно проще и не будет использовать битовые сдвиги

2022-06-07 17:20 UTC, webconn commented on src/register_value.h
> +    TRegisterValue operator>>(uint32_t offset) const;
От этих всех операций надо будет избавиться, пусть работают после каста в uint64

2022-06-07 17:20 UTC, webconn commented on src/register_value.h
> +    std::deque<uint8_t> Value;
Заменить на `union {uint64, string}` и приложить сюда `enum`, который говорит, что у нас сейчас в контейнере лежит.

По сути, у нас получится std::variant на минималках

2022-06-07 17:20 UTC, webconn commented on src/register_value.h
> +    std::deque<uint8_t> Value;
Строку можно сделать с зарезервированной памятью, например, на 16 байт

2022-06-10 00:10 UTC, rkochkin commented on src/modbus_common.cpp
> +                r |= TRegisterValue{mask & (data >> localBitOffset)} << bitsWritten;
Переделал

2022-06-10 00:10 UTC, rkochkin commented on src/modbus_common.cpp
> +        auto valueArray = value.Get<std::vector<TRegisterWord>>();
Сделал

2022-06-10 00:10 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +        "string_data_size": {
Убрал фиксированную ширину

2022-06-10 06:58 UTC, webconn commented on src/register_value.h
> +    std::string StringValue;
Так можно ж было сразу в union

2022-06-10 06:58 UTC, webconn commented on src/register_value.h
> +        Undefine,
Undefined
И нет никакого способа проверить, что тут сейчас лежит (метода, который смотрит наружу)

2022-06-10 06:58 UTC, webconn commented on src/register_value.cpp
> +    return StringValue;
Плохо, что мы тут и выше не кидаемся ничем, если значение на самом деле не того типа. Можем из-за этого однажды пропустить логическую ошибку

2022-06-10 06:58 UTC, webconn commented on src/modbus_common.cpp
> +                reg->SetValue(val);
Это же в одну строчку пишется через конструктор

2022-06-10 06:58 UTC, webconn commented on src/register.cpp
> +            return 32;
Тут ведь надо из RegisterFormat вернуть значение string size

2022-06-10 06:58 UTC, webconn commented on src/register.cpp
> +        LOG(Debug) << "new val for " << ToString() << ": " << std::hex << value.Get<uint64_t>();
А вот и место, где мы получаем логическую ошибку из-за того, что не проверяем, а что же в значении регистра

2022-06-10 06:58 UTC, webconn commented on src/register.cpp
> +    // TODO Modify
Кажется, этот TODO надо убирать, и ассертиться, если в значении приехала строка

2022-06-10 06:58 UTC, webconn commented on src/serial_config.cpp
> +        res.BitWidth = GetInt(register_data, "string_data_size") * 16;
Всё ещё актуально. Мы где-то тут не можем вытащить типичный размер регистра для выбранного протокола? Для переносимости я бы тут умножал на `sizeof(char)`, а в модбасе домножал на два, потому что иначе потом в других протоколах голову можно будет сломать

2022-06-10 06:58 UTC, webconn commented on test/serial_client_test.cpp
> +    Device->Registers[32] = '!';
Тут бы тоже нуль-терминацию добавить, она тут становится неявной (мы расчитываем, что в регистрах при инициализации будут нули)

2022-06-10 06:58 UTC, webconn commented on wb-mqtt-serial.schema.json
> +      "String Size": "Размер строки"
В оригинальной строчке "size" с маленьеой буквы

2022-06-10 07:35 UTC, rkochkin commented on src/register_value.cpp
> +    return StringValue;
Может генерить исключения?

2022-06-10 07:35 UTC, webconn commented on src/register_value.cpp
> +    return StringValue;
Ну да

2022-06-10 08:09 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +      "String Size": "Размер строки"
Поправил

2022-06-10 08:09 UTC, rkochkin commented on src/modbus_common.cpp
> +                reg->SetValue(val);
Поправил

2022-06-10 08:09 UTC, rkochkin commented on src/register_value.h
> +        Undefine,
Поправил, добавил геттер типа

2022-06-10 08:31 UTC, webconn commented on src/register_value.h
> +    std::string StringValue;
Решили пока не делать, сделаем, если будут проблемы с памятью

2022-06-14 08:36 UTC, rkochkin commented on src/register_value.cpp
> +    return StringValue;
Сделал генерацию исключений, если считываемый тип не совпадает

2022-06-14 08:37 UTC, rkochkin commented on src/register.cpp
> +        LOG(Debug) << "new val for " << ToString() << ": " << std::hex << value.Get<uint64_t>();
Поправил.

2022-06-14 09:02 UTC, rkochkin commented on src/register.cpp
> +            return 32;
Здесь задаётся некоторое значение по умолчанию если String Size не задан. Дальше по коду проверяется, установлен ли параметр BitWidth (вычисляется из String Size), и, если он не задан, вызывается RegisterFormatByteWidth().
Я бы вообще сколько данных считывать вычислял бы где нибудь в конструкторе и хранил в закрытом члене класса, а не каждый раз вычислял бы из формата.

2022-06-14 09:04 UTC, rkochkin commented on test/serial_client_test.cpp
> +    Device->Registers[32] = '!';
Зачем здесь нужна нуль терминация, если мы считываем заранее заданное количество байт?

2022-06-14 09:51 UTC, rkochkin commented
> Всё ещё актуально. Мы где-то тут не можем вытащить типичный размер регистра для выбранного протокола? Для переносимости я бы тут умножал на sizeof(char), а в модбасе домножал на два, потому что иначе потом в других протоколах голову можно будет сломать

Домножение на два в модбасе очень странное и не очевидное решение. BitWidth должно быть результирующей низкоуровневой длиной, которая просто считывается/записывается с использованием протокола. Я добавил, по сути, костыль со StringSize, а тут получится ещё и двойной костыль.

2022-06-14 09:53 UTC, rkochkin commented
> Кажется, этот TODO надо убирать, и ассертиться, если в значении приехала строка

Убрал

2022-06-14 21:10 UTC, webconn commented
> > Всё ещё актуально. Мы где-то тут не можем вытащить типичный размер регистра для выбранного протокола? Для переносимости я бы тут умножал на sizeof(char), а в модбасе домножал на два, потому что иначе потом в других протоколах голову можно будет сломать
> 
> Домножение на два в модбасе очень странное и не очевидное решение. BitWidth должно быть результирующей низкоуровневой длиной, которая просто считывается/записывается с использованием протокола. Я добавил, по сути, костыль со StringSize, а тут получится ещё и двойной костыль.

@KraPete можешь добавить своё мнение по этому поводу и вообще PR посмотреть? Кажется, раскостылили тут всё, что могли, но это место меня всё равно смущает

2022-06-14 21:11 UTC, webconn approved these changes
Кажется, нормально, хочу мнение Петра ещё услышать и давайте уже это закроем

2022-06-14 21:11 UTC, webconn commented on src/register.cpp
> +            return 32;
Опять же, если StringSize не задан, нам бы с исключением упасть, а то это поведение совсем неожиданное

2022-06-17 07:52 UTC, rkochkin commented
> Опять же, если StringSize не задан, нам бы с исключением упасть, а то это поведение совсем неожиданное

Сделал выброс исключения если не задан размер строки

2022-06-17 08:00 UTC, KraPete commented on src/modbus_common.cpp
> +            // Added workaround for data offset on write
Тут бы написать в чём заключается это workaround, и зачем он вообще нужен.
Если честно, я вообще не понял, что тут такое происходит, и почему столько кода в функции появилось :(

2022-06-17 08:12 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +                          "8-bit ASCII char", "String"]
@KraPete в каком месте это нужно описать? В "enum_titles"?

2022-06-17 08:15 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +          "title": "String size",
ASCII/UTF8/UTF16/UTF32?

2022-06-17 08:16 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +                          "8-bit ASCII char", "String"]
Да

2022-06-17 10:40 UTC, rkochkin commented on src/register.cpp
> +        std::stringstream ss;
Оставил как было в старой логике. Быстро не нашёл, как понять в этом месте, что включён Debug. И это, думаю, выходит за рамки данной задачи.

2022-06-17 10:40 UTC, rkochkin commented on src/modbus_common.cpp
> +                          << item->HumanReadableValue << " (0x" << std::hex << item->RawValue.Get<uint64_t>() << ")";
Поправил

2022-06-17 10:40 UTC, rkochkin commented on src/register_value.cpp
> +#include <vector>
Поправил

2022-06-17 10:41 UTC, rkochkin commented on test/serial_config_test.cpp
> +                                Emit() << "UnsupportedValue: " << reg->UnsupportedValue->Get<uint64_t>();
Поправил

2022-06-17 10:41 UTC, rkochkin commented on test/serial_config_test.cpp
> +                                Emit() << "ErrorValue: " << reg->ErrorValue->Get<uint64_t>();
Поправил

2022-06-17 10:49 UTC, rkochkin commented on src/serial_device.cpp
> +                  << setup_item->HumanReadableValue << " (0x" << std::hex << setup_item->RawValue.Get<uint64_t>()
Поправил

2022-06-17 10:50 UTC, rkochkin commented on test/serial_config_test.cpp
> +                               << setup_item->GetRawValue().Get<uint64_t>();
Строки поддерживаем. Поправил.

2022-06-17 10:50 UTC, rkochkin commented on test/channel_value_test.cpp
> +class RegisterValueTest: public ::testing::Test
Убрал

2022-06-17 10:59 UTC, KraPete commented on src/register.cpp
> +        std::stringstream ss;
::Debug.IsEnabled()

2022-06-17 11:55 UTC, webconn commented on src/register.cpp
> +    if ((reg.WordOrder == EWordOrder::BigEndian) || (reg.Format == RegisterFormat::String)) {
Так endianess - это про числа же. Прямо сейчас сделаем строки, которые как-то из modbus читаются по символу на регистр, и думаю, ладно

2022-06-17 11:58 UTC, webconn commented on wb-mqtt-serial.schema.json
> +          "title": "String size",
Так неважно ведь. Но про то, что тут в символах, дописать стоит

2022-06-17 12:00 UTC, webconn commented on src/register.cpp
> +            return 0;
Дописать бы тут, что размер будет потом взят из конфига

2022-06-17 12:01 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +          "title": "String size",
Важно же. Размер в байтиках откуда потом получать? Захочется это прикрутить к другому протоколу и новый тип городить?

2022-06-17 12:03 UTC, webconn commented on wb-mqtt-serial.schema.json
> +          "title": "String size",
Ну научимся читать замысловатым образом - доделаем. А то непонятно, поменяли протокол, и вдруг строка о 8 символах должна стать длиной 16. Мы это внутри можем сделать, не взрывая мозг пользователю

2022-06-17 12:04 UTC, webconn commented on wb-mqtt-serial.schema.json
> +          "title": "String size",
А в общем случае для utf-8 строки ты вообще не можешь сказать, сколько байт ожидать, если реальных символов определённое количество

2022-06-17 12:05 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +          "title": "String size",
Ну я ж не зря спросил ;)

2022-06-17 12:06 UTC, webconn commented on wb-mqtt-serial.schema.json
> +          "title": "String size",
Короче, давай пока символы считать

2022-06-17 12:07 UTC, KraPete commented on src/register.cpp
> +    if ((reg.WordOrder == EWordOrder::BigEndian) || (reg.Format == RegisterFormat::String)) {
Ну ок

2022-06-17 12:23 UTC, KraPete requested changes

2022-06-17 12:23 UTC, KraPete commented on test/serial_config_test.cpp
> +                                if (reg->ErrorValue->GetType() == TRegisterValue::ValueType::String) {
Давай оператор перегрузим? Чё-то куча копипасты

2022-06-17 12:23 UTC, KraPete commented on src/serial_config.cpp
> +            throw TConfigParserException("String size not set for register string format");
is not set

2022-06-17 12:23 UTC, KraPete commented on src/register.cpp
> +        std::stringstream ss;
Тут один if. Думаю, надо сделать

2022-06-20 10:23 UTC, rkochkin commented on src/register.cpp
> +        std::stringstream ss;
Сделал

2022-06-20 10:34 UTC, rkochkin commented on src/modbus_common.cpp
> +            // Added workaround for data offset on write
Я параметр IsPacking(reg) вынес за пределы цикла. Мне не очень понятно зачем его каждый раз внутри цикла нужно было считывать, к тому же старый код было сложно модифицировать.
Workaround мы обсуждали с @webconn . Договорились, что для записи и чтения строк будет пока своя процедура без сдвигов. Для числовых значений оставлен пока старый магический код.

2022-06-20 11:12 UTC, rkochkin commented on src/register.cpp
> +            return 32;
Сделал

2022-06-20 11:17 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +                          "8-bit ASCII char", "String"]
Для канала вообще Строка это просто строка не имеющая особенностей. Уже для определённого протокола она приобретает какой-то формат 1 символ на 16 разрядный регистр или 2 символа на регистр и тому подобное.
Если здесь явно указывать что означает Строка для каждого протокола, боюсь нам не хватит места отобразить всё это во всплывающем меню.

2022-06-21 11:45 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +        "string_data_size": {
Сделано

2022-06-21 11:48 UTC, webconn commented on wb-mqtt-serial.schema.json
> +                          "8-bit ASCII char", "String"]
Думаю, как description к string_size можно было бы добавить, что сейчас имеются в виду строки вполне определённого вида

2022-06-21 12:00 UTC, webconn reviewed
Только примечание ещё в форму про строки добавить, и думаю, ок. Можешь ещё сюда приложить скриншоты того, что получилось?

2022-06-21 12:00 UTC, webconn commented on src/register.cpp
> +            return 32; // The size will then be taken from the config parameter
Вот это снова откатилось, видимо. Не надо, чтобы это встречалось где-то, лучше пусть ноль вернётся

2022-06-21 16:45 UTC, rkochkin commented on src/register.cpp
> +            return 32; // The size will then be taken from the config parameter
Сделал нулём. Переделал тесты немного.

2022-06-21 16:52 UTC, rkochkin commented
Настройка канала, если выбран формат "Строка":
![Screenshot_20220621_194605](https://user-images.githubusercontent.com/12100943/174854283-897787d8-808b-4646-8111-5063f36d803d.png)

Настройка канала, если выбран формат отличный от формата "Строка":
![Screenshot_20220621_194920](https://user-images.githubusercontent.com/12100943/174854734-ca35b541-f18a-4dce-a062-d24191703f2e.png)

Отображение строки во вкладке "Устройства":
![Screenshot_20220621_195055](https://user-images.githubusercontent.com/12100943/174855183-69763997-c7cd-485c-b011-11ca5701cbb7.png)

2022-06-21 16:52 UTC, rkochkin commented on src/register.cpp
> +            return 0;
Сделал

2022-06-22 05:15 UTC, KraPete requested changes
Забыл. В Readme.md надо написать про новые параметры.

2022-06-22 05:15 UTC, KraPete commented on src/serial_config.cpp
> +            throw TConfigParserException("String size is not set for register string format");
Надо задачу сделать, чтобы здесь больше данных было о месте возникновения ошибки. Искать его в гигантском конфиге сложно.

2022-06-22 05:15 UTC, KraPete commented on src/serial_config.cpp
> +        res.BitWidth = GetInt(register_data, "string_data_size") * sizeof(char) * 8;
Почему оно умноженное на 8? А потом, при использовании, делённое на 8?
Почему не просто `*sizeof(char)`?

2022-06-22 05:15 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +          "description": "For the modbus protocol, strings are read one character per register from the low byte. The parameter specifies the number of characters",
Можно было здесь написать "string_data_size_description" и добавить конкретный текст как перевод для него в `en` и `ru`

2022-06-22 05:45 UTC, rkochkin commented on src/serial_config.cpp
> +        res.BitWidth = GetInt(register_data, "string_data_size") * sizeof(char) * 8;
Не хотелось сильно уродовать. Битовая длина ведь должна быть в битах?

2022-06-22 05:46 UTC, rkochkin commented on src/modbus_common.cpp
> +    inline uint32_t GetModbusDataWidthInWords(const TRegister& reg)
Да. 16 бит

2022-06-22 05:51 UTC, KraPete commented on src/serial_config.cpp
> +        res.BitWidth = GetInt(register_data, "string_data_size") * sizeof(char) * 8;
А! Тьфу. Да

2022-06-22 05:52 UTC, KraPete commented on src/modbus_common.cpp
> +    inline uint32_t GetModbusDataWidthInWords(const TRegister& reg)
Напиши в комментарии, пожалуйста.

2022-06-22 06:14 UTC, rkochkin commented on wb-mqtt-serial.schema.json
> +          "description": "For the modbus protocol, strings are read one character per register from the low byte. The parameter specifies the number of characters",
Поправил

2022-06-22 06:15 UTC, rkochkin commented on src/modbus_common.cpp
> +    inline uint32_t GetModbusDataWidthInWords(const TRegister& reg)
Переименовал, чтобы было понятнее.

2022-06-22 07:03 UTC, rkochkin commented on src/serial_config.cpp
> +            throw TConfigParserException("String size is not set for register string format");
Сделал отображение канала и устройства в сообщении исключения.

2022-06-22 07:21 UTC, rkochkin commented
> Забыл. В Readme.md надо написать про новые параметры.

Описал новые параметры в Readme.md

2022-06-22 08:29 UTC, merged