WB-MRGBW-D jinja template
wirenboard/wb-mqtt-serial pull request #454
Opened 2022-06-08 08:01 UTC by ExplorerOL

2022-06-20 18:35 UTC, wb-adegtyarev commented
Скачал пакет, поставил, шаблон отрисовывается корректно, но в устройство не записываются параметры.

Попробовал использовать файл шаблона на последней версии драйвера 2.61.7 — результат аналогичный.

2022-06-21 11:27 UTC, wb-adegtyarev approved these changes
Хороший шаблон получился. Надо избавиться от висячей запятой, учесть зависимость от сборки, которая чинит отправку параметров и можно вливать.

2022-06-21 11:27 UTC, wb-adegtyarev commented on template-templates/config-wb-mrgbw-d-fw3.json.jinja
> +            },
Тут надо подумать, как убрать висячую запятую, так как в стандарте такое нельзя. Наш сериал проглатывает, но у Спрута возникла проблема — валидатор валится. Ну и хотелось бы, чтобы стандарт соблюдался, мало ли…

![изображение](https://user-images.githubusercontent.com/77433258/174788370-bdf6f386-9bf6-4749-ac4b-788fc9c3d631.png)

2022-07-01 12:50 UTC, webconn requested changes

2022-07-01 12:50 UTC, webconn commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3-deprecated.json
> -                "WB-MRGBW-D_template_title": "WB-MRGBW-D fw3 (4-channel CV LED Dimmer)",
У нас теперь на deprecated шаблоны примечание автоматически дописывается, можно не менять

2022-07-01 12:50 UTC, webconn commented on template-templates/config-wb-mrgbw-d-fw3.json.jinja
> +                "off_ch1_act_title": "Disable channel 1 (B)",
Вот эта вся штука тоже в шаблонизаторный `for` хорошо заворачивается

2022-07-01 12:50 UTC, webconn commented on template-templates/config-wb-mrgbw-d-fw3.json.jinja
> +                "no_act_title": "Нет действия",
Аналогично, можно в 4 раза меньше текста получить

2022-07-01 12:50 UTC, webconn commented on template-templates/config-wb-mrgbw-d-fw3.json.jinja
> +            },
А они шаблонизатором сначала не прогоняют?

2022-07-01 14:33 UTC, ExplorerOL commented on template-templates/config-wb-mrgbw-d-fw3.json.jinja
> +            },
Я это исправил

2022-07-01 14:38 UTC, ExplorerOL commented on template-templates/config-wb-mrgbw-d-fw3.json.jinja
> +                "off_ch1_act_title": "Disable channel 1 (B)",
Можно сделать, но придется ifы добавлять, так как меняются буквы и цифры. Решил, что оптимизацию лучше делать уже в шаблоне WB-LED, там букв в названиях не будет. А тут уже все переводы были готовы.

2022-07-01 14:49 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-mrgbw-d-fw3-deprecated.json
> -                "WB-MRGBW-D_template_title": "WB-MRGBW-D fw3 (4-channel CV LED Dimmer)",
Тогда предлагаю оставить только "WB-MRGBW-D fw3" иначе с добавлением title будет очень длинным

2022-07-01 14:57 UTC, webconn commented on template-templates/config-wb-mrgbw-d-fw3.json.jinja
> +                "off_ch1_act_title": "Disable channel 1 (B)",
Вот стеснялся совращать, а в итоге решился ))

Смотри, как можно

```jinja2
//где-то в начале
{% set CHANNELS = ((1, "R"), (2, "G"), (3, "B"), (4, "W")) %}
...

// там, где надо и буквы, и цифры
{% for number, name in CHANNELS  %}
    "off_ch{{number}}_act_title": "Disable channel {{number}} ({{name}})",
{%- endfor %}
```

2022-07-01 17:54 UTC, wb-adegtyarev commented on template-templates/config-wb-mrgbw-d-fw3.json.jinja
> +            },
> А они шаблонизатором сначала не прогоняют?

Ну они берут наш готовый шаблон, который лежит в пакете serial и используют. И вот там была висячая запятая.

2022-07-04 07:27 UTC, ExplorerOL commented on template-templates/config-wb-mrgbw-d-fw3.json.jinja
> +                "off_ch1_act_title": "Disable channel 1 (B)",
Спасибо! Переделал.

2022-07-04 09:37 UTC, webconn commented on template-templates/config-wb-mrgbw-d-fw3.json.jinja
> +            {% for out_num in range(1, OUTPUTS_NUMBER + 1) -%}
Вот тут можно тоже на CHANNELS переделать

2022-07-04 11:49 UTC, webconn approved these changes

2022-07-04 12:22 UTC, merged