Add template T13 VFD
wirenboard/wb-mqtt-serial pull request #455
Opened 2022-06-09 16:29 UTC by brainroot

Добавил шаблон китайского частотника
Задача отсюда: https://wirenboard.bitrix24.ru/workgroups/group/14/tasks/task/view/49190/
для https://wirenboard.com/wiki/T13-400W-12-H#%D0%92%D1%8B%D0%B1%D0%BE%D1%80_%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B0

2022-06-22 05:58 UTC, wb-adegtyarev requested changes
Надо секцию translations привести в порядок: убрать остатки от другого устройства и добавить перевод параметров частотника.

2022-06-22 05:58 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-t13-frequency.json
> +            }
В секции translations левые строчки и нет перевода для параметров частотника.

2022-07-06 13:51 UTC, brainroot commented on wb-mqtt-serial-templates/config-t13-frequency.json
> +            }
Поправил, у меня сюда старая негодная версия залилась.

2022-07-08 06:47 UTC, wb-adegtyarev requested changes

2022-07-08 06:47 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-t13-frequency.json
> +                "t13_frequency_title": "Преобразователь частоты T13",
Давай тут напишем так:
T13-400W-12-H, T13-750W-12-H

2022-07-08 06:47 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-t13-frequency.json
> +    "device_type": "t13_freq",
Там Пётр [внедряет группы](https://github.com/wirenboard/wb-mqtt-serial/pull/466) и сказал, что в новом шаблоне лучше сразу указать, надо вставить сюда строку:
`"group": "motor-control",`

2022-07-08 06:47 UTC, wb-adegtyarev commented on wb-mqtt-serial-templates/config-t13-frequency.json
> +                "t13_frequency_title": "T13 frequency converter",
Давай тут напишем так:
T13-400W-12-H, T13-750W-12-H

2022-08-08 09:35 UTC, wb-adegtyarev approved these changes

2022-08-29 19:26 UTC, merged