Device templates are organized in groups in web config editor
wirenboard/wb-mqtt-serial pull request #466
Opened 2022-07-05 10:22 UTC by KraPete

https://github.com/wirenboard/homeui/pull/339

Добавил группировку для типов устройств. Группы взял из https://wirenboard.com/wiki/Supported_devices

2022-07-07 18:30 UTC, webconn requested changes

2022-07-07 18:30 UTC, webconn commented on wb-mqtt-serial.schema.json
> +      "conditioner": "Conditioner equipment",
`Air conditioning`/`air-conditioning` или `ac`, к тому же так будет единобразно рядом с `ventilation` и `refrigeration`

2022-07-07 18:30 UTC, webconn commented on wb-mqtt-serial-templates/config-wbio-ai-dv-12-20ma.json
> +    "device_type": "WBIO-AI-DV-12-20ma",
Интересно, почему гитхаб тут видит изменение

2022-07-08 05:22 UTC, KraPete commented on wb-mqtt-serial-templates/config-wbio-ai-dv-12-20ma.json
> +    "device_type": "WBIO-AI-DV-12-20ma",
Пробел в конце строки был

2022-07-08 05:22 UTC, KraPete commented on wb-mqtt-serial-templates/config-wbio-ai-dv-12-50V.json
> +    "device_type": "WBIO-AI-DV-12-50V",
Пробел в конце строки был

2022-07-08 05:22 UTC, KraPete commented on wb-mqtt-serial-templates/config-wbio-ai-dv-12.json
> +    "device_type": "WBIO-AI-DV-12",
Пробел в конце строки был

2022-07-08 05:23 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +      "wb": "Wiren Board devices",
Это странно выглядит в шаблоне:
```
"group": "group-wb"
```

2022-07-08 05:27 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +      "wb": "Wiren Board devices",
Пусть хоть `g-wb` будет?

2022-07-08 05:30 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +      "conditioner": "Conditioner equipment",
Переименовал

2022-07-08 05:30 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +      "climate": "Climate sensors",
сделал `climate-sensor`

2022-07-08 10:42 UTC, webconn commented on wb-mqtt-serial-templates/config-wbio-ai-dv-12-20ma.json
> +    "device_type": "WBIO-AI-DV-12-20ma",
Странно, обычно гитхаб это подсвечивает, но видимо, не сейчас

2022-07-08 10:42 UTC, webconn commented on wb-mqtt-serial.schema.json
> +      "wb": "Wiren Board devices",
Можно и так

2022-07-08 10:43 UTC, webconn requested changes

2022-07-08 10:43 UTC, webconn commented on wb-mqtt-serial.schema.json
> +      "air-conditioning": "Ait conditioning equipment",
`Air`, а не `Ait` :)

2022-07-08 12:40 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +      "wb": "Wiren Board devices",
Переделал

2022-07-08 12:56 UTC, webconn approved these changes

2022-07-08 14:15 UTC, ExplorerOL commented on wb-mqtt-serial.schema.json
> +      "g-ventilation": "Ventilation equipment",
Предлагаю такой перевод Climate control equipment

2022-07-08 14:19 UTC, ExplorerOL requested changes

2022-07-08 14:19 UTC, ExplorerOL commented on wb-mqtt-serial.schema.json
> +      "g-ventilation": "Ventilation equipment",
Предлагаю такой перевод Climate control equipment и название группы

2022-07-11 05:10 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +      "g-ventilation": "Ventilation equipment",
Поменял

2022-07-11 08:01 UTC, ExplorerOL approved these changes

2022-07-11 10:39 UTC, merged