Add RPC functionality
wirenboard/wb-mqtt-serial pull request #470
Opened 2022-07-08 15:25 UTC by ekateluv

1. Конфигурация RPC
При старте в процедуре LoadConfig, во вложенной процедуре LoadPort, а далее в DefaultPortFactory вызываются процедуры по созданию структуры PPort. В них вычитываются все строковые параметры из файла с настройками, создается структура порта, и все это передается в функцию rpc AddPort. Таким образом мы добавлям порты и их данные.
Для того, чтобы отправлять запросы в порт, недостаточно иметь только указатель PPort, нам нужны структуры типа PSerialPortDriver, чтобы мы могли встроиться в процедуру опроса. Когда создается SerialDriver, мы получаем из него соответствие экземпляров PPort и PSerialPortDriver. После этого мы все это соединяем вместе, как результат rpc может знать к какому PSerialPortDriver обращаться, ориентируясь на тип порта и его данные (путь, ip, номер порта).
2. Порядок обработки запроса
Когда поступает запрос, срабатывает функция LoadPort. Имея при себе данные, полученные после конфигурации, он может узнать, к какому PSerialDriver нужно обратиться. После этого посылается структура с запросом в класс TSerialClient. В этот момент поток rpc блокируется, давая сигнал потоку SerialClient, который при первой же проверке обнаружит сигнал и перейдет в процедуру выполнения rpc запроса. После его выполнения потоком serial client будет послан сигнал потоку rpc, который выйдет из состояния блокировки и вернет результат выполнения запроса. 
Блокировка потока rpc осуществляется с таймаутом. 
Для того, чтобы не нарушать порядок опроса, перед выполнением rpc запроса происходит закрытие сессии с текущим устройством, которое опрашивалось в предудыщий цикл работы.

В некоторых местах выделение памяти для объектов поменяла с new на std::make_shared. Без этого начинались утечки памяти (вылетало с segmentation fault). 

Пока выкладываю без тестов. В прошлый раз они не очень хорошо собрались, потому что пришлось запустить ручки в процедуры LoadConfig и LoadPort, в результате не смогли выполниться тесты в .dat  файлах. Когда утвердим основной код, займусь тестами.

2022-07-11 06:50 UTC, KraPete requested changes

2022-07-11 06:50 UTC, KraPete commented on src/binary_semaphore.h
> +class TBinarySemaphoreSignal
Я уже писал раньше. Мне однозначно не нравится это решение.
Используй очередь с разными типами сообщений (rpc и запрос на установку регистра) и список обработчиков, которые будут разгребать эту очередь.

2022-07-11 06:50 UTC, KraPete commented on src/main.cpp
> +        rpcHandler->SerialDriverInitialize(serialDriver);
Почему нельзя здесь создать TRPCHandler и в конструкторе проинициализировать? Зачем 3 метода инициализации?

2022-07-11 06:50 UTC, KraPete commented on src/rpc_handler.cpp
> +    std::tuple<PRPCRequest, TRPCPortMode, std::string, std::string, int> ParseOptions(const Json::Value& Request)
Не надо делать tuple на 5 параметров. Используй структуру.

2022-07-11 06:50 UTC, KraPete commented on src/rpc_handler.cpp
> +        PRPCRequest RPCRequest = std::make_shared<TRPCRequest>();
Тут лапша из валидации JSON. Сделай схему и валидируй через схему.

2022-07-11 06:50 UTC, KraPete commented on src/rpc_handler.cpp
> +        int PortNumber;
Зачем int?

2022-07-11 06:50 UTC, KraPete commented on src/rpc_handler.cpp
> +    std::string PortLoadResponseFormat(const std::vector<uint8_t>& response, std::string format)
`const std::string& format` ?

2022-07-11 06:50 UTC, KraPete commented on src/rpc_request.h
> +    std::string Format;
Зачем Format строкой? И без комментариев, а в коде куча мест, где оно сравнивается с какими-то фиксированными строками. Не надо так ...

2022-07-11 06:50 UTC, KraPete commented on src/rpc_handler.h
> +    TRPCException(const std::string& message, RPCPortHandlerResult resultCode)
Сможешь объяснить, зачем все реализации методов и конструктора оказались в заголовочном файле? ;)

2022-07-11 06:50 UTC, KraPete commented on src/rpc_handler.cpp
> +    } catch (TRPCException& e) {
У нас убогая документация. RPC внутри библиотеки умеет обрабатывать исключения и делает спец структуру ответа с ошибкой. Так что можешь пользоваться этим
```cpp
                try {
                    reply["result"] = handler(params);
                } catch (const TRequestTimeoutException & ex) {
                    reply["error"] = Json::Value();
                    reply["error"]["message"] = "Request timeout";
                    reply["error"]["code"] = E_RPC_REQUEST_TIMEOUT;
                    reply["error"]["data"] = ex.what();
                } catch (const std::exception & ex) {
                    reply["error"] = Json::Value();
                    reply["error"]["message"] = "Server error";
                    reply["error"]["code"] = E_RPC_SERVER_ERROR;
                    reply["error"]["data"] = ex.what();
                }
```

2022-07-11 06:50 UTC, KraPete commented on src/rpc_port.h
> +    enum TRPCPortMode Mode;
Мне не нравится это место. Лучше сделать иерархию классов. Перебор по `enum` фигово расширяется

2022-07-11 06:50 UTC, KraPete commented on src/rpc_request_handler.cpp
> +std::vector<uint8_t> TRPCRequestHandler::RPCTransceive(PRPCRequest Request,
Тут и в методе ниже какая-то каша с IPC.
Семафор из вне, какой-то мьютекс, который непонятно что защищает.

Ещё раз предлагаю сделать очередь.
Тогда ты спокойно кладёшь в неё объект с запросом и `conditional_variable`, ждёшь `cv`.

2022-07-11 06:50 UTC, KraPete commented on src/rpc_request_handler.cpp
> +    if (State == RPCRequestState::RPC_WRITE) {
Вообще не понял зачем State нужен. К тому же из-за него приходится тащить объект TRPCRequestHandler в цикл обработки порта. В третий раз предлагаю сделать очередь с обработчиками, это всё сразу уезжает отсюда.

2022-07-11 06:50 UTC, KraPete commented on src/serial_client.cpp
> +    bool continue_signal_handling;
А теперь добавим ещё 3 типа сигналов ...

2022-07-11 06:50 UTC, KraPete commented on src/serial_driver.cpp
> +    Json::Value result(Json::arrayValue);
Можно не переименовывать?

2022-07-11 06:50 UTC, KraPete commented on src/serial_port_driver.cpp
> +    SerialClient = std::make_shared<TSerialClient>(Config->Devices, Config->Port, Config->OpenCloseSettings, metrics);
Сможешь объяснить в чём разница?

2022-07-13 12:41 UTC, ekateluv commented on src/rpc_handler.h
> +    RPC_WRONG_RESP_LNGTH = -5
Поправила

2022-07-13 12:42 UTC, ekateluv commented on src/rpc_handler.cpp
> +        int PortNumber;
Исправила на uint16_t

2022-07-13 12:47 UTC, ekateluv commented on src/serial_port_driver.cpp
> +    SerialClient = std::make_shared<TSerialClient>(Config->Devices, Config->Port, Config->OpenCloseSettings, metrics);
При использовании new в какие то моменты начал возникать segmentation fault на этом месте, хотя все объекты были выделены в памяти. Вобще, как я поняла, рекомендуется использовать умные указатели вместо new. Поменяла - работает

2022-07-13 12:50 UTC, ekateluv commented on src/serial_driver.cpp
> +    Json::Value result(Json::arrayValue);
Можно, но а почему нет? Все равно метод пришлось немного изменять, показалось так лучше выглядит

2022-07-13 17:39 UTC, KraPete commented on src/serial_port_driver.cpp
> +    SerialClient = std::make_shared<TSerialClient>(Config->Devices, Config->Port, Config->OpenCloseSettings, metrics);
1. PSerialClient - это и так std::shared_ptr. Т.е. исходный вариант и твой абсолютно идентичны.
2. Сегфолт надо было бы отдебажить. Если ты только поменяла на make_shared, и всё заработало, то баг остался, просто где-то времена съехали, и ты его проявлений теперь не видищь. Значит, оно выстрелит где-то потом у клиентов.

2022-07-13 19:34 UTC, webconn commented on src/serial_driver.cpp
> +    Json::Value result(Json::arrayValue);
Я всё ещё считаю, что лучше разделять такие изменения, да :)
И по-моему каждый раз отношусь к этому снисходительно. Но ничего, однажды допишем это в гайдлайн и будем кошмарить

2022-07-18 07:07 UTC, ekateluv commented on src/binary_semaphore.h
> +class TBinarySemaphoreSignal
Убрала TBinarySemaphore, заменила на TQueue

2022-07-18 07:07 UTC, ekateluv commented on src/main.cpp
> +        rpcHandler->SerialDriverInitialize(serialDriver);
Можно, сделала

2022-07-18 07:09 UTC, ekateluv commented on src/rpc_handler.cpp
> +    std::tuple<PRPCRequest, TRPCPortMode, std::string, std::string, int> ParseOptions(const Json::Value& Request)
Сделала структуру TRPCOptions, которая заменяет tuple в данном месте

2022-07-18 07:09 UTC, ekateluv commented on src/rpc_handler.cpp
> +        PRPCRequest RPCRequest = std::make_shared<TRPCRequest>();
Схему написала

2022-07-18 07:14 UTC, ekateluv commented on src/rpc_request.h
> +    std::string Format;
Изменила на enum

2022-07-18 07:26 UTC, ekateluv commented on src/rpc_handler.h
> +    TRPCException(const std::string& message, RPCPortHandlerResult resultCode)
TBinarySemaphore тоже весь был в заголовочнике...Делать отдельныe .cpp .h?

2022-07-18 07:26 UTC, ekateluv commented on src/rpc_port.h
> +    enum TRPCPortMode Mode;
сделала иерархию классов рпс-порта

2022-07-18 07:27 UTC, ekateluv commented on src/rpc_request_handler.cpp
> +std::vector<uint8_t> TRPCRequestHandler::RPCTransceive(PRPCRequest Request,
Сделала очередь

2022-07-18 07:27 UTC, ekateluv commented on src/rpc_request_handler.cpp
> +    if (State == RPCRequestState::RPC_WRITE) {
Сделала очередь

2022-07-18 07:27 UTC, ekateluv commented on src/serial_client.cpp
> +    bool continue_signal_handling;
Все это убрала

2022-07-18 07:34 UTC, ekateluv commented on src/rpc_handler.cpp
> +    } catch (TRPCException& e) {
Упс...Есть небольшая проблема: с той системой ошибок, которая сейчас есть, уже написан modbus_client_rpc. @webconn переделываем и там и тут?

2022-07-18 07:46 UTC, KraPete commented on src/rpc_handler.cpp
> +    } catch (TRPCException& e) {
Мои замечания это же не руководство к реализации. Там, где мне покажется необходимым, я прямо так и напишу, что хочу переделать. Всё обсуждается. Здесь, наверное, можно оставить, но надо понимать почему так. Например, всякие homeui и прочие обёртки над rpc умеют в стандартные ошибки.

2022-07-18 08:08 UTC, ekateluv commented on src/serial_port_driver.cpp
> +    SerialClient = std::make_shared<TSerialClient>(Config->Devices, Config->Port, Config->OpenCloseSettings, metrics);
Вернула все как было

2022-07-18 10:17 UTC, webconn commented on src/rpc_handler.cpp
> +    } catch (TRPCException& e) {
> Упс...Есть небольшая проблема: с той системой ошибок, которая сейчас есть, уже написан modbus_client_rpc. @webconn переделываем и там и тут?

Да, есть смысл переделать и там, и там, в libwbmqtt1 действительно есть устоявшийся формат ошибки, который с этим не сходится.

2022-07-20 09:51 UTC, KraPete requested changes
Ты пробовала прогонять свой код через clang-format? Форматирование не соответствует нашим стандартам.

2022-07-20 09:51 UTC, KraPete commented on src/serial_client.cpp
>  void TSerialClient::NotifyFlushNeeded()
Этот метод вообще не нужен, можно удалить.

2022-07-20 09:51 UTC, KraPete commented on src/serial_client.cpp
> +            PQueueMessage message = std::make_shared<TSetValueQueueMessage>();
Весь этот метод тоже не нужен. Ты эту логику на очередь заменила

2022-07-20 09:51 UTC, KraPete commented on src/serial_client.cpp
> +    FlushNeeded = std::make_shared<TSerialClientQueue>();
Зачем память выделять динамически? Почему нельзя просто сделать членом класса?

2022-07-20 09:51 UTC, KraPete commented on src/rpc_handler.cpp
> +    Message->Port = RPCPort->GetPort();
Почему не сделать всю инициализацию в конструкторе TRPCQueueMessage?

2022-07-20 09:51 UTC, KraPete commented on src/rpc_handler.cpp
> +        RequestSchema = WBMQTT::JSON::Parse(RPC_REQUEST_SCHEMA_FULL_FILE_PATH);
Лучше передать путь до схемы в конструкторе

2022-07-20 09:51 UTC, KraPete commented on wb-mqtt-serial-rpc-request.schema.json
> +      "description": "Excexted response size",
Орфографическая ошибка

2022-07-20 09:51 UTC, KraPete commented on wb-mqtt-serial-rpc-request.schema.json
> +      "description": "Request execution time including queue time and thread operations, default 10",
Общее время 20 (кстати, это мс или с?), а первый байт ждём 500мс. Что-то тут не так.

2022-07-20 10:34 UTC, ekateluv commented on src/rpc_handler.cpp
> +                int PortNumber;
Потому что Get() не умеет в uint16_t. То оно то ли сразу не компилируется с ошибкой, что нет подходящего шаблона, то ли во время выполнения исключение, я точно не помню. Но у меня не заработало

2022-07-20 10:39 UTC, ekateluv commented on src/serial_client.cpp
> +    FlushNeeded = std::make_shared<TSerialClientQueue>();
Оно до этого было указателем, вдруг это зачем то было нужно, вот и оставила. Так то можно конечно статикой, оно все равно только внутри класса используется

2022-07-20 10:45 UTC, ekateluv commented on src/rpc_handler.cpp
> +    Message->Cancelled = std::make_shared<std::atomic<bool>>(false);
Потому что результат выполнения запроса и механизмы взаимодействия (переменные Done и Cancelled) передаются тут же в этом же сообщении, чтобы поток serial client мог общаться с потоком rpc. Либо можно сделать еще одну очередь в обратном направлении от serial client к rpc и тот будет сидеть ждать в ней ответных сообщений. Тогда можно без указателей

2022-07-20 10:51 UTC, ekateluv commented on src/rpc_handler.h
> +    PSerialPortDriver SerialPortDriver;
По иерархии классов идет как: сначала SerialDriver, у него массив SerialPortDriver, потом SerialClient. Я подумала что правильнее будет обращаться к самому верхнему классу "владельцев порта"- SerialPortDriver, а не напрямую к SerialClient

2022-07-20 11:23 UTC, ekateluv commented on src/rpc_config.cpp
> +void TRPCConfig::AddSerialPort(PPort Port, std::string Path)
Поправила

2022-07-20 11:23 UTC, ekateluv commented on src/rpc_config.cpp
> +        if (Port == RPCPort->GetPort()) {
Поправила

2022-07-20 11:23 UTC, ekateluv commented on src/rpc_config.cpp
> +void TRPCConfig::AddTCPPort(PPort Port, std::string Ip, uint16_t PortNumber)
Поправила

2022-07-20 11:23 UTC, ekateluv commented on src/rpc_handler.cpp
> +    std::string ByteVectorToHexString(const std::vector<uint8_t>& ByteVector)
Сейчас пока так оставляем?

2022-07-20 11:31 UTC, ekateluv commented on src/rpc_handler.cpp
> +      Message(message),
Убрала

2022-07-20 11:35 UTC, ekateluv commented on src/rpc_port.cpp
> +TRPCSerialPort::TRPCSerialPort(PPort Port, std::string Path): TRPCPort(Port), Path(Path){};
Поправила

2022-07-20 11:36 UTC, ekateluv commented on src/serial_client_queue.h
> +    virtual ~TQueueMessage(){};
Поправила

2022-07-20 11:37 UTC, ekateluv commented on src/serial_client.cpp
>  void TSerialClient::NotifyFlushNeeded()
Убрала

2022-07-20 11:48 UTC, KraPete commented on src/rpc_handler.cpp
> +    std::string ByteVectorToHexString(const std::vector<uint8_t>& ByteVector)
Оставляем

2022-07-20 11:51 UTC, KraPete commented on src/serial_client.cpp
> +    FlushNeeded = std::make_shared<TSerialClientQueue>();
Не знаю, зачем так было сделано, не могу придумать объяснения

2022-07-20 16:27 UTC, webconn commented
> Каким то странным образом я сама у себя ревью начала. Удалять не буду, иначе все комменты тоже удалятся

Так ведь даже удобней, ты можешь так в одно уведомление ответить на все комментарии

2022-07-27 05:23 UTC, KraPete requested changes
1. Очень хочу пропустить всё это через clang-format с нашим конфигом для форматирования.
2. Очень хочу тесты :)

2022-07-27 05:23 UTC, KraPete commented on debian/changelog
> +  * Add RPC functionality
Может более развёрнуто, что за метод добавлен? Не надо портянку, но хоть что и зачем.

2022-07-27 05:23 UTC, KraPete commented on src/rpc_handler.cpp
> +        LOG(Error) << "RPC request schema readind error: " << e.what();
reading

2022-07-27 05:23 UTC, KraPete commented on src/rpc_handler.cpp
> +                break;
Можно break не писать

2022-07-27 05:23 UTC, KraPete commented on src/rpc_handler.h
> +const auto RPC_REQUEST_SCHEMA_FULL_FILE_PATH = "/usr/share/wb-mqtt-serial/wb-mqtt-serial-rpc-request.schema.json";
Можно это в main ко всем константам с внешними файлами и путями? Ну и чтобы оно там как-то передавалось в конструкторы

2022-07-27 05:23 UTC, KraPete commented on src/rpc_request_handler.cpp
> +    return Response;
Мы сюда никогда не попадём

2022-07-27 05:23 UTC, KraPete commented on src/rpc_request_handler.cpp
> +    if (State == RPCRequestState::RPC_WRITE) {
Надо ли закрывать State мьютексом?

2022-07-27 05:23 UTC, KraPete commented on test/serial_config_test.cpp
> +    PRPCConfig rpcConfig = std::make_shared<TRPCConfig>();
Можно без инициализации, и так конструктор вызовется с тем же результатом

2022-07-27 06:00 UTC, KraPete commented
Ещё бы я прошёлся по всем методам и посмотрел, какие из них могут быть `const`

2022-07-27 07:57 UTC, ekateluv commented on src/rpc_handler.cpp
> +        LOG(Error) << "RPC request schema readind error: " << e.what();
Поправила

2022-07-27 07:57 UTC, ekateluv commented on src/rpc_handler.cpp
> +                break;
Убрала

2022-07-27 07:57 UTC, ekateluv commented on src/rpc_handler.h
> +const auto RPC_REQUEST_SCHEMA_FULL_FILE_PATH = "/usr/share/wb-mqtt-serial/wb-mqtt-serial-rpc-request.schema.json";
Переместила

2022-07-27 07:57 UTC, ekateluv commented on src/rpc_request_handler.cpp
> +    return Response;
Угу, убрала

2022-07-27 07:57 UTC, ekateluv commented on test/serial_config_test.cpp
> +    PRPCConfig rpcConfig = std::make_shared<TRPCConfig>();
Здесь все равно нужно создавать объект (в тестах есть убращение по указателю), кроме того в аргументах функций используется PRPCConfig, поэтому если сделать статический TRPCConfig, при передаче аргументов все время нужно будет брать указатель

2022-07-27 07:57 UTC, ekateluv commented on debian/changelog
> +  * Add RPC functionality
Добавила

2022-07-27 07:57 UTC, ekateluv commented on src/rpc_request_handler.cpp
> +    if (State == RPCRequestState::RPC_WRITE) {
Вобще, мне кажется, это место можно было бы сделать так:
Убрать отсюда еще один семафор с сигналом, оставить один мьютекс и condition_variable. Rpc поток берет мьютекс, вызывает wait_until, исполняющий поток берет мьютекс, выполняет запрос, делает notify, выходит, rpc просыпается, берет мьютекс, ну и дальше выполняет что там осталось от функции и выходит с освобождением мьютекса

2022-07-27 09:15 UTC, KraPete commented on src/rpc_request_handler.cpp
> +    if (State == RPCRequestState::RPC_WRITE) {
Если честно, я чё-то там запутался в этих семафорах, сигналах, мьютексах. Видимо, старею уже. Мне лично сложно логику проследить. Я, конечно, в общих чертах понимаю, что и зачем, но на глаз смоделировать поведение не могу. Я потому и начал за очередь топить, что там логика прозрачнее.  Ну и на первый взгляд надо работу со State как-то делать атомарной, потому и спросил. @webconn посмотришь в это место?

2022-07-29 11:47 UTC, webconn commented on src/rpc_request_handler.cpp
> +    if (State == RPCRequestState::RPC_WRITE) {
Ну я тут вижу проблему, что state и не защищается мьютексом, он где-то мимо него читается и пишется.

@ekateluv можешь прокомментировать? Какие где потоки появляются?

В идеале добавить комментарий о том, что от кого мы тут защищаем

2022-07-29 13:29 UTC, webconn requested changes

2022-07-29 13:29 UTC, webconn commented on src/rpc_handler.cpp
> +                rpcPortDriver->SerialClient = serialPortDriver->GetSerialClient();
Ощущается это неправильно, обычно для поиска используются чистые функции, без побочных эффектов. Лучше тут забрать возвращаемое значение и над ним уже выполнить действие (кстати, какое ожидается поведение, если ничего не нашлось?)

2022-07-29 13:29 UTC, webconn commented on src/rpc_request_handler.cpp
> +    if (State == RPCRequestState::RPC_WRITE) {
Решили, что надо дозавернуть мьютекс, а дальше использовать condition_variable вместо семафора

2022-07-29 13:29 UTC, webconn commented on src/rpc_request_handler.cpp
> +    this->Request = request;
`this` можно убрать теперь отсюда

2022-08-01 07:31 UTC, ekateluv commented on src/binary_semaphore.h
> +        std::unique_lock<std::mutex> lock(Mutex);
Поставила lock_guard

2022-08-01 07:31 UTC, ekateluv commented on src/binary_semaphore.h
> +        std::unique_lock<std::mutex> lock(Mutex);
Поставила lock_guard во всех функциях семафора

2022-08-01 07:31 UTC, ekateluv commented on src/rpc_handler.cpp
> +                rpcPortDriver->SerialClient = serialPortDriver->GetSerialClient();
Поправила. Насчет реакции: если в этом месте поиск завершился неудачно, то это значит что по указателю на порт не удалось найти его serialClient. А это уже означает, что согласованность данных в структурах нарушена и большой вопрос, можно ли продолжать работать в таких условиях. Для RPC IO в порт - точно нет. Думаю, есть два варианта:
1. Если мы решим, что это ситуация не критична для всего serial, то при инициализации можно сделать запись в лог с ошибкой, что не нашлось соответствие. А при выполнении RPC запроса возвращать ошибку с пояснением, что для запрошенного порта не был найден serialClient.
2. Если мы решим, что если нам не удалось восстановить связку PPort + PSerialClient, то это означает что в принципе нельзя дальше работать, то тогда выбрасываем исключение, завершаем serial. Звучит конечно радикально, но такая ситуация может произойти либо потому что RPC косячно собрал указатели, либо косячит код который создает все эти объекты, что уже как то не прикольно.

2022-08-01 07:31 UTC, ekateluv commented on src/rpc_request_handler.cpp
> +    this->Request = request;
Убрала

2022-08-01 08:48 UTC, KraPete commented on src/rpc_handler.cpp
> +                rpcPortDriver->SerialClient = serialPortDriver->GetSerialClient();
Лучше в лог писать и отдавать ошибку в RPC

2022-08-12 05:36 UTC, KraPete requested changes

2022-08-12 05:36 UTC, KraPete commented on src/serial_device.h
> +    virtual void Prepare();
Зачем `virtual`?

2022-08-12 05:36 UTC, KraPete commented on test/fake_serial_device.h
> +    void Prepare() override;
Есть PrepareImpl для этого

2022-08-12 05:36 UTC, KraPete commented on test/serial_client_test.cpp
> +    // SerialDriver->LoopOnce();
Зачем?

2022-08-12 05:36 UTC, KraPete commented on test/serial_client_test.cpp
> +        // std::thread serialDriverThread(&TSerialClient::RPCTransceive, serialClient, request);
И это зачем?

2022-08-12 05:36 UTC, KraPete commented on test/serial_client_test.cpp
> +    PublishWaitOnValue("/devices/RPCTest/controls/RGB/on", "10;20;30", 0, true);
Хочу тут комментарий, что тестируется и какое поведение ожидается.

2022-08-12 05:36 UTC, KraPete commented on test/serial_client_test.cpp
> +    Json::Value configSchema = LoadConfigSchema(GetDataFilePath("../wb-mqtt-serial.schema.json"));
Хочу тут комментарий, что тестируется и какое поведение ожидается.

2022-08-12 05:36 UTC, KraPete commented on test/serial_client_test.cpp
> +    if (rpcException.GetResultCode() != TRPCResultCode::RPC_OK) {
EXPECT_EQUAL?

2022-08-12 13:18 UTC, ekateluv commented on test/serial_client_test.cpp
> +    PublishWaitOnValue("/devices/RPCTest/controls/RGB/on", "10;20;30", 0, true);
Написала

2022-08-12 13:18 UTC, ekateluv commented on test/serial_client_test.cpp
> +        // std::thread serialDriverThread(&TSerialClient::RPCTransceive, serialClient, request);
Убрала

2022-08-12 13:18 UTC, ekateluv commented on test/serial_client_test.cpp
> +    // SerialDriver->LoopOnce();
Убрала

2022-08-12 13:19 UTC, ekateluv commented on .gitignore
> -wb-mqtt-serial-templates/config-wb-mr6cu.json
Поправила тут

2022-08-12 13:19 UTC, ekateluv commented on src/rpc_handler.cpp
> +            throw std::runtime_error("Hex message have odd char count");
Поправила

2022-08-12 13:20 UTC, ekateluv commented on src/rpc_handler.cpp
> +        throw std::runtime_error(e);
Поправила

2022-08-12 13:20 UTC, ekateluv commented on test/fake_serial_device.h
> +    void Prepare() override;
Не заметила эту функцию сначала, поправила

2022-08-12 13:20 UTC, ekateluv commented on src/serial_device.h
> +    virtual void Prepare();
Убрала

2022-08-12 13:20 UTC, ekateluv commented on test/serial_client_test.cpp
> +    Json::Value configSchema = LoadConfigSchema(GetDataFilePath("../wb-mqtt-serial.schema.json"));
Написала

2022-08-12 13:21 UTC, ekateluv commented on test/serial_client_test.cpp
> +    if (rpcException.GetResultCode() != TRPCResultCode::RPC_OK) {
Возвращаю код в вызывающую функцию, проверяю там через EXPECT_EQ

2022-08-12 15:06 UTC, ekateluv commented on src/rpc_request_handler.cpp
> +            for (size_t i = 0; i < ActualSize; i++) {
std::copy_n

2022-08-15 06:17 UTC, KraPete approved these changes

2022-08-15 08:36 UTC, ekateluv commented on src/rpc_request_handler.cpp
> +            std::copy_n(readData.begin(), actualSize, std::back_inserter(ReadData));
Так сделать не получится. Потому что ReadFrame принимает в качестве буфера указатель на обычный массив uint8_t* buf и пишет в него напрямую, не через вектор. Поэтому после выполнения процедуры, хоть валидные данные и будут содержаться в хранилище вектора, его ReadData.size() будет равен нулю, поскольку элементы добавлялись напрямую, а не через интерфейс вектора. Вследствие этого resize будет думать что вектор пуст и заполнит его нулями и мы потеряем результат.

2022-08-15 08:36 UTC, ekateluv commented on test/serial_client_test.cpp
> +                                                            std::vector<int> expectedRequest,
Вектор передается как ```<int>``` потому что функция Port->Exect() принимает только ```vector<int>```, поэтому в поле запроса вектор перемещается через copy.
Int заменила на size_t

2022-08-15 08:36 UTC, ekateluv commented on test/serial_client_test.cpp
> +    TRPCException rpcException("", TRPCResultCode::RPC_OK);
Поправила

2022-08-15 08:36 UTC, ekateluv commented on src/rpc_handler.cpp
> +        for (unsigned int i = 0; i < hexString.size(); i += 2) {
Поправила

2022-08-15 13:24 UTC, merged