Feature/51140 wb led template
wirenboard/wb-mqtt-serial pull request #474
Opened 2022-07-18 12:39 UTC by pgasheev

2022-07-19 14:36 UTC, ExplorerOL requested changes

2022-07-19 14:36 UTC, ExplorerOL commented on template-templates/config-wb-led.json.jinja
> +                "Overcurrent protection": "Перегрузка по току",
"Overcurrent protection" предлагаю заменить на "Overcurrent", как в MDM3.

2022-07-20 05:41 UTC, pgasheev commented on .gitignore
> +wb-mqtt-serial-templates/config-wb-led.json
А чем это друг от друга отличается? Там удалили, здесь не создавали. В итоге и там и там шаблона нет. Могу откатить, но принцип пока непонятен

2022-07-20 05:43 UTC, pgasheev commented on template-templates/config-wb-led.json.jinja
> +                "Available Power": "Располагаемая мощность",
Это означает максимальную мощность, на которой может работать диммер. Зависит от температуры платы. Описал в [документации](https://wirenboard.com/wiki/WB-LED_v.1_Modbus_LED_Dimmer#Защита_от_перегрузки_по_току_и_перегреву)

По другому пока не придумал как назвать

2022-07-20 09:11 UTC, ExplorerOL approved these changes

2022-07-20 11:08 UTC, pgasheev commented on template-templates/config-wb-led.json.jinja
> +                "Available Power": "Располагаемая мощность",
Поменяли на "Разрешенная мощность"

2022-07-20 11:10 UTC, merged