added cm1106 register and co2 common for MSW v3
wirenboard/wb-mqtt-serial pull request #478
Opened 2022-07-26 10:04 UTC by RLOVD

2022-07-26 12:11 UTC, wb-adegtyarev commented
Я видел в таблице регистров, что появились регистры, которые работают в с одним типом датчика, но не работают с другим.

Предлагаю это учесть в новом шаблоне и добавить в description, какой параметр с каким датчиком работает.

2022-07-27 08:58 UTC, nikitoz236 commented
в description можно добавить. и при каком значении регистра типа датчика еще можно добавить. 

это временная мера чтобы пользовали могли настраивать датчик. @KraPete обещал добавить тип виртуальный переключатель, чтобы относительно него используя condition прятать неиспользуемые параметры.

2022-07-29 12:11 UTC, RLOVD commented
На данный момент description для регистров не доступен, только для параметров. Ждем поддержку с выбором типа датчика в serial

2022-08-01 14:12 UTC, ExplorerOL requested changes

2022-08-01 14:12 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "CO2 Sens Type": "Тип установленного датчика CO2",
Думаю, достаточно "Тип датчика CO2"

2022-08-01 14:12 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "error_value": "0xFFFF",
Предлагаю добавить поле min

2022-08-02 09:03 UTC, RLOVD commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "CO2 Force Calibration To Value": "Принудительная калибровка датчика CO2 на заданное значение концентрации",
Я думаю лучше оставить как есть, в вики написано также:
https://wirenboard.com/wiki/WB-MSWv_3_registers
гораздо понятнее

2022-08-02 09:49 UTC, RLOVD commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "CO2 Force Calibration Cycle": "Длительность цикла для самокалибровки датчика CO2",
В днях, изменять можно

2022-08-02 09:49 UTC, RLOVD commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "name": "CO2 Sens Availability",
значения 0-1

2022-08-02 12:40 UTC, ExplorerOL commented on test/TDeviceTemplatesTest.Validate.dat
> +	CO₂  =>  CO₂
Имена каналов изменять нельзя, в каналах везде оставить CO2.

Я имел в виду только в title у параметра в одном месте изменить на CO₂, как и у других.

2022-08-02 12:40 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "CO2 Force Calibration To Value": "Принудительная калибровка датчика CO2 на заданное значение концентрации",
Думаю, что так смотрится плохо:
![image](https://user-images.githubusercontent.com/36483527/182377006-239dd589-8d77-4319-bacc-ab3f07ae4ba3.png)

2022-08-02 13:00 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "CO2 Force Calibration To Value": "Принудительная калибровка датчика CO2 на заданное значение концентрации",
Очень длинное название канала плохо смотрится. 
![image](https://user-images.githubusercontent.com/36483527/182380400-f07e3289-2b0a-4af9-a7e6-a8c63c14ba67.png)
![image](https://user-images.githubusercontent.com/36483527/182380498-d0503919-c494-4b6d-af64-76830597f3ee.png)

Еще один вариант:
co2 calibration value: калибровочное значение co2

2022-08-02 15:24 UTC, nikitoz236 commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "CO2 Force Calibration To Value": "Принудительная калибровка датчика CO2 на заданное значение концентрации",
калибровать показания CO2

2022-08-04 11:46 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "description": "Only for Winsen CO₂ sensor",
А Winsen - это датчики CM1106 и CM1107? Предлагаю указать здесь еще и модели "Only for Winsen CM110x sensors". Иначе пользователь не догадается, какой производитель его датчика, так как на сайте это не указано.
![image](https://user-images.githubusercontent.com/36483527/182837113-d4e53e26-0c2f-4bcf-8c40-fca9e1c496ce.png)

2022-08-04 11:46 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "CO2 Reference Sensor Value": "Значение референсного датчика CO2",
Можно и так, конечно, но предвижу уже вопросы пользователей: "А где смотреть показания этого рефернсного датчика, откуда их брать и где этот датчик стоит?"
Вот такой еще вариант:
"CO2 Reference Value": "Референсное значение CO2",

2022-08-04 12:04 UTC, RLOVD commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "description": "Only for Winsen CO₂ sensor",
Нет, Winsen это старые датчики, тоесть MH-Z19B. CM1106 это Cubic. Непонятно зачем при заказе указываются конкретные модели датчиков. Вроде как обсуждали и в карте регистров делали Cubic и Winsen @nikitoz236

2022-08-04 12:09 UTC, RLOVD commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "CO2 Reference Sensor Value": "Значение референсного датчика CO2",
Скорее всего надо в документации этот момент отразить. Регистр выведен как debug и отключен, пользователю который задает такие вопросы вообще не стоит в этот регистр что то записывать скорее всего.

2022-08-04 18:09 UTC, nikitoz236 commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "description": "Only for Winsen CO₂ sensor",
решили названия моделей датчиков всетаки использовать как в каталоге.

2022-08-09 12:22 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "units": "ppm",
В логе получаю ошибки:
![image](https://user-images.githubusercontent.com/36483527/183643604-233001fd-aac3-425a-8197-063d3dc75c5e.png)

Пока в документации не нашел про поддержку units : ppm и units: day. Думаю, нужно уточнить у программистов, можно ли использовать произвольные названия тут. Если нельзя, то использовать concentration, а для дней не знаю даже...

2022-08-09 12:22 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "group": "debug"
Предлагаю этот канал переместить в группу Air Quality. Ведь он предназначен и для пользователей тоже. По умолчанию выключить.

2022-08-09 12:22 UTC, ExplorerOL commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "group": "debug"
Предлагаю этот канал переместить в группу Air Quality. Ведь он предназначен и для пользователей тоже. По умолчанию выключить.

2022-08-09 12:37 UTC, RLOVD commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "units": "ppm",
@KraPete сильно страшно тут что ворнинги?

2022-08-10 06:24 UTC, KraPete commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "units": "ppm",
Не страшно. Можешь задачу сделать на добавление, чтоб не ругалось? Это специально, чтоб видно было каких единиц измерения не хватает. Больше ни на что не влияет.

2022-08-10 06:28 UTC, RLOVD commented on wb-mqtt-serial-templates/config-wb-msw_v3.json
> +                "units": "ppm",
ок

2022-08-10 11:24 UTC, ExplorerOL approved these changes

2022-08-11 08:19 UTC, KraPete requested changes
Где-то в названиях CO₂, а где-то CO2. Думаю, надо привести к одному виду.

2022-08-11 14:05 UTC, nikitoz236 commented
> Где-то в названиях CO₂, а где-то CO2. Думаю, надо привести к одному виду.

ну у нас в каналах уже CO2 с большой двойкой. ломать обратную совместимость мы не будем. Сейчас во всех параметрах двойка маленькая. Предлагаю оставить. Однообразие есть. в интерфейсе маленькая двойка выглядит правильнее. интерфейс ее рисовать может раз мы ее давным давно добавили. такчто пусть так и остается. в каналах большая так как это имя топика а в параметрах маленькая. вот когда у нас имя топика канала от названия канала будет отвязаным там тоже сделаем маленькую двойку.

2022-08-11 14:06 UTC, nikitoz236 approved these changes

2022-08-11 14:15 UTC, merged

2022-08-11 15:00 UTC, KraPete commented
> > Где-то в названиях CO₂, а где-то CO2. Думаю, надо привести к одному виду.
> 
> ну у нас в каналах уже CO2 с большой двойкой. ломать обратную совместимость мы не будем. Сейчас во всех параметрах двойка маленькая. Предлагаю оставить. Однообразие есть. в интерфейсе маленькая двойка выглядит правильнее. интерфейс ее рисовать может раз мы ее давным давно добавили. такчто пусть так и остается. в каналах большая так как это имя топика а в параметрах маленькая. вот когда у нас имя топика канала от названия канала будет отвязаным там тоже сделаем маленькую двойку.

С разморозкой Вас. У нас имя канала отвязано от надписи в веб интерфейсе с момента появления переводов. Я ж не зря про названия написал.

И в параметрах так же. Вот, например, в `co2_measurement_range` можно `title` делать с маленькой двойкой, а `co2_sensor_type` нельзя?