Limit registers reads per second
wirenboard/wb-mqtt-serial pull request #493
Opened 2022-08-17 13:07 UTC by KraPete

2022-08-19 22:52 UTC, evgeny-boger requested changes
я бы ещё rate_limit добавил в дефолтные конфиги разных вб

2022-08-19 22:52 UTC, evgeny-boger commented on src/poll_plan.h
> +            lowPriorityDeadline = LowPriorityRateLimit.GetStartTime() + std::chrono::seconds(1);
это же получается очень неравномерная нагрузка. Это не будет заметно?

Если оставлять такой алгоритм, то может быть стоит как-то более осмысленно выбрать константу времени (т.е. вместо 1 секунды здесь)

2022-08-22 07:26 UTC, KraPete commented on src/poll_plan.h
> +            lowPriorityDeadline = LowPriorityRateLimit.GetStartTime() + std::chrono::seconds(1);
Да, нагрузка не равномерная. Каждую секунду сначала читаем непрерывно, потом ждём конца секунды, потому тут и такая костанта в секунду. В любом случае не получится равномерно размазать нагрузку, мы ж не можем предсказать, когда придётся делать публикацию, а основная нагрузка именно при публикации.

2022-08-22 07:28 UTC, KraPete commented
> я бы ещё rate_limit добавил в дефолтные конфиги разных вб

Я сделал ограничение на весь сервис. Если сделать на конкретные устройства, всё равно можно будет насобирать кучу регистров и публикаций.

2022-08-22 07:37 UTC, evgeny-boger commented
> > я бы ещё rate_limit добавил в дефолтные конфиги разных вб
> 
> Я сделал ограничение на весь сервис. Если сделать на конкретные устройства, всё равно можно будет насобирать кучу регистров и публикаций.

я говорю про дефолтные /etc/wb-mqtt-serial.conf, которые устанавливаются разные в зависмости от версии контроллера.

2022-08-22 07:38 UTC, evgeny-boger commented on src/poll_plan.h
> +            lowPriorityDeadline = LowPriorityRateLimit.GetStartTime() + std::chrono::seconds(1);
так вот, если выбрать 100мс или 10с, то поведение не будет лучше? Здесь же 1с выбрана произвольно.

2022-08-22 07:54 UTC, KraPete commented on src/poll_plan.h
> +            lowPriorityDeadline = LowPriorityRateLimit.GetStartTime() + std::chrono::seconds(1);
Секунда выбрана из-за того, что "что-то в секунду" - первое что приходит на ум. Кажется, что чем меньше интервал, тем более равномерная нагрузка будет.

2022-08-24 06:25 UTC, KraPete commented
> > > я бы ещё rate_limit добавил в дефолтные конфиги разных вб
> > 
> > 
> > Я сделал ограничение на весь сервис. Если сделать на конкретные устройства, всё равно можно будет насобирать кучу регистров и публикаций.
> 
> я говорю про дефолтные /etc/wb-mqtt-serial.conf, которые устанавливаются разные в зависмости от версии контроллера.

Я сделал определение по числу ядер, если ничего в конфиге не задано, то выбираются 100 или 800. Думаю, в конфиг по умолчанию можно и не обавлять.

2022-08-25 18:18 UTC, evgeny-boger approved these changes

2022-09-06 07:08 UTC, webconn commented on src/poll_plan.h
> +        return std::min(HighPriorityQueue.GetDeadline(), lowPriorityDeadline);
Ещё стоит как-то наружу сообщить, что мы достигли предела и работаем в режиме rate limit. Липких индикаторов у нас никаких нет, так что пока можно было бы писать в лог (ограничив количество сообщений до одного в день, например. Думаю, такое ограничение можно хоть на макросах сделать, как в glog).

2022-09-14 10:51 UTC, KraPete commented on src/poll_plan.h
> +        return std::min(HighPriorityQueue.GetDeadline(), lowPriorityDeadline);
А надо ли? На WB6 оно будет очень часто, на WB7 - реже. Мы всё равно ничего не сможем сделать с этим. Надо системно работать по всему стеку приложений, чтоб они могли большое число публикаций обрабатывать с низкой нагрузкой.

2022-09-14 11:25 UTC, webconn commented on src/poll_plan.h
> +        return std::min(HighPriorityQueue.GetDeadline(), lowPriorityDeadline);
Ну так на WB6 это будет нештатное поведение всё равно, об этом хочется узнать как-то при диагностике

2022-09-19 11:43 UTC, KraPete commented on src/poll_plan.h
> +        return std::min(HighPriorityQueue.GetDeadline(), lowPriorityDeadline);
Добавил сообщение

2022-09-19 11:50 UTC, webconn approved these changes

2022-09-19 13:20 UTC, merged