RPC: Get list of enabled ports
wirenboard/wb-mqtt-serial pull request #525
Opened 2022-10-21 14:44 UTC by sikmir

### Test instructions
```
$ cat wb-mqtt-serial.conf
{
  "ports": [
    {
      "enabled": true,
      "path": "/dev/pts/2"
    },
    {
      "enabled": true,
      "port_type": "tcp",
      "address": "127.0.0.1",
      "port": 2000
    },
    {
      "enabled": false,
      "path": "/dev/pts/3"
    }
  ]
}
$ wb-mqtt-serial -c ./wb-mqtt-serial.conf
```

```
$ mosquitto_sub -t /rpc/v1/wb-mqtt-serial/ports/Load/client_id/reply
{"error":null,"id":1,"result":[{"baud_rate":9600,"data_bits":8,"parity":"N","path":"/dev/pts/2","stop_bits":1},{"address":"127.0.0.1","port":2000}]}
```

```
$ mosquitto_pub -t /rpc/v1/wb-mqtt-serial/ports/Load/client_id -m "{\"params\":{},\"id\":1}"
```

2022-10-24 06:01 UTC, KraPete requested changes
1. Документация на RPC  в Readme.md
2. Я согласнен, что предложенное решение самое очевидное и, наверное, по коду короткое. Но идеологически оно мне абсолютно не нравится. Мы сначала скрываем всё через общий интерфейс, а потом начинаем скрытые детали выставлять наружу. Ну и JSON в интерфейсе порта выглядит явно неуместно. Предлагаю подумать, как можно это всё сделать без изменения интерфейса порта. Можно, например, запомнить JSON при чтении конфига, как это Катя в предыдущем коммите сделала.

2022-10-26 05:27 UTC, KraPete commented on src/rpc_config.h
> +    Json::Value Config{Json::arrayValue};
Может, изменить название на что-то типа `PortConfigs`. А то не ясно, что это за настройки.

2022-10-26 06:46 UTC, sikmir commented on src/rpc_config.h
> +    Json::Value Config{Json::arrayValue};
Да, переименовал

2022-10-26 08:03 UTC, KraPete commented on src/rpc_config.h
> +    Json::Value GetConfig() const;
Ну и тут тогда переимновать надо

2022-10-26 08:24 UTC, sikmir commented on src/rpc_config.h
> +    Json::Value GetConfig() const;
поправил

2022-10-26 09:38 UTC, KraPete approved these changes

2022-10-26 11:20 UTC, merged