Feature/54334 rpc connection settings
wirenboard/wb-mqtt-serial pull request #529
Opened 2022-10-26 21:26 UTC by sikmir

2022-10-27 07:36 UTC, vdromanov commented on src/serial_device.h
> +const int DefaultStopBits = 1;
а стопбит - точно по умолчанию 1?
в наших устройствах 2 же (напиши мб в dev-чатик, а то я могу ошибаться)


и еще вопрос (вопрос, не исправление):
а в сериале как-то под капотом реализована логика "стопбиты из настроечек (2sb по умолчанию) на передачу; 1sb (всегда) - на приём"?

2022-10-27 07:44 UTC, vdromanov commented on src/serial_port.cpp
> +            throw std::runtime_error("can't open serial port");
а точно runtime_error надо кидать?
у нас же в libwbmqtt какие-то эксепшоны есть
мб strerror(errno) еще печатать в эксепшоне здесь и дальше?

(не настаиваю; могу ошибаться)

2022-10-27 07:50 UTC, vdromanov commented on src/serial_port.cpp
> +        throw std::runtime_error("can't set termios attributes" + FormatErrno(errno));
кстати, а через rpc эти ошибки будет видно?
если нет - хотелось бы! (а то у нас иногда может случиться, что стучимся в fd, которого еще нет) => как-то понимать бы снаружи, что всё плохо

2022-10-27 08:22 UTC, sikmir commented on src/serial_device.h
> +const int DefaultStopBits = 1;
убираем дефолты, делаем обязательным параметром в RPC запросе

2022-10-28 06:57 UTC, sikmir commented on src/serial_port.cpp
> +        throw std::runtime_error("can't set termios attributes" + FormatErrno(errno));
Да, например порт /dev/pts/7 сконфигурен, но его нет:
```json
{"error":{"code":-32000,"data":"Serial protocol error: /dev/pts/7, can't open serial port","message":"Server error"},"id":1}
```

2022-10-28 10:18 UTC, KraPete requested changes

2022-10-28 10:18 UTC, KraPete commented on debian/changelog
> +wb-mqtt-serial (2.73.2) stable; urgency=medium
API поменяли, надо minor увeличить

2022-10-28 10:18 UTC, KraPete commented on src/port.h
> +    virtual void ApplySerialPortSettings(const TSerialPortSettings* settings = nullptr);
1. Документацию хочу.
2. Зачем передавать указатель? Что будет, если `nullptr` передали?

2022-10-28 10:18 UTC, KraPete commented on src/port.h
>      virtual void SetSerialPortByteFormat(const TSerialPortByteFormat* params);
Договаривались удалить этот метод и оставить один

2022-10-28 10:18 UTC, KraPete commented on src/serial_port.cpp
> +void TSerialPort::ApplySerialPortSettings(const TSerialPortSettings* settings)
В `TSerialPortSettings` есть `path`. Кажется, что тут мы и порт можем переоткрыть для другого устройства.
Вероятно, стоит расширить `TSerialPortByteFormat` или вообще переименовать и сделать структуру с настройками всего, кроме пути.

2022-10-28 10:18 UTC, KraPete commented on src/rpc_request.h
> +    int BaudRate;
Почему не использовать `TSerialPortSettings`?

2022-10-28 18:20 UTC, sikmir commented on debian/changelog
> +wb-mqtt-serial (2.73.2) stable; urgency=medium
готово

2022-10-28 18:25 UTC, sikmir commented on src/port.h
> +    virtual void ApplySerialPortSettings(const TSerialPortSettings* settings = nullptr);
2. Идея в том, что если вызываем без параметра (то есть с дефолтным nullptr), то применяются исходные настройки из конфига (TSerialPort хранит их внутри себя), то есть reset настроек.

2022-10-29 05:01 UTC, KraPete commented on src/port.h
> +    virtual void ApplySerialPortSettings(const TSerialPortSettings* settings = nullptr);
Да, я почитал, что у метода выше писал, и спомнил. Но надо описать это поведение в коментариях.

2022-10-31 06:59 UTC, sikmir commented on src/serial_device.h
> +const int DefaultStopBits = 1;
> а в сериале как-то под капотом реализована логика "стопбиты из настроечек (2sb по умолчанию) на передачу; 1sb (всегда) - на приём"?

По моему нет такого. А это для чего может быть нужно?

2022-10-31 15:22 UTC, sikmir commented on src/port.h
>      virtual void SetSerialPortByteFormat(const TSerialPortByteFormat* params);
Правильно понимаю что весь хак в виде TSerialPortWithIECHack тоже не нужен, если умеем менять настройки через tcsetattr и termios? То есть если у нас на порту хотя бы одно IEC устройство, то принудительно выставляем 7E1 для всего порта.

2022-10-31 15:45 UTC, sikmir commented on src/serial_port.cpp
> +            throw std::runtime_error("can't open serial port");
Он тут же ниже заворачивается в `TSerialDeviceException`.

2022-10-31 16:20 UTC, sikmir commented on src/serial_port.cpp
> +void TSerialPort::ApplySerialPortSettings(const TSerialPortSettings* settings)
Сейчас тут `path` пустой. А так мне кажется `path` у объекта `TSerialPort` должен быть инвариантом, новому устройству -  новый  `TSerialPort`.

2022-10-31 16:33 UTC, sikmir commented on src/rpc_request.h
> +    int BaudRate;
В `TSerialPortSettings` чуть больше параметров (есть path) чем тут нужно, я бы оставил `TRPCRequest` более простой структурой, не вкладывая `TSerialPortSettings`.

2022-10-31 23:29 UTC, vdromanov approved these changes
у меня настроечки порта через rpc переключаются; погонял упдатером

2022-11-02 09:55 UTC, webconn commented on src/port.h
> +    virtual void ApplySerialPortSettings(const TSerialPortSettings* settings = nullptr);
Магия дремучая, конечно. Может, для этого сделать метод `Reset...`?

2022-11-02 09:55 UTC, webconn commented on src/rpc_request.h
> +    int BaudRate;
Мне кажется тоже, что тут лучше использовать `TSerialPortSettings`. Он и так везде по коду в этом PR не совсем на своём месте и просится немного побить структуру, а так у нас хотя бы на основании типов можно будет судить о взаимосвязях.

Вообще можно было бы немного прикоснуться рефакторингом, сделав `TSerialPortSettings` наследником нового класса, в котором прописать только настройки порта, без пути, и использовать базовый класс в новом коде

2022-11-02 23:05 UTC, sikmir commented on src/port.h
> +    virtual void ApplySerialPortSettings(const TSerialPortSettings* settings = nullptr);
Пожалуй да, добавил Reset для понятности из названия

2022-11-02 23:21 UTC, sikmir commented on src/rpc_request.h
> +    int BaudRate;
Поменял на `TSerialPortSettings`. Сейчас он уже является наследником `TSerialPortByteFormat`, если будем избавлятся от `SetSerialPortByteFormat`, то как раз это место и подчистим.

2022-11-07 05:22 UTC, KraPete commented on src/port.h
>      virtual void SetSerialPortByteFormat(const TSerialPortByteFormat* params);
Да! Выпилить это убожество

2022-11-07 05:22 UTC, KraPete commented on src/serial_port.cpp
> +void TSerialPort::ApplySerialPortSettings(const TSerialPortSettings* settings)
Согласен. Потому и написал, что тут имеет смысл использовать отдельную структуру без пути.

2022-11-07 05:23 UTC, KraPete commented on src/rpc_request.h
> +    int BaudRate;
Я это и предлагаю. Вместо `TSerialPortByteFormat` сделать структуру с настройками без пути

2022-11-07 05:26 UTC, KraPete commented on src/port.h
>      virtual void SetSerialPortByteFormat(const TSerialPortByteFormat* params);
Не надо у всего порта выставлять настройки. Будет работать старый код для IEC устройств (оно при обращении меняет настройки, а потом сбрасывает на начальные), но бонусом мы получим возможность использовать на одном порту неIEC устройства с другими настройками порта.

2022-11-07 05:33 UTC, KraPete requested changes

2022-11-07 05:33 UTC, KraPete commented on wb-mqtt-serial-rpc-request.schema.json
> +        "baud_rate",
А зачем? Раньше можно было просто указать путь и использовать текущие настройки порта.

2022-11-07 05:33 UTC, KraPete commented on src/rpc_request_handler.cpp
> +        port->ResetSerialPortSettings();
Если выпадет случайное исключение, получим кривосконфигурированный порт. Use RAII, Luke!

2022-11-07 05:33 UTC, KraPete commented on src/port.h
> +    virtual void ResetSerialPortSettings();
Всё равно хочу комментарии

2022-11-07 11:49 UTC, sikmir commented on src/rpc_request_handler.cpp
> +        port->ResetSerialPortSettings();
добавил

2022-11-07 11:54 UTC, KraPete commented on src/serial_port.h
> +    TSerialPortSettingsGuard(PPort port, const TSerialPortSettings& settings): Port(port)
Можно реализацию в cpp?

2022-11-07 19:09 UTC, sikmir commented on src/rpc_request.h
> +    int BaudRate;
Вынес в `TSerialPortConnectionSettings`

2022-11-07 19:12 UTC, sikmir commented on src/serial_port.cpp
> +void TSerialPort::ApplySerialPortSettings(const TSerialPortSettings* settings)
Вынес в `TSerialPortConnectionSettings`

2022-11-07 19:17 UTC, sikmir commented on src/port.h
> +    virtual void ResetSerialPortSettings();
done

2022-11-07 20:54 UTC, sikmir commented on wb-mqtt-serial-rpc-request.schema.json
> +        "baud_rate",
Здесь https://github.com/wirenboard/wb-mqtt-serial/pull/529#discussion_r1006553418 и далее как раз обсуждали это, идея в том что слишком много вариаций возникает:
1. порт не сконфигурен, настроек нет в запросе - использовать некий дефолт (какой?)
2. порт сконфигурен, настроек нет в запросе - использовать конфигурацию порта или же дефолт?
3. порт сконфигурен и только часть настроек в запросе - мержить?
и т.д.

Делая rpc запрос теперь не предполагается заранее знать сконфигурен он или нет, в любом случае он будет выполнен, но если параметры явно не указаны в запросе, то ситуация немного неоднозначная если использовать текущие настройки порта - результат начинает зависеть от того, есть ли порт в конфиге.

2022-11-08 05:16 UTC, KraPete requested changes

2022-11-08 05:16 UTC, KraPete commented on src/iec_common.cpp
> +    int baudRate = static_cast<TSerialPort*>(Port().get())->GetSettings().BaudRate;
Мы везде писали, что умеем только 9600. По факту НЕВА работает только на 9600, в Энергомере можно выбрать до 300-19200.
Здесь сразу возникает проблема, мы должны будем использовать скорость обмена счётчика для всех устройств на шине.
Предлагаю тут забить явно 9600. Заодно не надо будет прокидывать `GetSettings()`

2022-11-08 05:16 UTC, KraPete commented on src/iec_common.h
> +#if 0 // TSerialPortWithIECHack removed
Убери это совсем

2022-11-08 05:16 UTC, KraPete commented on src/rpc_handler.cpp
> +            WBMQTT::JSON::Get(request, "baud_rate", RPCRequest->SerialPortSettings.BaudRate);
Почему это уехало сюда? Если порт `tcp`, эти параметры же не нужны.
Тогда может вообще весь разбор `json` убрать сюда. И в `SendRequest` не смотреть в `json`. Либо вернуть как было. А то странно, часть специфичных параметров разбирается тут, а часть в `SendRequest`.

2022-11-08 05:16 UTC, KraPete commented on src/serial_port.h
> +class TSerialPortSettingsGuard
Надо комментарий, что этот класс делает

2022-11-08 05:16 UTC, KraPete commented on src/serial_port_settings.h
> +    TSerialPortConnectionSettings(const TSerialPortConnectionSettings& other)
Пустую строку забыл

2022-11-08 05:16 UTC, KraPete commented on test/iec_test.cpp
> +#if 0 // TSerialPortWithIECHack removed
Давай, вообще весь файл уберём

2022-11-08 06:41 UTC, sikmir commented on test/iec_test.cpp
> +#if 0 // TSerialPortWithIECHack removed
убрал

2022-11-08 06:41 UTC, sikmir commented on src/serial_port_settings.h
> +    TSerialPortConnectionSettings(const TSerialPortConnectionSettings& other)
fixed

2022-11-08 06:41 UTC, sikmir commented on src/iec_common.h
> +#if 0 // TSerialPortWithIECHack removed
убрал

2022-11-08 06:45 UTC, sikmir commented on src/iec_common.cpp
> +    int baudRate = static_cast<TSerialPort*>(Port().get())->GetSettings().BaudRate;
Выкинул, теперь 9600

2022-11-08 06:45 UTC, sikmir commented on src/iec_common.cpp
> +#if 0 // TSerialPortWithIECHack removed
Выкинул

2022-11-08 06:49 UTC, KraPete commented on src/iec_common.cpp
> +    int baudRate = static_cast<TSerialPort*>(Port().get())->GetSettings().BaudRate;
Осталось Readme.md подправить, где написано про неву и энергомеру

2022-11-08 07:06 UTC, sikmir commented on src/port.h
> +    virtual void ResetSerialPortSettings();
добавил

2022-11-08 07:07 UTC, sikmir commented on src/serial_port.h
> +class TSerialPortSettingsGuard
добавил

2022-11-08 07:52 UTC, sikmir commented on src/rpc_handler.cpp
> +            WBMQTT::JSON::Get(request, "baud_rate", RPCRequest->SerialPortSettings.BaudRate);
Там 2 `SendRequest`, и во второй json вообще не передаем, поэтому пришлось здесь их разбирать. Пока можно проверку добавить чтобы разбирать их только если это сериал порт.

2022-11-09 07:27 UTC, sikmir commented on src/rpc_handler.cpp
> +            }
Ну сейчас тут `path` не нужен, это если все парсить тут, тогда и `address`/`port` тоже.

2022-11-09 07:31 UTC, sikmir commented on src/iec_common.cpp
> +    int baudRate = static_cast<TSerialPort*>(Port().get())->GetSettings().BaudRate;
поправил

2022-11-09 07:32 UTC, sikmir commented on src/serial_port.h
> +class TSerialPortSettingsGuard
добавил подробности

2022-11-09 07:48 UTC, KraPete commented on README.md
> +|`baud_rate`|обязательный |                      |скорость порта        |
Тогда тут и тип параметра, и значение по умолчанию не нужны

2022-11-09 07:50 UTC, KraPete approved these changes

2022-11-09 07:53 UTC, sikmir commented on README.md
> +|`baud_rate`|обязательный |                      |скорость порта        |
почистил

2022-11-09 08:53 UTC, merged