mai6 jinja template
wirenboard/wb-mqtt-serial pull request #530
Opened 2022-10-28 10:14 UTC by ExplorerOL

2022-10-28 10:25 UTC, KraPete requested changes

2022-10-28 10:25 UTC, KraPete commented on debian/changelog
> +wb-mqtt-serial (2.73.2) stable; urgency=medium
Давай, minor версию увеличим

2022-10-28 10:25 UTC, KraPete commented on template-templates/config-wb-mai6.json.jinja
> +{%- set types_with_gain = [0, 1, 3, 257] -%}
Если начал константы называть заглавными буквами, то давай все так делать

2022-10-28 10:25 UTC, KraPete commented on template-templates/config-wb-mai6.json.jinja
> +        "max_read_registers": 4,
Зачем это ограничение? Почему нельзя читать больше 4 регистров?

2022-10-28 13:57 UTC, ExplorerOL commented on debian/changelog
> +wb-mqtt-serial (2.73.2) stable; urgency=medium
сделал

2022-10-28 13:57 UTC, ExplorerOL commented on template-templates/config-wb-mai6.json.jinja
> +{%- set types_with_gain = [0, 1, 3, 257] -%}
исправил

2022-10-28 13:57 UTC, ExplorerOL commented on template-templates/config-wb-mai6.json.jinja
> +        "max_read_registers": 4,
Так было в шаблоне маи11. Убрал ограничение, поставил 0.

2022-10-28 14:08 UTC, KraPete approved these changes

2022-10-29 14:50 UTC, sikmir approved these changes

2022-11-01 08:36 UTC, webconn reviewed
Добавил серию PR в компоненты, завязанные на конвенцию, чтобы добавить туда юниты `mA`, `mV`, `mOhm`. Можно здесь в `debian/control` добавить зависимость от `libwbmqtt1 (>= 3.9.0~~)` и использовать новые юниты

2022-11-07 07:21 UTC, KraPete commented
1. Нашёл багу в homeui https://wirenboard.bitrix24.ru/company/personal/user/134/tasks/task/view/54870/
2. Возможно, при создании таких шаблонов через jinja, стоит делать именованные константы для режимов? Проще для понимания. Сейчас не прошу так делать, но, думаю, стоит озвучить для всех, кто разрабатывает шаблоны.

2022-11-07 09:36 UTC, KraPete commented
3. Может, так сделаем?

![изображение](https://user-images.githubusercontent.com/86825564/200276699-54c4234f-6a1b-40f3-9d07-c1c2cdc63d57.png)

Не будет панелей вокруг N и P. Могу ещё сделать, чтоб тип был во всю длину

2022-11-08 05:50 UTC, ExplorerOL commented
Мне больше с рамками нравится...

2022-11-11 09:49 UTC, webconn commented on template-templates/config-wb-mai6.json.jinja
> +                "units": "V",
Мы сюда милливольты не хотели? Или уже не надо?
Про миллиомы то же самое

2022-11-11 09:55 UTC, KraPete approved these changes

2022-11-11 09:59 UTC, sikmir approved these changes

2022-11-11 11:05 UTC, evgeny-boger commented on template-templates/config-wb-mai6.json.jinja
> +                "units": "V",
нет, нет

2022-11-16 06:55 UTC, Boris-wb approved these changes

2022-11-16 06:55 UTC, webconn approved these changes

2022-11-16 08:26 UTC, ExplorerOL commented
Чек-лист проверок при создании нового или редактировании существующего шаблона
--
 1. Согласовать с разработчиком устройства список необходимых общих регистров и служебных каналов (регистров), их видимость - сделано.
 2. Согласовать внешний вид шаблона в веб-интерфейсе (с кем?). 
 3. Проверить наличие перевода на русский язык - сделано.
 4.  Проверить отсутствие ошибок и предупреждений в логах при использовании шаблона 
     сообщения INFO от wb-rules "failed to convert value '', passing raw, error: This control is incomplete". Задан вопрос разработчикам.
 5. Проверить безошибочную запись всех параметров в устройство - сделано.
 6. Проверить наличие общих для всех устройств каналов в группах HW_Info, General - сделано.
 7. Получить аппрув PR шаблона от разработчика устройства на гитхаб (Борис) - сделано 
 8. Получить аппрув PR от программиста на гитхаб (Петр) - сделано

2022-11-16 12:50 UTC, closed without merging