Added support for min_read_registers option
wirenboard/wb-mqtt-serial pull request #538
Opened 2022-11-17 17:32 UTC by sikmir

2022-11-18 04:53 UTC, KraPete requested changes
На это всё надо тест

2022-11-18 04:53 UTC, KraPete commented on src/modbus_common.cpp
> +            Count = deviceConfig.MinReadRegisters;
По смыслу это константная функция, она не должна менять состояние объекта.
Эту проверку надо переносить глубже в `ComposeReadRequestPDU` или вообще в `GetQuantity`

2022-11-18 04:53 UTC, KraPete commented on src/modbus_common.cpp
> +            Count = deviceConfig.MinReadRegisters;
Плюс это надо делать в `GetResponseSize`.
Сейчас получается, что, если вызвать `GetResponseSize` раньше чем `GetRequest`, вычисленный размер ответа будет меньше. Потому тебе и пришлось двигать инициализацию буфера. Потенциально кто-то потом наступит на эти грабли.

2022-11-18 06:20 UTC, sikmir commented on src/modbus_common.cpp
> +            Count = deviceConfig.MinReadRegisters;
> По смыслу это константная функция, она не должна менять состояние объекта. Эту проверку надо переносить глубже в `ComposeReadRequestPDU` или вообще в `GetQuantity`

Поправил константность, в том числе `GetRequest` теперь const.

2022-11-18 06:28 UTC, sikmir commented on src/modbus_common.cpp
> +            Count = deviceConfig.MinReadRegisters;
> Плюс это надо делать в `GetResponseSize`. Сейчас получается, что, если вызвать `GetResponseSize` раньше чем `GetRequest`, вычисленный размер ответа будет меньше. Потому тебе и пришлось двигать инициализацию буфера. Потенциально кто-то потом наступит на эти грабли.

`GetResponseSize` по смыслу тоже const все таки. Сейчас вынес выставление `Count` в `ReadRange`, перед вызовами `GetRequest` и `GetResponseSize`, так более понятно должно быть.

2022-11-18 06:32 UTC, KraPete commented on src/modbus_common.cpp
> +            if (GetCount() < deviceConfig.MinReadRegisters) {
Всё равно мне это не очень нравится. После чтения число регистров в интервале произвольно увеличивается.

2022-11-21 11:24 UTC, sikmir commented
От @evgeny-boger:
> предлагаю добавить с уровнем debug сообщение о том, что из-за ограничений времени читается меньше регистров, чем могло бы быть и в нём же формулу расчёта.

2022-11-21 12:10 UTC, sikmir commented on src/modbus_common.cpp
> +            if (GetCount() < deviceConfig.MinReadRegisters) {
Можем возвращать `Count` обратно по выходу из `ReadRange`, задвигать это в `GetQuantity` или куда-то еще выглядит тоже не хорошо.

2022-11-22 11:15 UTC, KraPete requested changes

2022-11-22 11:15 UTC, KraPete commented on src/modbus_common.cpp
> +        } else if (newPollTime <= pollLimit) {
Зачем писать else, если и так вверху return?

2022-11-22 11:15 UTC, KraPete commented on src/modbus_common.cpp
> +            LOG(Debug) << "Poll time for " << reg->ToString() << " is too long: " << newPollTime.count() << " ms"
Кажется, что эта строка будет сыпаться раз в 100мс, т.е. всегда. Оно надо в таком виде?

2022-11-22 11:15 UTC, KraPete commented on test/serial_config_test.cpp
> +                Emit() << "MinReadRegisters: " << device_config->MinReadRegisters;
Надо добавить конфиг, где этот параметр отличен от значения по умолчанию.

2022-11-22 11:15 UTC, KraPete commented on test/modbus_expectations.cpp
> +void TModbusExpectations::EnqueueHoldingReadU16Max3ReadResponse(uint8_t exception)
Почему такое странное название у функции?

2022-11-22 11:15 UTC, KraPete commented on test/modbus_test.cpp
> +    EXPECT_EQ(registerList.size(), 1);
Тут бы ещё значение регистра проверить.

2022-11-22 12:57 UTC, sikmir commented on test/modbus_expectations.cpp
> +void TModbusExpectations::EnqueueHoldingReadU16Max3ReadResponse(uint8_t exception)
поправил

2022-11-22 20:38 UTC, sikmir commented on test/modbus_test.cpp
> +    EXPECT_EQ(registerList.size(), 1);
добавил

2022-11-22 20:38 UTC, sikmir commented on src/modbus_common.cpp
> +        } else if (newPollTime <= pollLimit) {
убрал

2022-11-23 03:44 UTC, sikmir commented on src/modbus_common.cpp
> +            LOG(Debug) << "Poll time for " << reg->ToString() << " is too long: " << newPollTime.count() << " ms"
Зависит от конфига, может и ни разу не попадать.

2022-11-23 06:04 UTC, sikmir commented on src/modbus_common.cpp
> +            LOG(Debug) << "Poll time for " << reg->ToString() << " is too long: " << newPollTime.count() << " ms"
А вообще сейчас в debug и так много всего сыпется на каждый цикл опроса начиная с Write/ReadFrame, так что оставлять с включенным debug логгингом надолго идея сомнительная, а для кратковременного включения при отладке как раз хорошо бы видеть как можно больше подробностей.
Ну и кстати на стенде с одним частотником в это место ни разу не попадает, после поправки в темплейте.

2022-11-23 06:36 UTC, sikmir commented on test/serial_config_test.cpp
> +                Emit() << "MinReadRegisters: " << device_config->MinReadRegisters;
добавил

2022-11-23 08:11 UTC, KraPete commented on src/modbus_common.cpp
> +            LOG(Debug) << "Poll time for " << reg->ToString() << " is too long: " << newPollTime.count() << " ms"
Оно вообще выводится? У тебя получалось увидеть это сообщение?

2022-11-23 10:28 UTC, sikmir commented on src/modbus_common.cpp
> +            LOG(Debug) << "Poll time for " << reg->ToString() << " is too long: " << newPollTime.count() << " ms"
Да, вот например:
```
<7>DEBUG: [modbus] Poll time for <modbus:1:holding: 3> is too long: 122 ms (sendTime=22 ms, AverageResponseTime=15430 ms, RequestDelay=5000 ms, FrameTimeout=40 ms), limit is 100 ms
```

2022-11-23 11:01 UTC, KraPete approved these changes

2022-11-23 11:53 UTC, merged