Feature/51232 add a check for prohibited characters in
wirenboard/wb-mqtt-serial pull request #539
Opened 2022-11-17 20:29 UTC by rkochkin

* Добавил регулярные выражения в схемы для проверки отсутствия запрещённых символов,
а именно: `'#$/"+` для  `name` и `id` опций устройства и канала.
* Добавил в генератор шаблонов dlms замену в имени/id канала запрещённых в mqtt символов.

2022-11-18 03:08 UTC, sikmir commented on src/common_utils.cpp
> +                validStr.append(1, '|');
```suggestion
                validStr += '|';
```

2022-11-18 03:13 UTC, sikmir commented on templates/config-vacon10.json
> +                "name": "Output frequency (_plus_|- Hz)",
А в UI пользователь теперь будет видеть  `_plus_`  вместо  `+`?

2022-11-18 05:15 UTC, KraPete requested changes

2022-11-18 05:15 UTC, KraPete commented on src/common_utils.cpp
> +            case '\'':
`std::unordered_map`?

2022-11-18 05:15 UTC, KraPete commented on src/common_utils.h
> +    std::string ConvertToMqttTopicValidString(const std::string& src);
Надо коментарий

2022-11-18 05:15 UTC, KraPete commented on src/devices/dlms_device.cpp
>          Json::Value res;
Тут надо делать дополнительно `title` с исходным текстом

2022-11-18 05:15 UTC, KraPete commented on templates/config-vacon10.json
> +                "name": "Output frequency (_plus_|- Hz)",
Тут надо `title`.
Судя по всему, этот шаблон никто никогда не использовал. На этом месте wb-mqtt-serial всегда будет выпадать с ошибкой. Значит, мы можем смело менять `name`. Надо найти того, кто делал шаблон, и обсудить, как можно это всё переназвать. Это относится ко всем исправления в этом шаблоне

2022-11-18 05:15 UTC, KraPete commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
Тут бы как-то более гибко заменять. Например,  на `Active positive power`. Надо с коллегами по поводу терминологи посоветоваться

2022-11-18 06:55 UTC, rkochkin commented on src/common_utils.cpp
> +            case '\'':
Да, спасибо. Стало нагляднее.

2022-11-18 06:55 UTC, rkochkin commented on src/common_utils.cpp
> +                validStr.append(1, '|');
Поправил

2022-11-18 06:57 UTC, rkochkin commented on templates/config-vacon10.json
> +                "name": "Output frequency (_plus_|- Hz)",
> А в UI пользователь теперь будет видеть `_plus_` вместо `+`?

Да, не очень красиво получается. Может во что-то другое преобразовать?

2022-11-18 07:00 UTC, rkochkin commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
Да, согласен, что `Active positive power` лучше. Я сделал как выдал бы генератор dlms с автокоррекцией.

Если для этих dlms шаблонов генератор не будет использован повторно, то лучше отредактировать шаблоны, конечно.

2022-11-18 07:06 UTC, rkochkin commented on templates/config-vacon10.json
> +                "name": "Output frequency (_plus_|- Hz)",
> Надо найти того, кто делал шаблон, и обсудить, как можно это всё переназвать. Это относится ко всем исправления в этом шаблоне

Первоначально добавил шаблон @evgeny-boger, судя по истории. 
Да, шаблон создавался руками. Нужно просто переписать фрагменты с запрещёнными символами

2022-11-18 07:08 UTC, KraPete commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
Эти трогать не будем. Можно это и в автозамены добавить, т.к. такой параметр может встречаться и в процессе сканирования.

2022-11-18 07:17 UTC, rkochkin commented on src/common_utils.h
> +    std::string ConvertToMqttTopicValidString(const std::string& src);
Добавил

2022-11-18 20:57 UTC, rkochkin commented on src/devices/dlms_device.cpp
>          Json::Value res;
Сделал так, чтобы исходный текст, если он не валидный попадал в `translations: {}`

2022-11-18 21:03 UTC, sikmir commented on src/common_utils.cpp
> +        }
```suggestion
        const auto it = ConvertToMqttStringMap.find(ch);
        validStr += it != ConvertToMqttStringMap.end() ? it->second : ch;
```

2022-11-21 08:03 UTC, rkochkin commented on src/common_utils.cpp
> +        }
Так не сработает: it->second и ch имеют разные типы. При компиляции возникает ошибка. 
Оставил как есть, код эквивалентен.

2022-11-22 04:34 UTC, KraPete commented on templates/config-vacon10.json
> +                "name": "Output frequency (plus|minus Hz)",
Я бы вообще убрал тут всё в скобках. А `Hz` перенёс в `units`

2022-11-22 04:34 UTC, KraPete commented on templates/config-vacon10.json
> +                "name": "Motor torque plus|minus % (of nom)",
Здесь бы оставить `Motor torque`

2022-11-22 04:34 UTC, KraPete commented on templates/config-vacon10.json
> +                "name": "Motor power plus|minus % (of nom)",
Тут тоже только `Motor power`

2022-11-22 04:35 UTC, KraPete commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
Это ещё актуально

2022-11-22 06:31 UTC, rkochkin commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
Добавить целую фразу "Ch. 0 Sum Li Active power+ (QI+QIV) Inst. value" в автозамену? А на что заменять? Мне не совсем понятно. Если каждую фразу нужно заменять другой фразой, то словарь очень сильно раздуется. Или я не так понял.

2022-11-22 06:48 UTC, KraPete commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
`Active power+` на `Active positive power` и проконсультироваться у коллег, что это корректно

2022-11-22 06:52 UTC, rkochkin commented on templates/config-vacon10.json
> +                "name": "Output frequency (plus|minus Hz)",
Если смотреть в https://github.com/wirenboard/conventions#units там нет частоты

2022-11-22 06:58 UTC, KraPete commented on templates/config-vacon10.json
> +                "name": "Output frequency (plus|minus Hz)",
Возможно, стоит добавить

2022-11-22 07:03 UTC, rkochkin commented on templates/config-vacon10.json
> +                "name": "Motor power plus|minus % (of nom)",
Сделал

2022-11-22 07:04 UTC, rkochkin commented on templates/config-vacon10.json
> +                "name": "Motor torque plus|minus % (of nom)",
Оставил

2022-11-22 07:04 UTC, rkochkin commented on templates/config-vacon10.json
> +                "name": "Output frequency (plus|minus Hz)",
Сделал `"units": "Hz"`

2022-11-24 08:44 UTC, rkochkin commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
Мне не понятно как именовать каналы. 
Если из dlms устройства приходит `"Ch. 0 Sum Li Active power+ (QI+QIV) Inst. value"`, то для того, чтобы превратить на выходе это в: `"Ch. 0 Sum Li Active positive power (QI+QIV) Inst. value"` нужно держать в словаре пару: `"power+": "positive power"` Этих фраз может быть достаточно много, и все мне они не известны.
Сейчас сделано что если встречается запрещённый символ он меняется либо на не запрещённый символ, либо на слово.

2022-11-24 09:33 UTC, webconn commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
Так, а у нас из dlms контролы приходят не из нашего шаблона?

2022-11-24 09:37 UTC, webconn commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
Ага, осознал.

Ну тут вопрос скорее к опытным коллегам. Мне вот кажется, что если девайс отдаёт какие-то свои имена регистров, то надо их с минимальными искажениями отдать в нашу систему, чтобы потом при отладке не перепутать ничего и можно было бы поиском пользоваться. В title всё равно лучше написать то, что пришло, без модификаций.

В целом пока склоняюсь к решению @rkochkin с заменой символов по отдельности.

2022-11-24 09:39 UTC, rkochkin commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
А, всё понял. Они из gurux генерятся.

2022-11-24 10:11 UTC, rkochkin commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
Но нужно перебрать весь каталог OBIS кодов которые есть в gurux и сделать словарь. Это много и я не знаю как это поддерживать.

2022-11-24 10:33 UTC, webconn commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
@KraPete что думаешь про моё решение?

2022-11-24 15:58 UTC, KraPete commented on templates/config-energomera-ce308.json
> +        "name" : "Ch. 0 Sum Li Active power_plus_ (QI_plus_QIV) Inst. value",
Ну ок. Меня напрягало, что топики будут иметь странные названия. Если никто за полтора года не заинтресовался ими, пусть они и будут странными.

2022-11-24 15:59 UTC, KraPete approved these changes

2022-11-25 10:49 UTC, sikmir approved these changes

2022-11-25 12:56 UTC, merged