Feature/mr debounce
wirenboard/wb-mqtt-serial pull request #545
Opened 2022-11-21 12:51 UTC by nikitoz236

2022-11-22 09:58 UTC, ExplorerOL commented
Для WB-MR6CU/MRPS6 шаблона не хватает

2022-11-22 13:43 UTC, ExplorerOL reviewed
Думаю, что может быть конфликт со старыми параметрами для маппинг-матрицы в уже существующих файлах настроек wb-mqtt-serial.

2022-11-23 04:42 UTC, KraPete requested changes
Обсудили, что возможна ситуация с новым шаблоном и устройством со старой прошивкой. В результате клиент не сможет его настроить корректно, надо будет в логах копаться, чтобы понять, что прошивка не та.

2022-11-24 16:06 UTC, KraPete requested changes
А ещё сборка ругается так
```
C++ exception with description "Failed to parse JSON test/../build/templates/config-wb-mr3.json:* Line 2350, Column 46
```

2022-11-24 16:06 UTC, KraPete commented on templates/config-wb-mr3.json.jinja
> +                "debounce_time_description": "For press detection must be 5-10 times less than second press waiting time. Firmware up to 1.19.0 support maximum 250 ms"
support**S** и так везде

2022-11-25 09:06 UTC, KraPete approved these changes

2022-11-25 10:44 UTC, sikmir approved these changes

2022-11-27 06:32 UTC, nikitoz236 commented
> Для WB-MR6CU/MRPS6 шаблона не хватает
в них нет входов

2022-11-27 06:43 UTC, merged