Fix compiler warnings
wirenboard/wb-mqtt-serial pull request #548
Opened 2022-11-30 07:37 UTC by sikmir

```sh
wb-mqtt-serial> src/register.h:192:1: error: 'TRegisterConfig' defined as a class here but previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]
<...>
wb-mqtt-serial> src/devices/mercury230_device.h:36:10: error: 'ConnectionSetup' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
<...>
wb-mqtt-serial> src/devices/mercury230_device.h:37:15: error: 'CheckForException' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
<...>
wb-mqtt-serial> src/modbus_common.h:69:18: error: 'GetPDU' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
<...>
wb-mqtt-serial> src/devices/lls_device.cpp:69:19: error: unused variable 'RESPONSE_PREFIX' [-Werror,-Wunused-const-variable]
<...>
wb-mqtt-serial> src/devices/milur_device.h:31:10: error: 'ConnectionSetup' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
<...>
wb-mqtt-serial> src/devices/milur_device.h:32:15: error: 'CheckForException' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
<...>
wb-mqtt-serial> /nix/store/1gf2flfqnpqbr1b4p4qz2f72y42bs56r-gcc-11.3.0/include/c++/11.3.0/ext/new_allocator.h:168:4: error: destructor called on non-final 'TRPCSerialPort' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
<...>
wb-mqtt-serial> /nix/store/1gf2flfqnpqbr1b4p4qz2f72y42bs56r-gcc-11.3.0/include/c++/11.3.0/ext/new_allocator.h:168:4: error: destructor called on non-final 'TRPCTCPPort' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
<...>
wb-mqtt-serial> src/rpc_handler.cpp:174:48: error: lambda capture 'serialPortDriver' is not used [-Werror,-Wunused-lambda-capture]
<...>
wb-mqtt-serial> src/modbus_common.cpp:25:15: error: unused variable 'MAX_WRITE_BITS' [-Werror,-Wunused-const-variable]
<...>
wb-mqtt-serial> src/modbus_common.cpp:28:15: error: unused variable 'MAX_WRITE_REGISTERS' [-Werror,-Wunused-const-variable]
<...>
wb-mqtt-serial> src/modbus_common.cpp:29:15: error: unused variable 'MAX_RW_WRITE_REGISTERS' [-Werror,-Wunused-const-variable]
<...>
wb-mqtt-serial> src/register_handler.cpp:10:18: error: unused variable 'MAX_WRITE_FAILS' [-Werror,-Wunused-const-variable]
<...>
wb-mqtt-serial> src/main.cpp:99:54: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
wb-mqtt-serial>         auto configSchema = make_shared<Json::Value>(std::move(LoadConfigSchema(CONFIG_JSON_SCHEMA_FULL_FILE_PATH)));
wb-mqtt-serial>                                                      ^
wb-mqtt-serial> src/main.cpp:99:54: note: remove std::move call here
wb-mqtt-serial>         auto configSchema = make_shared<Json::Value>(std::move(LoadConfigSchema(CONFIG_JSON_SCHEMA_FULL_FILE_PATH)));
wb-mqtt-serial>                                                      ^~~~~~~~~~                                                   ~
wb-mqtt-serial> 1 error generated.
<...and other similar...>
```

2022-11-30 08:09 UTC, KraPete requested changes

2022-11-30 08:09 UTC, KraPete commented on src/devices/lls_device.cpp
> +    // const uint8_t RESPONSE_PREFIX = 0x3E;
Лучше заменить место, где явно число используется на эту константу

2022-11-30 08:09 UTC, KraPete commented on src/modbus_common.cpp
> +    // const int MAX_WRITE_BITS = 1968;
Лучше убрать совсем, если нигде не написано явно это число

2022-11-30 08:09 UTC, KraPete commented on src/modbus_common.cpp
> +    // const int MAX_WRITE_REGISTERS = 123;
Тут тоже лучше убрать

2022-11-30 08:09 UTC, KraPete commented on src/register_handler.cpp
> +    // const size_t MAX_WRITE_FAILS = 10;
Лучше убрать, если нигде не используется явно число

2022-11-30 08:09 UTC, KraPete commented on src/rpc_port.h
> +class TRPCSerialPort final: public TRPCPort
Может, деструкторы нормально виртуальные сделаем вместо этого?

2022-11-30 08:09 UTC, KraPete commented on src/rpc_port.h
> +class TRPCTCPPort final: public TRPCPort
Может, деструкторы нормально виртуальные сделаем вместо этого?

2022-11-30 08:51 UTC, sikmir commented on src/devices/lls_device.cpp
> +    // const uint8_t RESPONSE_PREFIX = 0x3E;
Насколько вижу нигде не используется

2022-11-30 10:04 UTC, KraPete commented on src/devices/lls_device.cpp
> +    // const uint8_t RESPONSE_PREFIX = 0x3E;
Используется

2022-11-30 12:43 UTC, sikmir commented on src/rpc_port.h
> +class TRPCTCPPort final: public TRPCPort
ок, добавил dtor

2022-11-30 12:43 UTC, sikmir commented on src/rpc_port.h
> +class TRPCSerialPort final: public TRPCPort
ок, добавил dtor

2022-11-30 12:43 UTC, sikmir commented on src/register_handler.cpp
> +    // const size_t MAX_WRITE_FAILS = 10;
removed

2022-11-30 12:43 UTC, sikmir commented on src/modbus_common.cpp
> +    // const int MAX_WRITE_REGISTERS = 123;
removed

2022-11-30 12:43 UTC, sikmir commented on src/modbus_common.cpp
> +    // const int MAX_WRITE_BITS = 1968;
removed

2022-11-30 12:47 UTC, sikmir commented on src/devices/lls_device.cpp
> +    // const uint8_t RESPONSE_PREFIX = 0x3E;
Точно, у меня поиск case sensitive и я искал `0x3E` или `62`, а оно встречается как `0x3e`.

2022-11-30 13:56 UTC, KraPete commented on src/rpc_port.h
> +    virtual ~TRPCSerialPort() = default;
А это не про то, что в базовом классе деструктор не виртуальный?

2022-12-01 07:22 UTC, sikmir commented on src/rpc_port.h
> +    virtual ~TRPCSerialPort() = default;
Да, конечно, не туда добавил. Поправил.

2022-12-01 07:30 UTC, KraPete approved these changes

2022-12-01 07:31 UTC, merged