Feature/msw add debug co2 regs
wirenboard/wb-mqtt-serial pull request #552
Opened 2022-12-16 10:27 UTC by pgasheev

Работает с прошивкой 4.25.0

2022-12-16 11:43 UTC, KraPete requested changes

2022-12-16 11:43 UTC, KraPete commented on templates/config-wb-msw_v3.json
> +                "name": "CO2 MH-Z19 Autocalibration Ticks (1 unit is ~7.5 min)",
Давай, сделаем `name` = `CO2 MH-Z19 Autocalibration Ticks`, а весь текст с `(1 unit is ~7.5 min)` перенесём в переводы, тогда оно в имя MQTT-топика не попадёт

2022-12-16 11:43 UTC, KraPete commented on templates/config-wb-ms_v2.json
> +                "units": "ppb",
Сделай, пожалуйста, нам историю, про добавление ppb в единицы измерения, а то `wb-mqtt-serial` будет в лог ошибки сыпать, что это неизвестный тип

2022-12-16 12:28 UTC, pgasheev commented on templates/config-wb-ms_v2.json
> +                "units": "ppb",
Готово https://wirenboard.bitrix24.ru/workgroups/group/218/tasks/task/view/56610/

2022-12-16 12:36 UTC, pgasheev commented on templates/config-wb-msw_v3.json
> +                "name": "CO2 MH-Z19 Autocalibration Ticks (1 unit is ~7.5 min)",
Сделал, для соседних каналов тоже добавил перевод аналогично существующим

2022-12-16 13:34 UTC, KraPete approved these changes

2022-12-16 20:23 UTC, sikmir approved these changes

2022-12-20 14:12 UTC, nikitoz236 approved these changes

2022-12-21 15:38 UTC, merged