Update README.md
wirenboard/wb-mqtt-serial pull request #556
Opened 2023-01-19 12:11 UTC by matveevrj

Исправил некоторые опечатки в разделе шаблонов конфигурации, добавил пояснения для чего это нужно и как создать свой шаблон.

2023-01-19 13:07 UTC, KraPete requested changes

2023-01-31 14:42 UTC, KraPete approved these changes

2023-02-01 05:54 UTC, KraPete approved these changes

2023-02-01 12:07 UTC, aadegtyarev requested changes
В целом ок, в одном месте надо поправить.

2023-02-01 12:07 UTC, aadegtyarev commented on README.md
> +В состав пакета изначально входят шаблоны конфигурации некоторых поддерживаемых устройств. Они хранятся в папке `/usr/share/wb-mqtt-serial/templates`. Для хранения пользовательских шаблонов используе
Давай уточним:
`Они хранятся на контроллере в папке`

2023-02-01 13:41 UTC, aadegtyarev approved these changes

2023-02-01 13:53 UTC, merged