Feature/56382 mao4 template add buttons
wirenboard/wb-mqtt-serial pull request #564
Opened 2023-02-17 04:39 UTC by yayayat

* Шаблон переделан из json в jinja
* Повторяющиеся куски засунул в for
* Добавлены 8 групп регистров для подсчета различных типов нажатий и настройки их детектирования

2023-02-17 04:56 UTC, KraPete commented
1. Надо сделать запись в Changelog
2. Если добавились регистры, надо добавить их в тест

2023-02-17 05:52 UTC, KraPete requested changes
Ты добавил регистры, их надо описать в тесте в TDeviceTemplatesTest.Validate.dat

2023-02-17 07:40 UTC, sikmir commented
```diff
--- test/TDeviceTemplatesTest.Validate.dat	2023-02-17 04:59:34.000000000 +0000
+++ test/TDeviceTemplatesTest.Validate.dat.out	2023-02-17 05:03:36.314871418 +0000
@@ -12935,10 +12935,22 @@
 	FW Version  =>  FW Version
 	Input 1  =>  Input 1
 	Input 1 counter  =>  Input 1 counter
+	Input 1 double press counter  =>  Input 1 double press counter
+	Input 1 long press counter  =>  Input 1 long press counter
+	Input 1 short long press counter  =>  Input 1 short long press counter
+	Input 1 short press counter  =>  Input 1 short press counter
 	Input 2  =>  Input 2
 	Input 2 counter  =>  Input 2 counter
+	Input 2 double press counter  =>  Input 2 double press counter
+	Input 2 long press counter  =>  Input 2 long press counter
+	Input 2 short long press counter  =>  Input 2 short long press counter
+	Input 2 short press counter  =>  Input 2 short press counter
 	Input 3  =>  Input 3
 	Input 3 counter  =>  Input 3 counter
+	Input 3 double press counter  =>  Input 3 double press counter
+	Input 3 long press counter  =>  Input 3 long press counter
+	Input 3 short long press counter  =>  Input 3 short long press counter
+	Input 3 short press counter  =>  Input 3 short press counter
 	MCU Temperature  =>  MCU Temperature
 	MCU Voltage  =>  MCU Voltage
 	Serial  =>  Serial
```

2023-02-21 04:34 UTC, sikmir approved these changes

2023-02-21 04:48 UTC, KraPete approved these changes

2023-02-21 08:33 UTC, nikitoz236 approved these changes

2023-02-21 08:39 UTC, merged