Add noise skipping before Modbus requests
wirenboard/wb-mqtt-serial pull request #576
Opened 2023-03-24 16:02 UTC by KraPete

Встречаются устройства, которые шлют лишние байты после ответа на modbus запрос. Вычитываем буфер перед каждым новым запросом
```
Mar 24 18:20:28 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 9000 us
Mar 24 18:20:28 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] ReadFrame: b0 01 03 02 00 19 79
Mar 24 18:20:28 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] read noise:  8e b0
Mar 24 18:20:28 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: WARNING: [modbus] failed to read 1 holding(s) @ 10032 of device modbus:01: Serial protocol error: malformed response: invalid crc
Mar 24 18:20:29 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 400000 us
Mar 24 18:20:29 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Write: 01 03 27 35 00 01 9e b0
Mar 24 18:20:29 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 9000 us
Mar 24 18:20:29 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] ReadFrame: 01 03 02 00 01 79 84
Mar 24 18:20:29 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 400000 us
Mar 24 18:20:29 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Write: 01 03 27 2e 00 01 ee b7
Mar 24 18:20:29 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 9000 us
Mar 24 18:20:29 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] ReadFrame: b0 01 03 02 00 11 78
Mar 24 18:20:29 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] read noise:  48 b0
Mar 24 18:20:29 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: WARNING: [modbus] failed to read 1 holding(s) @ 10030 of device modbus:01: Serial protocol error: malformed response: invalid crc
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 400000 us
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Write: 01 03 27 30 00 01 8e b1
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 9000 us
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] ReadFrame: 01 03 02 00 19 79 8e
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 400000 us
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Write: 01 03 27 35 00 01 9e b0
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 9000 us
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] ReadFrame: b0 01 03 02 00 01 79
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] read noise:  84 b0
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: WARNING: [modbus] failed to read 1 holding(s) @ 10037 of device modbus:01: Serial protocol error: malformed response: invalid crc
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 400000 us
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Write: 01 03 27 2e 00 01 ee b7
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 9000 us
Mar 24 18:20:30 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] ReadFrame: 01 03 02 00 11 78 48
Mar 24 18:20:31 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 400000 us
Mar 24 18:20:31 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Write: 01 03 27 30 00 01 8e b1
Mar 24 18:20:31 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 9000 us
Mar 24 18:20:31 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] ReadFrame: b0 01 03 02 00 19 79
Mar 24 18:20:31 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] read noise:  8e b0
Mar 24 18:20:31 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: WARNING: [modbus] failed to read 1 holding(s) @ 10032 of device modbus:01: Serial protocol error: malformed response: invalid crc
Mar 24 18:20:31 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 400000 us
Mar 24 18:20:31 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Write: 01 03 27 35 00 01 9e b0
Mar 24 18:20:31 wirenboard-HCB18W10AA000248 wb-mqtt-serial[592]: DEBUG: [port] Sleep 9000 us
```

2023-03-24 16:14 UTC, evgeny-boger commented on src/file_descriptor_port.cpp
> +void TFileDescriptorPort::SkipNoise(TPort::TSkipNoiseTimeoutPolicy timeoutPolicy)
может просто передавать таймаут явно? Кажется понятнее будет

2023-03-27 10:24 UTC, KraPete commented on src/file_descriptor_port.cpp
> +void TFileDescriptorPort::SkipNoise(TPort::TSkipNoiseTimeoutPolicy timeoutPolicy)
Переделал

2023-03-28 17:57 UTC, evgeny-boger commented
там мой кривой бекпорт у клиента не заработал, хорошо бы разорабться в чём дело, прежде чем вливать

2023-03-29 08:18 UTC, KraPete commented
> там мой кривой бекпорт у клиента не заработал, хорошо бы разорабться в чём дело, прежде чем вливать

Там блокирующий `select` получается, если `0us`.

2023-03-30 11:49 UTC, KraPete commented
Пока тестировал выяснились следующие нюансы:
1. Драйвер WB7 отдаёт в приложение куски по 32 байта. Если ожидание слишком маленькое, то мы можем не получить ничего от дравера и решить, что мусора больше нет.
2. Драйвер WB6 отдаёт данные по мере получения. Если ожидание слишком маленькое, мы можем не успеть получить первый байт или последующие байты мусора.

В результате:
1. Добавил задержку в 3.5 символа перед запросом. Это соответствует стандарту. Раньше мы слали запрос сразу после получения ответа. Теперь первый байт мусора на WB6 не пропускается.
2. Если получено несколько байт мусора, то таймаут ожидания устанавливается достаточным для получения всех данных из очереди (1 байт для WB6, 32 байта для WB7). Так будет вычитываться весь мусор.

Остаётся проблема на WB7. Если размер ответа кратен 32 байтам, время ожидания первого байта будет слишком мало и мусор не будет вычитан.

У клиента стоит задержка 400мс перед запросом, так что он не видит ничего, описанного выше.

2023-04-05 04:37 UTC, sikmir approved these changes

2023-04-05 09:39 UTC, KraPete commented
@webconn посмотри тоже, пожалуйста

2023-04-05 10:37 UTC, webconn commented on src/devices/milur_device.cpp
> +        if (!ReadResponse(0x08, buf, 1, ExpectNBytes(SlaveIdWidth, SlaveIdWidth + 4)))
Это как-то связано с изменениями в modbus? Проверялось как-то отдельно на устройствах? (в целом если это важно, то хочется тест-кейс про это, на какой железке и при каких условиях проверять)

2023-04-05 10:37 UTC, webconn commented on test/utils/noise-simulator.py
> +# Simulates sending extra noise bytes after modbus response
Тут бы побольше описания, как пользоваться этой утилитой, какая нужна инсталляция. Без этого, к сожалению, это будет потерянный кусок кода, который проще будет придумать заново

2023-04-05 10:37 UTC, webconn commented on test/modbus_test.cpp
> +    Config->PortConfigs[0]->Devices[0]->DeviceConfig()->RequestDelay = chrono::microseconds(10000);
Это реально нужно было, или мы так проверяем, что перегрузка и аргументы по умолчанию в С++ работает? :)

2023-04-05 10:46 UTC, evgeny-boger requested changes
> 1. Драйвер WB7 отдаёт в приложение куски по 32 байта

есть же rx_trig_bytes. Мы его как минимум уже читаем. Но можем и писать совершенно спокойно.

> Добавил задержку в 3.5 символа перед запросом

это регрессия, это очень плохо, это никогда не должно добавляться проходя мимо в несвязанном PR, это никогда не должно было пройти ревью и тесты. 

Изменение значительно увеличивает время опроса. 

Оно не добавляет никакой пользы клиентам, т.к. наши устройства такие запросы понимать умеют, а для чужих ожидание настраивается. 


По этому инциденту я бы очень хотел увидеть изменения в процессах и в тестах, которые сделали такое возможным.

2023-04-05 12:10 UTC, KraPete commented on src/devices/milur_device.cpp
> +        if (!ReadResponse(0x08, buf, 1, ExpectNBytes(SlaveIdWidth, SlaveIdWidth + 4)))
Нет. Это протокол милура. Но ты прав, надо снова перечитать доку на протокол и на железке запустить, т.к. раньше тест, вероятно, был не верным.

2023-04-05 12:10 UTC, KraPete commented on test/utils/noise-simulator.py
> +# Simulates sending extra noise bytes after modbus response
Это вообще не надо. Уберу

2023-06-05 12:30 UTC, webconn commented
Изначальная задача была в том, чтобы сбросить произвольный байт из конца пакета. Кажется, это надо заткнуть костылём попроще. Этот PR закрываю

2023-06-05 12:30 UTC, closed without merging