Feature/43874 mao4 events
wirenboard/wb-mqtt-serial pull request #577
Opened 2023-03-31 09:56 UTC by yayayat

Шаблон MAO4
* Добавлены настройки событий
* Добавлены выключатели выходов и ползунки для управления в процентах

2023-04-03 04:30 UTC, KraPete commented on templates/config-wb-mao4.json.jinja
> +                "Channel {{ch_number}} Duty Cycle Raw": "Сырое задание для канала {{ch_number}}",
Очень сложно понять, что за "Сырое задание для канала". С английским оно не бъётся, единиц иземерения нет. Я понимаю, что это уже было так. Но, может, как-то даработать?

2023-04-10 05:19 UTC, sikmir requested changes
Надо поправить тест, сейчас не проходит

2023-04-13 10:45 UTC, KraPete approved these changes

2023-05-04 06:21 UTC, aadegtyarev commented
Првоеряю документацию и начал пользоваться новым шаблоном. На вкладке Вход x на каждый параметр отводится по целой строке — это довольно расточительно. У нас в других шаблонах по два параметра в строке.

![изображение](https://user-images.githubusercontent.com/77433258/236125979-add61458-e016-4024-ad4d-9f13681a1570.png)

2023-05-04 06:24 UTC, aadegtyarev commented
Ещё почему-то настройки выходов вынесли в отдельную вкладку «Диммер» — это наверное, логично с точки зрения организации прошивки, но для для пользователя выглядит странно. Зачем так сделано?
![изображение](https://user-images.githubusercontent.com/77433258/236126362-d049787c-ecce-4bc7-aa05-20e24fda737d.png)

2023-05-04 06:29 UTC, aadegtyarev commented
Ещё в черновике докумнтации есть фраза

>Некоторые комбинации событий и действий, не имеют практического смысла и будут проигнорированы. 

А как понять, что нет практического смысла и оно будет проигнорировано? Может эти комбинации не давать выбирать шаблоном?


![изображение](https://user-images.githubusercontent.com/77433258/236126899-b626cd77-dfe6-4ed3-bfce-0470ba6a0150.png)

2023-05-04 06:38 UTC, aadegtyarev commented
В целом, парадигма назначения действий отличается от других наших устройств, например, WB-LED:
![изображение](https://user-images.githubusercontent.com/77433258/236127915-e0cc420a-28e0-4d86-898c-2d0e09f90c69.png)

и WB-MAO4:
![изображение](https://user-images.githubusercontent.com/77433258/236127970-e7d6634c-c36c-411e-828e-5358bdae7eab.png)

Субьективно кажется, что подход в WB-MAO4 удобнее — меньше полей в настройке. Как думаете, мы можем так же сделать в WB-LED?

2023-05-04 08:06 UTC, aadegtyarev commented
Непонятки с параметром **Верхний порог диммирования выхода**

В документации написано (хорошо бы написать также и в шаблоне):
> Верхний порог диммирования — Значение выхода в мВ, соответствующее уровню 100%.

Я понял это так: настройка ограничивает максимальное напряжение на выходе. То есть, если я поставил значение 100 мВ, то у меня должно быть на выходе при ползунке в 100 % 100 мВ.

Что я вижу: 
1. Режим выхода аналоговые 10 В.
2. Верхний порог диммирования выхода — 100 мВ.
3. В ползунке можно выкрутить до 10 000 пунктов — зачем так? Там разве не должно быть от 0 до 100%?
4. Ну и на выходе у меня при максимальном значение ползунка 10 В.

![изображение](https://user-images.githubusercontent.com/77433258/236145934-2bebf74c-4b04-43db-89d3-06b5a63459e4.png)

![изображение](https://user-images.githubusercontent.com/77433258/236145805-229ec72a-fd1e-4944-8e4b-336446f85e14.png)

2023-05-05 12:22 UTC, yayayat commented
>  _На вкладке Вход x на каждый параметр отводится по целой строке — это довольно расточительно. У нас в других шаблонах по два параметра в строке._

Во втором столбце находятся параметры с условием видимости в зависимости от выбранного пункта в первом столбце.

---

> _Настройки выходов вынесли в отдельную вкладку «Диммер» — это наверное, логично с точки зрения организации прошивки, но для для пользователя выглядит странно._

Диммер - это сущность реализация которой в разных формах встречается в разных прошивках. Чтобы не плодить эти формы и прийти к унификации, мы решили оформить это в виде библиотечного модуля с универсальной логикой работы, которая подходит для любого устройства. Пока ее планируется внедрить в MDM3, возможно LED. Парадигма изолированности всех подсистем подразумевает, что диммер никак не может лезть в подсистему выходов и управляет ими через тот же интерфейс, что и пользователь. С точки зрения шаблона это выливается в то, что вкладка Диммер будет одинаковая для всех шаблонов, разница будет только в количестве каналов.

---

> Ещё в черновике докумнтации есть фраза
>
> >Некоторые комбинации событий и действий, не имеют практического смысла и будут проигнорированы.
>
> А как понять, что нет практического смысла и оно будет проигнорировано? 

Таблица "Доступные комбинации событий и действий" проясняет именно этот вопрос

>Может эти комбинации не давать выбирать шаблоном?

Шаблон и так не допускает такие комбинации, это пояснение относится способу настройки через modbus_client и т.п.

---

> Субьективно кажется, что подход в WB-MAO4 удобнее — меньше портянка выбора действий. Как думаете, мы можем так же сделать в WB-LED?

Когда обсуждали привязку событий к действиям, пришли к выводу, что портянка WB-LED действительно сильно перегружена и решили разбить ее на две настройки. Этот подход реализован не в самой прошивке MAO4, а в библиотечном модуле. Постепенно планируется унифицировать привязку кнопок к событиям в модулях с похожим функционалом.

---

> Непонятки с параметром **Верхний порог диммирования выхода**
> 
> В документации написано (хорошо бы написать также и в шаблоне):
> 
> > Верхний порог диммирования — Значение выхода в мВ, соответствующее уровню 100%.
> 
> Я понял это так: настройка ограничивает максимальное напряжение на выходе. То есть, если я поставил значение 100 мВ, то у меня должно быть на выходе при ползунке в 100 % 100 мВ.
> 
> Что я вижу:
> 
> 1. Режим выхода аналоговые 10 В.
> 2. Верхний порог диммирования выхода — 100 мВ.
> 3. В ползунке можно выкрутить до 10 000 пунктов — зачем так? Там разве не должно быть от 0 до 100%?
> 4. Ну и на выходе у меня при максимальном значение ползунка 10 В.
> 
> Я ожидаю, что оно будет работать по аналогии с другими устройствами: ограничили напряжение на выходе и вся шкала пересчиталась, но осталась от 0 до 100 %.

Все что находится во вкладке "Диммер" относится только к диммеру и никак не влияет на работу подсистемы выходов. 

Параметры для настройки порогов диммирования задают диммеру диапазон значений в "попугаях", которые он будет передавать подсистеме выходов.

Ползунок "Канал" не имеет отношения к диммеру. Его может крутить пользователь, а может крутить подсистема диммера. Это оставляет возможность для пользователей, которые не хотят замарачиваться с настройкой диммера и привязки событий, просто настроить два параметра во вкладке выходы и напрямую задавать значение в милливольтах.


> Заголовок **Действие, для короткого нажатия на канале 1** длиный и не имеет смысла, тут лучше писать просто **Действие для короткого нажатия** . А какой это вход понятно из контекста — мы же выбрали его слева.

Согласен, исправлю. Там еще где-то была похожая избыточность. Короче говоря, идею понял, проработаю.

2023-05-05 12:32 UTC, aadegtyarev commented
> С точки зрения шаблона это выливается в то, что вкладка Диммер будет одинаковая для всех шаблонов, разница будет только в количестве каналов.

Не согласен. Как пользователю, мне без разницы. как устроена кухня внутри прошивки. У меня есть вкладки «Вход N» и там же я ищу настройки входов.

>Все что находится во вкладке "Диммер" относится только к диммеру и никак не влияет на работу подсистемы выходов.
>Параметры для настройки порогов диммирования задают диммеру диапазон значений в "попугаях", которые он будет передавать подсистеме выходов.
>Ползунок "Канал" не имеет отношения к диммеру. Его может крутить пользователь, а может крутить подсистема диммера. Это оставляет возможность для пользователей, которые не хотят замарачиваться с настройкой диммера и привязки событий, просто настроить два параметра во вкладке выходы и напрямую задавать значение в милливольтах.

С этим тоже не согласен: разное поведение с кнопок и в веб-интерфейсе — плохо.

2023-05-22 12:15 UTC, aadegtyarev reviewed
Стало лучше, но почему-то мы совсем ушли в именах контролов и параметров от термина «Канал», а ведь у нас везде именно так называется Выход.

Комменты оставил, предлагаю поправить, там недолго: название самих каналов и переводы. Мы ведь новый шаблон делаем для устройства?

2023-05-22 12:15 UTC, aadegtyarev commented on templates/config-wb-mao4.json.jinja
> +                "Input {{ch_number}} Short Long Press Counter": "Счетчик короткого, а затем долгого нажатия {{ch_number}}",
Давай сделаем, как в WB-LED
```
Счетчик коротких нажатий входа 1
Счетчик длинных нажатий входа 1
Счетчик двойных нажатий входа 1
Счетчик коротких, а затем длинных нажатий входа 1
```

2023-05-22 12:15 UTC, aadegtyarev commented on templates/config-wb-mao4.json.jinja
> +                "Short Long Press Action": "Действие, для короткого, затем длинного нажатия",
Кажется, запятая после «Действие лишнии», надо просто:
`Действие для короткого нажатия`
`Действие для ...`

2023-05-22 12:15 UTC, aadegtyarev commented on templates/config-wb-mao4.json.jinja
> +                "Dimming level increment rate (ms/%)": "Скорость возрастания уровня диммирования (мс/%)",
Тут тоже не клеится с другми устройствами, там у нас:
```
Нижний порог диммирования
Верхний порог диммирования
Время уменьшения значения с 0 до 100% в мс << Возможно, тут лучше написать с 100 до 0%
Время увеличения значения c 0 до 100% в мс
```

2023-05-22 12:15 UTC, aadegtyarev commented on templates/config-wb-mao4.json.jinja
> +                "level_100_voltage_description": "Задает границу диапазона напряжения, соответствующую 1% уровня диммирования",
Должно быть 100%

2023-05-23 12:55 UTC, yayayat commented on templates/config-wb-mao4.json.jinja
> +                "Dimming level increment rate (ms/%)": "Время увеличения значения на 1 % в (мс)",
Тут не написал с 0 до 100. Оно задает сколько времени в мс уходит на изменение уровня на 1%, не от 0% до 100%

2023-05-24 17:03 UTC, aadegtyarev reviewed
Что-то у меня на этой версии шаблона, которую я поставил пакетом с wb-matt-serial из артефактов сборки не работает управление по одинарному нажатию. Подробности пришлю в телеграм.

2023-05-26 05:17 UTC, KraPete approved these changes

2023-05-26 05:17 UTC, KraPete commented on templates/config-wb-mao4.json.jinja
> +                "Dimming level decrement rate (ms/%)": "Время уменьшения значения на 1 % (мс)",
```suggestion
                "Dimming level decrement rate (ms/%)": "Время уменьшения значения на 1% (мс)",
```

2023-05-26 05:17 UTC, KraPete commented on templates/config-wb-mao4.json.jinja
> +                "Dimming level increment rate (ms/%)": "Время увеличения значения на 1 % в (мс)",
```suggestion
                "Dimming level increment rate (ms/%)": "Время увеличения значения на 1% в (мс)",
```

2023-05-26 06:38 UTC, sikmir approved these changes

2023-05-26 06:48 UTC, merged