Feature/msv4
wirenboard/wb-mqtt-serial pull request #580
Opened 2023-04-07 12:51 UTC by MaximTomchuk

Добавил шаблон для MSW v.4. Шаблон проверил.

2023-04-09 13:18 UTC, evgeny-boger approved these changes

2023-04-10 04:52 UTC, sikmir commented
Для сравнения с msv3:
```diff
diff -Naur templates/config-wb-msw_v3.json templates/config-wb-msw_v4.json
--- templates/config-wb-msw_v3.json	2023-04-07 17:50:27.000000000 +0400
+++ templates/config-wb-msw_v4.json	2023-04-10 08:49:05.000000000 +0400
@@ -1,14 +1,13 @@
 {
-    "title": "WB-MSW-v3_template_title",
-    "device_type": "WB-MSW v.3",
+    "title": "WB-MSW-v4_template_title",
+    "device_type": "WB-MSW v.4",
     "group": "g-wb",
     "device": {
-        "name": "WB-MSW v.3",
-        "id": "wb-msw-v3",
+        "name": "WB-MSW v.4",
+        "id": "wb-msw-v4",
         "max_read_registers": 0,
         "response_timeout_ms": 150,
         "frame_timeout_ms": 12,
-        "enable_wb_continuous_read": true,

         "groups": [
             {
@@ -79,40 +78,6 @@
                 "group": "air_quality",
                 "order": 2
             },
-            "co2_sensor_type": {
-                "id": "co2_sensor_type",
-                "title": "CO2 Sensor Type",
-                // "address": 83,
-                // "reg_type": "input",
-                "enum": [0, 1],
-                "enum_titles": ["MH-Z19B", "CM1106"],
-                "default": 0,
-                "group": "air_quality",
-                "order": 1,
-                "readonly": true
-            },
-            "co2_measurement_range": {
-                "title": "CO₂ Measurement Range (ppm)",
-                "description": "Only for MH-Z19B CO₂ sensor",
-                "address": 96,
-                "reg_type": "holding",
-                "enum": [2000, 5000, 10000],
-                "enum_titles": ["2000", "5000", "10000"],
-                "default": 5000,
-                "group": "air_quality",
-                "order": 3,
-                "condition": "co2_sensor_type==0"
-            },
-            "th_sensor_heater_enabled": {
-                "title": "TH Sensor Heater Enabled",
-                "address": 2,
-                "reg_type": "coil",
-                "enum": [0, 1],
-                "enum_titles": ["no", "yes"],
-                "default": 0,
-                "group": "air_quality",
-                "order": 4
-            },
             "selfheating_compensation_deg": {
                 "title": "Self-Heating Compensation (°C)",
                 "description": "selfheating_compensation_deg_description",
@@ -217,7 +182,6 @@
                 "units": "ppm",
                 "error_value": "0xFFFF",
                 "enabled": false,
-                "condition": "co2_sensor_type==1",
                 "group": "air_quality"
             },
             {
@@ -229,17 +193,15 @@
                 "units": "day",
                 "error_value": "0xFFFF",
                 "enabled": false,
-                "condition": "co2_sensor_type==1",
                 "group": "air_quality"
             },
             {
-                "name": "CO2 Force Calibration",
+                "name": "TH Sensor Heater Enabled",
+                "address": 2,
                 "reg_type": "coil",
-                "address": 1,
                 "type": "switch",
                 "enabled": false,
-                "group": "air_quality",
-                "condition": "co2_sensor_type==0"
+                "group": "air_quality"
             },
             {
                 "name": "Air Quality (VOC)",
@@ -1385,14 +1347,7 @@
                 "group": "hw_info"
             },
             {
-                "name": "Sound ADC Channel",
-                "reg_type": "input",
-                "address": 86,
-                "enabled": false,
-                "group": "debug"
-            },
-            {
-                "name": "Sound Low Gain ADC Raw",
+                "name": "Sound Gain ADC Raw",
                 "reg_type": "input",
                 "address": 100,
                 "scale": 0.0625,
@@ -1400,14 +1355,6 @@
                 "group": "debug"
             },
             {
-                "name": "Sound High Gain ADC Raw",
-                "reg_type": "input",
-                "address": 87,
-                "scale": 0.0625,
-                "enabled": false,
-                "group": "debug"
-            },
-            {
                 "name": "Sound dB Offset",
                 "reg_type": "holding",
                 "address": 93,
@@ -1454,29 +1401,6 @@
                 "group": "debug"
             },
             {
-                "name": "CO2 MH-Z19 Temperature",
-                "reg_type": "input",
-                "address": 393,
-                "units": "deg C",
-                "format": "s16",
-                "enabled": false,
-                "group": "debug"
-            },
-            {
-                "name": "CO2 MH-Z19 Autocalibration Ticks",
-                "reg_type": "input",
-                "address": 394,
-                "enabled": false,
-                "group": "debug"
-            },
-            {
-                "name": "CO2 MH-Z19 Autocalibration Count",
-                "reg_type": "input",
-                "address": 395,
-                "enabled": false,
-                "group": "debug"
-            },
-            {
                 "name": "VOC Sensor Installed",
                 "reg_type": "input",
                 "address": 371,
@@ -1550,7 +1474,7 @@
         ],
         "translations": {
             "en": {
-                "WB-MSW-v3_template_title": "WB-MSW v.3 (wall-mounted Modbus sensor)",
+                "WB-MSW-v4_template_title": "WB-MSW v.4 (wall-mounted Modbus sensor)",
                 "group_sound_level_title": "Sound Level",
                 "selfheating_compensation_deg_description": "Compensation value is subtracted from measured temperature",
                 "baud_rate_description": "Make sure that communication with device is established before changing this parameter. Select ,
@@ -1562,12 +1486,9 @@
                 "CO2 Sensor Installed": "CO₂ Sensor Installed",
                 "CO2 Sensor Type": "CO₂ Sensor Type",
                 "CO2 Sensor Software Version": "CO₂ Sensor Software Version",
-                "CO2 MH-Z19 Temperature": "CO₂ MH-Z19 Temperature",
-                "CO2 MH-Z19 Autocalibration Ticks": "CO₂ MH-Z19 Autocalibration Ticks (1 unit is ~7.5 min)",
-                "CO2 MH-Z19 Autocalibration Count": "CO₂ MH-Z19 Autocalibration Count"
             },
             "ru": {
-                "WB-MSW-v3_template_title": "WB-MSW v.3 (универсальный настенный Modbus-датчик)",
+                "WB-MSW-v4_template_title": "WB-MSW v.4 (универсальный настенный Modbus-датчик)",
                 "Air Quality": "Параметры воздуха",
                 "group_sound_level_title": "Шум",
                 "Illuminance": "Освещенность",
@@ -1725,10 +1646,6 @@
                 "CO2 Sensor Installed": "Датчик CO₂ установлен",
                 "CO2 Sensor Type": "Тип датчика CO₂",
                 "CO2 Sensor Software Version": "Версия ПО датчика CO₂",
-                "Only for MH-Z19B CO₂ sensor": "Только для CO₂ датчика MH-Z19B",
-                "CO2 MH-Z19 Temperature": "Температура CO₂ датчика MH-Z19B",
-                "CO2 MH-Z19 Autocalibration Ticks": "Время цикла автокалибровки CO₂ датчика MH-Z19B (1 ед. ~7.5 минут)",
-                "CO2 MH-Z19 Autocalibration Count": "Число циклов автокалибровки CO₂ датчика MH-Z19B",
                 "VOC Sensor Installed": "Датчик VOC установлен",
                 "VOC Version": "Версия датчика VOC",
                 "VOC Raw": "Сырое значение датчика VOC",
```

2023-04-10 04:57 UTC, sikmir requested changes
Еще тесты надо поправить.

2023-04-10 08:16 UTC, MaximTomchuk commented
Эти все изменения обсуждали в чате "WB документация".
>Я думаю, что там надо:
>1) Тип датчика CO2— убрать; 
>2) Включить подогрев датчика TH — убрать и заменить на обычный канал, регистра coil 2 и по умолчанию не >опрашивать.
>3) Наверное, сейчас тоже можно убрать, ну или оставить для информации, лучше спросить у программистов.
>4, 5, 6 — убрать.
4, 5, 6 - каналы с упоминанием MH-Z19B - его мы не будем ставить на MSW v.4. И двух ADC gain больше нет (схемотехнически).
Шаблон я проверял.

2023-04-10 15:19 UTC, vdromanov commented
починил тесты; поговорил с @MaximTomchuk - вроде бы все выпиливания в шаблоне - актуальны

2023-04-10 16:49 UTC, sikmir commented
Тесты снова не проходят

2023-04-12 09:28 UTC, sikmir approved these changes

2023-04-12 09:31 UTC, merged