Add ext modbus proto
wirenboard/wb-mqtt-serial pull request #591
Opened 2023-04-19 05:17 UTC by sikmir

Выделенная протокольная часть из https://github.com/wirenboard/wb-mqtt-serial/pull/587

2023-04-19 05:30 UTC, KraPete requested changes

2023-04-19 05:30 UTC, KraPete commented on src/modbus_ext_common.h
> +        typedef std::function<void(uint16_t, bool)> TVisitorFn;
Здесь нужен тип события

2023-04-19 05:30 UTC, KraPete commented on src/modbus_ext_common.cpp
> +                         static_cast<uint8_t>(std::ceil(maxEventsReadTime.count() / port.GetSendTime(1).count())));
Тут надо учитывать время запроса и арбитража. Так же при делении может получиться 0. А ещё можно подсунуть tcp-порт, который вообще вернёт 0, и будет деление на 0.

2023-04-19 05:30 UTC, KraPete commented on src/modbus_ext_common.cpp
> +                    const std::chrono::milliseconds& responseTimeout,
Насколько я понимаю, мы можем расчитать эти времна из параметров порта. Было бы идеально не передавать их вообще.

2023-04-19 05:30 UTC, KraPete commented on src/modbus_ext_common.cpp
> +        // const uint8_t* end = data + Response[ENABLE_EVENTS_RESPONSE_DATA_SIZE_POS];
Можно удалить

2023-04-19 05:30 UTC, KraPete commented on src/modbus_ext_common.h
> +                    const std::chrono::milliseconds& responseTimeout,
Насколько я понимаю, мы можем расчитать эти времена из параметров порта. Было бы идеально не передавать их вообще.

2023-04-19 05:30 UTC, KraPete commented on src/modbus_ext_common.h
> +                       const std::chrono::milliseconds& responseTimeout,
Тут тоже, вероятно, можно расчитать время.

2023-04-19 05:30 UTC, KraPete commented on src/modbus_ext_common.h
> +        const std::chrono::milliseconds& ResponseTimeout;
Нехорошо тут константную ссылку хранить. Может, это я налажал.

2023-04-20 04:43 UTC, sikmir commented on src/modbus_ext_common.h
> +        typedef std::function<void(uint16_t, bool)> TVisitorFn;
добавил

2023-04-20 04:58 UTC, KraPete commented
Ещё надо метод для отключения событий

2023-04-20 05:11 UTC, KraPete commented on src/modbus_ext_common.h
> +
Надо ещё дефайн для события перезагрузки, в доке оно уже есть

2023-04-20 19:50 UTC, sikmir commented on src/modbus_ext_common.h
> +
Добавил, и тест добавил

2023-04-20 19:51 UTC, sikmir commented on src/modbus_ext_common.h
> +        const std::chrono::milliseconds& ResponseTimeout;
Убрал

2023-04-20 21:58 UTC, sikmir commented
> Ещё надо метод для отключения событий

Отключение же ничем не отличается от включения, в `AddRegister` передать `TEventPriority::DISABLE`, вместо `TEventPriority::HIGH/TEventPriority::LOW`.

2023-04-21 03:49 UTC, KraPete commented on src/modbus_ext_common.h
> +
Тогда `enum` надо назвать иначе, это же уже не тип регистра

2023-04-21 03:58 UTC, KraPete commented on test/modbus_ext_common_test.cpp
> +    TPortMock port;
При чтении событий не должно быть такого исключения

2023-04-21 03:58 UTC, KraPete commented on test/modbus_ext_common_test.cpp
> +        ModbusExt::ReadEvents(port, std::chrono::milliseconds(100), std::chrono::milliseconds(100), visitor, state));
Я бы тут ещё проверил, что ReadEvents возвращает `false`

2023-04-21 03:58 UTC, KraPete commented on test/modbus_ext_common_test.cpp
> +        ModbusExt::ReadEvents(port, std::chrono::milliseconds(100), std::chrono::milliseconds(100), visitor, state));
Тут должно возвращать `true`

2023-04-21 03:58 UTC, KraPete commented on test/modbus_ext_common_test.cpp
> +    EXPECT_NO_THROW(
Тут тоже должно возвращать `true`

2023-04-21 04:50 UTC, sikmir commented on test/modbus_ext_common_test.cpp
> +    TPortMock port;
Фактически не должно, так как словим его уже на этапе настройки, но в целом при любом запросе надо быть готовым словить модбасное исключение (не только Illegal Function).

2023-04-21 05:00 UTC, sikmir commented on test/modbus_ext_common_test.cpp
> +    EXPECT_NO_THROW(
добавил

2023-04-21 05:00 UTC, sikmir commented on test/modbus_ext_common_test.cpp
> +        ModbusExt::ReadEvents(port, std::chrono::milliseconds(100), std::chrono::milliseconds(100), visitor, state));
добавил

2023-04-21 05:00 UTC, sikmir commented on test/modbus_ext_common_test.cpp
> +        ModbusExt::ReadEvents(port, std::chrono::milliseconds(100), std::chrono::milliseconds(100), visitor, state));
добавил

2023-04-21 05:01 UTC, sikmir commented on src/modbus_ext_common.h
> +
поправил

2023-04-21 05:02 UTC, KraPete commented on test/modbus_ext_common_test.cpp
> +    TPortMock port;
Это же запрос с арбиражем, там нет исключений

2023-04-21 08:56 UTC, sikmir commented on src/modbus_ext_common.cpp
> +        // const uint8_t* end = data + Response[ENABLE_EVENTS_RESPONSE_DATA_SIZE_POS];
теперь используется

2023-04-21 09:14 UTC, sikmir commented on test/modbus_ext_common_test.cpp
> +    TPortMock port;
хорошо, убрал этот тест

2023-04-25 05:36 UTC, KraPete approved these changes

2023-04-25 05:41 UTC, merged