Add fast modbus events polling with time limiting
wirenboard/wb-mqtt-serial pull request #594
Opened 2023-04-25 07:54 UTC by KraPete

2023-04-25 09:46 UTC, webconn commented on test/fake_serial_port.cpp
>      // 9600 8-N-2
Коммент уже не актуальный

2023-04-25 09:46 UTC, webconn commented on src/serial_device.cpp
> +            SetDisconnected();
Тут про `LastSuccessfulCycle` не потерялось?

2023-04-25 09:46 UTC, webconn commented on src/serial_client_events_reader.cpp
> +            // TODO: disable event
```suggestion
            // TODO: disable event on device
```

2023-04-25 09:46 UTC, webconn commented on src/serial_client_events_reader.cpp
> +            LOG(Info) << "Event on " << reg->second->ToString() << ", data: " << WBMQTT::HexDump(data, dataSize);
Давай в `debug`

2023-04-25 09:52 UTC, KraPete commented on src/modbus_ext_common.cpp
> +        // TODO: Count request and arbitration
Актуально. Ограничение на полный цикл запроса событий. Сейчас не учитывается время на запрос и арбитраж, будто всё время можно тратить на получение ответа.

2023-04-25 09:53 UTC, KraPete commented on src/modbus_ext_common.cpp
> +        if (timePerByte.count() == 0) {
Ты про что? Здесь проверка на 0. Не важно, какие единицы измерения

2023-04-25 09:54 UTC, KraPete commented on src/poll_plan.h
> +
Низя. Контейнер у `std::priority_queue` лежит в `protected`

2023-04-25 09:56 UTC, webconn commented on src/modbus_ext_common.cpp
> +        // TODO: Count request and arbitration
Допиши тогда сюда комментарий подробней, пожалуйста, а то без контекста непонятно

2023-04-25 09:58 UTC, webconn commented on src/modbus_ext_common.cpp
> +        if (timePerByte.count() == 0) {
А как там может быть ноль? Это если `GetSendTime` не реализована? Я глядя в код подумал, что тут так минимальное время высчитывается, если скорость сильно большая

2023-04-25 09:58 UTC, KraPete commented on src/poll_plan.h
> +class TTotalTimeBalancer
Это сумма времени, потраченного на что-то, с поверкой не превысила ли она заданную границу. К планировщику и приоритетам может и не иметь отношения. Нет никаких итерций и циклов.

2023-04-25 10:01 UTC, KraPete commented on src/serial_device.cpp
> +            SetDisconnected();
Оно было нужно, чтобы выводить самое первое после старта сообщение о том, что устройство отключено. Теперь вместо этого непонятного присвоения, явный флаг `ForceDisconnectionLogging`

2023-04-25 10:01 UTC, webconn commented on src/poll_plan.h
> +class TTotalTimeBalancer
Из этого объяснения непонятно, откуда тут тогда операция декремента и метод `GetTimeToDecrement`

2023-04-25 10:06 UTC, KraPete commented on src/modbus_ext_common.cpp
> +        if (timePerByte.count() == 0) {
У `TCP` порта `0`.

2023-04-25 10:14 UTC, webconn commented on src/modbus_ext_common.cpp
> +        if (timePerByte.count() == 0) {
okay

2023-04-25 10:14 UTC, KraPete commented on src/poll_plan.h
> +class TTotalTimeBalancer
Суммарное время может увеличиваться и уменьшаться.
Могу переименовать `GetTimeToDecrement` в что-нибудь типа `GetTimeOverflow`

2023-04-25 10:15 UTC, KraPete commented on src/modbus_ext_common.h
> +     */
Да. Убрал лишнее

2023-04-25 10:20 UTC, webconn commented on src/poll_plan.h
> +        if (TotalTime < OldTotalTime) { // Prevent overflow
Тогда сразу хочу уточнить, эта проверка условий так и задумывалась? Тут не MaxTotalTime должен был быть и знак наоборот? (то же самое ниже)

2023-04-25 10:22 UTC, KraPete commented on src/poll_plan.h
> +        if (TotalTime < OldTotalTime) { // Prevent overflow
Это переполнение типа, который хранит время. Стандартная библиотека не выполняет порверки на переполнение и просто прибаляет или вычитает.

2023-04-25 10:27 UTC, webconn commented on src/poll_plan.h
> +        if (TotalTime < OldTotalTime) { // Prevent overflow
Ага, окей. Наверное, если бы из кода следовало, что дельта всегда положительная, можно было бы догадаться :)

А на практике с этим были случаи? Нам не надо случайно уровнем выше трезвонить о том, что что-то пошло не так? Кажется, что переполнение тут будет в совсем неадекватных ситуациях

2023-04-25 11:08 UTC, KraPete commented on src/poll_plan.h
> +        if (TotalTime < OldTotalTime) { // Prevent overflow
Хотя нет. Может быть мало каких-то регистров и оно постепенно переполнится

2023-04-26 07:31 UTC, sikmir commented on src/serial_client_device_access_handler.cpp
> +                EventsReader.EnableEvents(dev, *(dev->Port()));
Если у девайса старая прошивка и он ничего не ответит в EnableEvents, то тут будем постоянно пытаться снова включить ивенты.

2023-04-26 08:38 UTC, KraPete commented on src/serial_client_device_access_handler.cpp
> +                EventsReader.EnableEvents(dev, *(dev->Port()));
Он должен ответить модбас исключением, оно превращается в `TSerialDevicePermanentRegisterException`, выводится в лог, и больше нет попыток включить события.
Если вообще нет ответа, то да, будем постоянно пытаться включить. Я так понимаю, что устройство должно всё таки ответить всегда.

2023-04-26 09:04 UTC, KraPete commented on src/serial_client_device_access_handler.cpp
> +                EventsReader.EnableEvents(dev, *(dev->Port()));
Обсудили с Никитой. Гарантий нет, что не было прошивок, которые молчат. Надо сделать логику, которая обрабатывает таймаут, идёт опрашивать регистры как обычно и пытается снова настроить события

2023-04-27 09:52 UTC, KraPete commented on wb-mqtt-serial.schema.json
> +          "title": "Sporadic",
Написал

2023-04-27 10:20 UTC, KraPete commented on src/poll_plan.h
> +class TTotalTimeBalancer
Сделал как обсуждали

2023-04-27 10:20 UTC, KraPete commented on src/poll_plan.h
> +        if (TotalTime < OldTotalTime) { // Prevent overflow
Сделал как обсуждали

2023-04-28 07:56 UTC, webconn commented on src/modbus_ext_common.h
> +        void SendRequest();
```suggestion
        void SendSingleRequest();
```

И во всех причастных местах

2023-05-02 14:16 UTC, KraPete commented on src/modbus_ext_common.h
> +        void SendRequest();
Заменил

2023-05-02 14:16 UTC, KraPete commented on src/serial_client_events_reader.h
> +struct TRegisterDescHasher: public std::unary_function<TEventsReaderRegisterDesc, size_t>
Убрал

2023-05-03 08:40 UTC, webconn requested changes

2023-05-03 08:40 UTC, webconn commented on src/port.h
> +    virtual size_t GetBaudrate() const;
Почему `size_t`, это же никак к размеру не относится? Тут вроде бы просто `unsigned` подошёл бы

2023-05-03 08:40 UTC, webconn commented on src/serial_client.cpp
> +        if (baudrate >= 115200 || baudrate == 0) {
Магия про `baudrate == 0`, конечно. Надо как-то более явно показать, что тут имеется в виду магическое значение "у порта нет baudrate`, хотя бы константу сделать

2023-05-03 10:07 UTC, KraPete commented on src/modbus_ext_common.cpp
> +    //             S       A
Моторллер не мой. Табличку дал @nikitoz236

2023-05-03 10:15 UTC, webconn commented on src/modbus_ext_common.cpp
> +    //             S       A
Ну так тем более. Тут достаточно просто расшифровать, что происходит

2023-05-03 10:46 UTC, KraPete commented on src/modbus_ext_common.cpp
> +    //             S       A
Я не знаю, что это за S и A.

2023-05-03 11:17 UTC, KraPete commented on src/port.h
> +    virtual size_t GetBaudrate() const;
Переделал

2023-05-03 11:17 UTC, KraPete commented on src/serial_client.cpp
> +        if (baudrate >= 115200 || baudrate == 0) {
Переделал

2023-05-04 11:01 UTC, webconn commented on src/modbus_ext_common.cpp
> +    // max(3.5 symbols, (12 bits + 800us)) + 9 * max(13 bits, 12 bits + 50us)
Меняем тут 12 на 20 обратно, ссылку на описание протокола и вроде на этом всё

2023-05-11 07:16 UTC, sikmir approved these changes

2023-05-11 11:32 UTC, webconn approved these changes

2023-05-11 11:40 UTC, KraPete commented
Rebase https://github.com/wirenboard/wb-mqtt-serial/pull/598

2023-05-11 11:40 UTC, closed without merging