Fix incorrect parameter names in device templates
wirenboard/wb-mqtt-serial pull request #597
Opened 2023-05-11 07:35 UTC by sikmir

2023-05-11 11:57 UTC, webconn reviewed
Хорошо бы ещё как-то сделать тест валидации шаблонов по новой схеме, и имена шаблонов поменять там, где они изменились

2023-05-11 11:57 UTC, webconn commented on debian/control
> +Build-Depends: debhelper (>= 10), pkg-config, libwbmqtt1-4-dev (>= 4.1.0), libwbmqtt1-4-test-utils (>= 4.1.0), j2cli:all
```suggestion
Build-Depends: debhelper (>= 10), pkg-config, libwbmqtt1-4-dev (>= 4.1.0~~), libwbmqtt1-4-test-utils (>= 4.1.0~~), j2cli:all
```

Это нам нужно, чтобы можно было пакеты из веток ставить, пока разработка идёт

2023-05-11 11:57 UTC, webconn commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, ucf, bsdutils (>= 2.29), libwbmqtt1-4 (>= 4.1.0)
```suggestion
Depends: ${shlibs:Depends}, ${misc:Depends}, ucf, bsdutils (>= 2.29), libwbmqtt1-4 (>= 4.1.0~~)
```

2023-05-11 11:57 UTC, webconn commented on templates/config-danfoss-ekc-202d-wb-ref.json
> +    "device_type": "danfoss_ekc_202d_wb_ref_df_178a",
Тут бы как-нибудь в названии дать понять, что обновлённый шаблон, чтобы техподдержке было проще разбирать чужие конфиги. Заодно закрепить это в README как правило версионирования шаблонов (например, префиксом `tpl2_`, `tpl3_` и т.д.)

2023-05-11 12:11 UTC, sikmir commented on debian/control
> +Build-Depends: debhelper (>= 10), pkg-config, libwbmqtt1-4-dev (>= 4.1.0), libwbmqtt1-4-test-utils (>= 4.1.0), j2cli:all
поправил

2023-05-11 12:11 UTC, sikmir commented on debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, ucf, bsdutils (>= 2.29), libwbmqtt1-4 (>= 4.1.0)
поправил

2023-05-11 12:18 UTC, sikmir commented on debian/changelog
> +  * Fix incorrect parameter names in device templates
добавил

2023-05-12 05:45 UTC, sikmir commented on templates/config-danfoss-ekc-202d-wb-ref.json
> +    "device_type": "danfoss_ekc_202d_wb_ref_df_178a",
добавил

2023-05-12 09:29 UTC, webconn reviewed
Я говорил ещё про тест валидатора, хочется проверять, что он сам работает и в новых шаблонах никак не появится сломанный параметр

2023-05-12 09:29 UTC, webconn commented on templates/config-carel-pj-basic.json
> +            "_3rd_input_configuration": {
Это нужное изменение?

2023-05-12 09:32 UTC, sikmir commented on templates/config-carel-pj-basic.json
> +            "_3rd_input_configuration": {
да, в JS имя переменной не может начинаться с цифры.

2023-05-15 05:53 UTC, KraPete requested changes
Ещё хочу тест, в котором провалится валидация шаблона из-за кривого названия параметра

2023-05-15 05:53 UTC, KraPete commented on README.md
> +При необходимости внести обратно несовместимые изменения в шаблон, его необходимо отметить устаревшим (добавить `"deprecated": true`) и создать его копию (при этом в `device_type`  нового шаблона доб
Может, постфикс делать?

2023-05-15 05:53 UTC, KraPete commented on templates/config-carel-pj-basic.json
> +            "_3rd_input_configuration": {
```suggestion
            "third_input_configuration": {
```

2023-05-15 08:03 UTC, sikmir commented
Добавил тест

2023-05-15 08:08 UTC, sikmir commented on README.md
> +При необходимости внести обратно несовместимые изменения в шаблон, его необходимо отметить устаревшим (добавить `"deprecated": true`) и создать его копию (при этом в `device_type`  нового шаблона доб
В конце может выглядеть как часть названия устройства, например `wb_foobar_tpl1`.

2023-05-16 07:49 UTC, webconn approved these changes

2023-05-16 07:53 UTC, KraPete approved these changes

2023-05-16 08:03 UTC, merged