Feature/62004 ebus opentherm new registers
wirenboard/wb-mqtt-serial pull request #607
Opened 2023-05-31 15:39 UTC by matveevrj

Add new parameters in WBE2-I-EBUS and WBE2-I-OPENTHERM templates

2023-05-31 18:14 UTC, sikmir commented on templates/config-wbe2-i-ebus.json
> +                "address": 212,
```suggestion
            {
                "name": "Water Pressure",
                "address": 212,
```

2023-06-09 05:13 UTC, KraPete requested changes

2023-06-09 05:13 UTC, KraPete commented on templates/config-wbe2-i-ebus.json
> +            { "name": "Burner Modulation Level (%)",
Не надо в названии писать единицы измерения. Если нет ничего кроме `name`, оно будет использовано как ключ в файле настроек и как название топика в MQTT.
Для единиц измерения есть `units`.
Для красивого текста в веб-интерфейсе надо использовать переводы.
Например, тут оставить `"name": "Burner Modulation Level"`, а в английский перевод добавить `"Burner Modulation Level": "Burner Modulation Level (%)"`, ну и ключ в русском подправить

2023-06-21 10:04 UTC, KraPete approved these changes

2023-06-21 10:05 UTC, KraPete commented
Тьфу ты, а тест поправить? Оно ж не собирается

2023-06-21 14:59 UTC, merged