Feature/62504 m1w2 buttons
wirenboard/wb-mqtt-serial pull request #615
Opened 2023-06-21 13:28 UTC by ad7718

Новый конфиг для wb-m1w2 на базе конфига от wb-mcm8. Добавлена обработка нажатий, подсчёт частоты пока не ведётся. Старый конфиг помечен как deprecated.

2023-06-22 04:57 UTC, KraPete requested changes
Надо ещё в тесты добавить информацию о новом шаблоне, иначе пакет не собирается

2023-06-22 04:57 UTC, KraPete commented on debian/changelog
> +wb-mqtt-serial (2.87.7) stable; urgency=medium
Давайте, minor поднимем

2023-06-22 04:57 UTC, KraPete commented on templates/config-wb-m1w2-buttons.json.jinja
> +        "frame_timeout_ms": 8,
А зачем 8? Я понимаю, что "так было в старом шаблоне", но, может, тут всё иначе?

2023-08-14 15:50 UTC, aadegtyarev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Input {{in_num}} counter",
А почему этот не sporadic? 

Ещё он к нажатиям не имеет никакого отношения — может под него отдельный режим «Дискретный вход» сделать? И туда этот счётчик и состояние входа.

2023-08-14 15:51 UTC, aadegtyarev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Input {{in_num}} Double Press Counter",
Предлагаю по умолчанию отключить опрос.

2023-08-14 15:51 UTC, aadegtyarev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Input {{in_num}} Shortlong Press Counter",
Предлагаю по умолчанию отключить опрос.

2023-08-14 15:52 UTC, aadegtyarev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "mode_description": "Для детектирования нажатий требуется прошивка v5.0.0 или новее",
давай уберём букву **v** в версии — смотрится странно.

2023-08-15 06:52 UTC, pgasheev requested changes
Шаблон `WB-M1W2 DI` наверно тоже стоит пометить как deprecated? Новый шаблон ведь его заменяет?

2023-08-15 06:52 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Supply voltage",
Voltage с большой буквы

2023-08-15 06:52 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "type": "voltage",
Это вроде не рекомендуется к использованию, нужно писать 
```
"type": "value",
"units": "V",
```

2023-08-15 06:52 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "type": "temperature",
```
"type": "value",
"units": "deg C",
```
И в других местах тоже

2023-08-15 06:52 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "Uptime": "Uptime (s)",
Думаю этот перевод можно убрать, а добавить `"units": "s",`

https://github.com/wirenboard/conventions

2023-08-15 06:52 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "address": 130, {# FIMXE: нет в карте регистров M1W2, но в прошивке видимо был #}
Зачем это в шаблоне? Надо сразу пофиксить в карте регистров

2023-08-15 06:58 UTC, pgasheev commented
> Шаблон `WB-M1W2 DI` наверно тоже стоит пометить как deprecated? Новый шаблон ведь его заменяет?

Я проглядел, он уже deprecated, оказывается

2023-08-15 07:00 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "address": 130, {# FIMXE: нет в карте регистров M1W2, но в прошивке видимо был #}
Так, а в M1W2 ведь вообще нет индикатора, нужно из шаблона убрать

2023-08-15 07:08 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "group": "g_general",
Не знаю, подходит ли это в группу "Общие", по-моему оно там теряется. Может в отдельную группу вынести. @aadegtyarev  как думаешь?

2023-08-15 08:38 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Supply voltage",
почему?

2023-08-15 08:39 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "type": "voltage",
можно подробнее?

2023-08-15 08:41 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "address": 130, {# FIMXE: нет в карте регистров M1W2, но в прошивке видимо был #}
есть же внутри, сбоку видно

2023-08-15 09:08 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "address": 130, {# FIMXE: нет в карте регистров M1W2, но в прошивке видимо был #}
Да, это я видимо с WB-MIR перепутал. Ок, пусть остается, хотя конечно для M1W2 отключать его - сомнительная необходимость

2023-08-15 09:10 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Supply voltage",
https://en.wikipedia.org/wiki/Capitalization

Шаблон новый, поэтому я думаю что нужно писать правильно. Призову @aadegtyarev ещё

2023-08-15 09:11 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "type": "voltage",
https://github.com/wirenboard/conventions#specific-value-type-controls

2023-08-16 08:31 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Supply voltage",
сейчас посмотрел пару даташитов, voltage с маленькой буквы

2023-08-16 08:43 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Supply voltage",
Пару каких даташитов? Нужно различать названия, которые в английском пишутся по правилам capitalization и просто текст, который понятно, что с маленьких букв будет. В шаблоне у нас - название. Посмотри соседние шаблоны. Там тоже встречается voltage с маленькой буквы, но это не повод новый шаблон делать неправильно

2023-08-16 08:48 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Input {{in_num}} counter",
Этот канал нужно тоже сделать sporadic (и проверить, что работает). Режим третий тут думаю не надо, т.к. этот называется "Счет и детектирование нажатий", то есть противоречий нет. В реле у нас так же

2023-08-16 17:02 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "Uptime": "Uptime (s)",
сделал

2023-08-16 17:03 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "type": "temperature",
сделал

2023-08-16 17:03 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "type": "voltage",
сделал

2023-08-16 17:03 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Supply voltage",
сделал

2023-08-16 17:03 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "mode_description": "Для детектирования нажатий требуется прошивка v5.0.0 или новее",
сделал

2023-08-16 17:03 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Input {{in_num}} Shortlong Press Counter",
сделал

2023-08-16 17:03 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Input {{in_num}} Double Press Counter",
сделал

2023-08-16 17:04 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Input {{in_num}} counter",
включил sporadic

2023-08-16 19:34 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "Uptime": "Uptime (s)",
Точно сделал? Проверял? Перевод убрал, а единицы измерения в канал не добавил. В русском переводе `(с)` тоже надо убрать

2023-08-17 08:51 UTC, ad7718 commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "Uptime": "Uptime (s)",
сейчас должно быть нормально

2023-08-17 10:14 UTC, sikmir commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "temperature_readings_filter_deg_description": "If new value equals 85 °C, it is discarded if it differs from previous one by more than filter value. Write 0 to disable filter. Defaul
Nit:
```suggestion
                "temperature_readings_filter_deg_description": "If the new value equals 85 °C, it is discarded if it differs from the previous one by more than filter value. Write 0 to disable the filter. Default value is 1",
```

2023-08-17 10:21 UTC, sikmir approved these changes

2023-08-17 10:53 UTC, sikmir approved these changes

2023-08-17 11:18 UTC, webconn commented
Петр в отпуске, заочно лайкнул, потому я вливаю

2023-08-17 11:18 UTC, merged