Feature/62480 add sokolm template
wirenboard/wb-mqtt-serial pull request #617
Opened 2023-06-29 19:13 UTC by matveevrj

Add new template for Sokol-M

2023-06-30 04:42 UTC, KraPete requested changes
Надо обновить changelog. Напомню, что при добавлении шаблона, мы обычно увеличиваем `minor`, а не `patch`.

2023-06-30 04:42 UTC, KraPete commented on templates/config-sokol-m.json
> +                "CO2": "Уровень CO2",
```suggestion
                "CO2": "Уровень CO₂",
```
Так же можно сделать для английского и для других надписей

2023-06-30 04:42 UTC, KraPete commented on templates/config-sokol-m.json
> +        "groups": [
Зачем делать группу для каналов? Можно просто без группы

2023-06-30 04:42 UTC, KraPete commented on templates/config-sokol-m.json
> +    "device_type": "SOKOL-M",
Он прямо так и называется SOKOL-M на английском? Если есть русскоязычное название, можно его добавить в переводы

2023-06-30 08:13 UTC, KraPete commented on templates/config-sokol-m.json
> +                "Pressure1": "Атмосферное давление",
Может, их как-то назвать по разному? Можно же запутаться, если будет две одинаковые строки

2023-07-04 12:17 UTC, KraPete commented on templates/config-sokol-m.json
> +                "Pressure1": "Атмосферное давление",
Моет, тогда и `Pressure1` на просто `Pressure` заменить?

2023-07-04 21:10 UTC, sikmir commented on templates/config-sokol-m.json
> +                "Pm25":"Dust 2.5 microns",
```suggestion
            "en": {
                "Pm25": "Dust 2.5 microns",  
```

2023-07-04 21:11 UTC, sikmir commented on templates/config-sokol-m.json
> +                "Relative humidity":"Относительная влажность воздуха",
```suggestion
                "Relative humidity": "Относительная влажность воздуха",
```

2023-07-04 21:11 UTC, sikmir commented on templates/config-sokol-m.json
> +            }
```suggestion
            }
```

2023-07-05 04:23 UTC, KraPete approved these changes

2023-07-05 09:49 UTC, merged