Feature/65108 add template ridan greencon
wirenboard/wb-mqtt-serial pull request #652
Opened 2023-09-25 12:28 UTC by matveevrj

Add new template for Ridan Greencon-R

2023-09-25 19:02 UTC, sikmir commented on templates/config-ridan-greencon-r.json
> +                "name": "Switching between Manual and programm modes",
```suggestion
                "name": "Switching between Manual and programmable modes",
```

2023-09-25 19:10 UTC, sikmir commented on templates/config-ridan-greencon-r.json
> +                "Switching between Manual and programm modes": "Выбор сценария (ручной или недельный)",
`programm mode` и `недельный` тут точно корректный перевод?

2023-09-27 10:18 UTC, sikmir commented on templates/config-ridan-greencon-r.json
> +                "Switching between Manual and programm modes": "Выбор сценария (ручной или недельный)",
Тогда programm -> programmable поправить, а то выше поменяли, а тут нет.

2023-09-28 04:28 UTC, KraPete requested changes
В целом неконсистентные названия в плане регистров букв. Где-то каждое слово с заглавной буквы, где-то только первое. Режимы работы названы с разным регистром первой буквы.

2023-09-28 04:28 UTC, KraPete commented on templates/config-ridan-greencon-r.json
> +        "guard_interval_us": 5000,
Почему задан этот параметр?

2023-09-28 04:28 UTC, KraPete commented on templates/config-ridan-greencon-r.json
> +            {
Зачем делать только одну группу? Можно вообще без групп обойтись тогда

2023-09-29 05:15 UTC, KraPete approved these changes

2023-09-29 05:15 UTC, KraPete commented on templates/config-ridan-greencon-r.json
> +                "Parameters": "Параметры",
Эту строку теперь можно убрать

2023-09-29 10:11 UTC, merged