Feature/64378 add new template komfovent
wirenboard/wb-mqtt-serial pull request #657
Opened 2023-10-04 14:04 UTC by matveevrj

2023-10-04 17:02 UTC, sikmir commented on templates/config-komfovent.json
> +                "title": "schedules hannels",
```suggestion
                "title": "schedules channels",

```

2023-10-04 17:09 UTC, sikmir commented on templates/config-komfovent.json
> +            ],
```suggestion
        ],

```

2023-10-04 17:11 UTC, sikmir commented on templates/config-komfovent.json
> +
```suggestion

```

2023-10-05 06:29 UTC, KraPete requested changes

2023-10-05 06:29 UTC, KraPete commented on templates/config-komfovent.json
> +                "order": 1
`order` для групп не надо писать. Порядок следования соответствует порядку, в котором группы описаны в шаблоне.

2023-10-05 06:29 UTC, KraPete commented on templates/config-komfovent.json
> +                "id": "FirstLevelAdjustingOfSupplyIntensity",
У нас во всех шаблонах параметры названы в [snake_case](https://ru.wikipedia.org/wiki/Snake_case)

2023-10-05 06:33 UTC, sikmir commented
Через форматер хорошо бы прогнать.

2023-10-11 08:34 UTC, KraPete approved these changes

2023-10-11 09:13 UTC, merged