add sporadic for input registers in mao4
wirenboard/wb-mqtt-serial pull request #662
Opened 2023-10-17 14:02 UTC by sfDaniil

2023-10-18 04:09 UTC, KraPete requested changes
Changelog не обновил

2023-10-18 14:36 UTC, KraPete approved these changes

2023-10-19 04:33 UTC, KraPete commented on debian/changelog
> +  * Add new template for Komfovent
Да пусть будет. Зато формат везде соблюдается

2023-11-03 04:52 UTC, KraPete commented on templates/config-wb-mao4.json.jinja
> +                "enabled": true,
Почему раньше было выключено, а теперь включено?

2023-11-03 10:57 UTC, sfDaniil commented on templates/config-wb-mao4.json.jinja
> +                "enabled": true,
Выключение этого пункта убирает топик в mqtt и wb-rules - и после обновления может сломать логику обработки нажатий на кнопки у клиентов которые это использовали.

думаю ранее было ошибочно выключенно
PR в котором выключили - 5 месяцев назад.
https://github.com/wirenboard/wb-mqtt-serial/pull/577/files#diff-ad2994acc72920852fac96601a0818770139aeecc8936ad5536751454990eb55

2023-11-03 11:08 UTC, KraPete approved these changes

2023-11-03 11:14 UTC, nikitoz236 approved these changes

2023-11-03 14:58 UTC, merged