mwac v2 template, upd old : debounce max, del reg5
wirenboard/wb-mqtt-serial pull request #671
Opened 2023-11-15 14:05 UTC by ad7718

2023-11-16 05:09 UTC, KraPete requested changes
1. Нужено обновить ChangeLog
2. Новые каналы надо добавиь в тест
![Screenshot_20231116_100745](https://github.com/wirenboard/wb-mqtt-serial/assets/86825564/cf1cc722-31ff-4d3e-ad43-eecc1a96e0e6)
3. Почему для старого шаблона удалили запись 5-ого регистра?

2023-11-16 18:04 UTC, ad7718 commented
>     3. Почему для старого шаблона удалили запись 5-ого регистра?
Решили удалить его, @nikitoz236 говорит что он не нужен

2023-12-22 05:05 UTC, ad7718 commented
[config-wb-mwac2.json](https://github.com/wirenboard/wb-mqtt-serial/files/13748510/config-wb-mwac2.json)

Json для тех, кто хочет протестировать шаблон

2023-12-22 06:12 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                "name": "P{{ lp_in_num }} Counter Offset",
перенёс в новом шаблоне в параметры

2023-12-22 06:13 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                "WB-MWAC_template_title": "WB-MWAC v2 (модуль контроля протечек и расхода воды )",
починил

2023-12-27 06:11 UTC, ad7718 commented
[config-wb-mwac.json](https://github.com/wirenboard/wb-mqtt-serial/files/13775995/config-wb-mwac.json)
[config-wb-mwac2.json](https://github.com/wirenboard/wb-mqtt-serial/files/13775996/config-wb-mwac2.json)

2023-12-28 06:00 UTC, ad7718 commented
[config-wb-mwac2.json](https://github.com/wirenboard/wb-mqtt-serial/files/13783732/config-wb-mwac2.json)

2023-12-28 06:01 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                "name": "P{{ lp_in_num }} Counter Offset",
удалил регистр смещения до лучших времён

2023-12-28 07:27 UTC, aadegtyarev commented
> [config-wb-mwac2.json](https://github.com/wirenboard/wb-mqtt-serial/files/13783732/config-wb-mwac2.json)

Для входов в режиме «Датчик протечки» подпись «Действия для выходов при замыкании» лучше заменить на «Действия для выходов при срабатывании датчика».
![изображение](https://github.com/wirenboard/wb-mqtt-serial/assets/77433258/23afb5dc-a162-45ad-8d0c-cef2129de334)

Тут что-то сложно написано, хотя и подробно. Может напишем по другому? Мой вариант:
>Состояние выходов для безопасного режима и настройки "Состояния выходов при подаче питания". По умолчанию безопасный режим отключен, в настройке "Состояния выходов при подаче питания" установлено "Перевести в безопасное состояние", а безопасное состояние для каждого выхода установлено в "Выключен".

![изображение](https://github.com/wirenboard/wb-mqtt-serial/assets/77433258/aa232a04-327b-4c6e-8fa5-91108260b838)

Тут при установленной галочке выбирается 30, а по умолчанию написано 20. Наверное, забыли поправить.
Ещё мы обычно размерность пишем в имени параметра, то есть «Таймер режима уборки (мин)». 
![изображение](https://github.com/wirenboard/wb-mqtt-serial/assets/77433258/467981cf-4ef3-470c-a337-758c8d3a7667)

Тут и в других местах предлагаю использовать термин «влажная уборка». На этикетке мы пишем «Wet cleaning», хочется, чтобы одинаково было.
![изображение](https://github.com/wirenboard/wb-mqtt-serial/assets/77433258/bfa75795-00dd-4d65-beaa-13b12d63d2b1)

Здесь размерность рядом везде есть в названии параметра, а в антидребезге нет
![изображение](https://github.com/wirenboard/wb-mqtt-serial/assets/77433258/64f068c2-df0c-4719-959d-91fdd4f3759a)

Ну и в названии счтчиков цифры без буквы F

2023-12-28 10:48 UTC, ad7718 commented
[config-wb-mwac2.json](https://github.com/wirenboard/wb-mqtt-serial/files/13785778/config-wb-mwac2.json)

2024-01-11 14:02 UTC, ad7718 commented
[config-wb-mwac2.json](https://github.com/wirenboard/wb-mqtt-serial/files/13904195/config-wb-mwac2.json)

2024-01-15 18:31 UTC, ad7718 commented
[config-wb-mwac2.json](https://github.com/wirenboard/wb-mqtt-serial/files/13942066/config-wb-mwac2.json)

2024-01-22 11:43 UTC, aadegtyarev commented
Увидел, что мы выводим состояние счётных входов P1 и P2. Не вижу практического смысла. Но если очень хочется, то давай хотя бы по умолчанию отклюим опрос, оставис только сами счётчики.

![изображение](https://github.com/wirenboard/wb-mqtt-serial/assets/77433258/95faf941-3f60-4f19-8489-62e99b4e2eb5)

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "counter_pulse_weight_description": "Распространённые счётчики имеют вес 1, 10, 50, или 100 литров на импульс. Ознакомьтесь с технической документацией на ваш счётчик. 1 — 10000, 1 по
Меняем на: Смотрите в технической документации на ваш счетчик

Диаппазон вынести в min/max параметра, а по умолчанию модно не указывать никак тут, смысла не имеет.

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "Counter Pulse Weight": "Вес импульса",
Меняем на: Вес импульса (л)

А ещё тут в параметре не стоит max значение, можно ввести 1000000 и ошибки не будет, а в регистр не зальётся.

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "Counter Offset": "Начальное значение счётчика",
Меняем на: Начальное значение счетчика (л)

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "counter_offset_description": "Начальное значение счётчика в литрах",
Дублирует название параметра, лучше тут написать, как работает: «Значение будет прибавлено к счетчику объема»

Оно тут в литрах точно, потом перечитается в м3 само?

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "Counter {{ lp_in_num }}": "Счётчик {{ lp_in_num }}",
Так исторически сложилось, что мы не пишем ё в интерфейсе, поэтому здесь и везде надо ё убрать, например: "счетчик", "обьем".

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "Input {{ letter }}{{ in_num }} Mode": "Режим работы входа {{ letter }}{{ in_num }}",
Не нужно писать «входа X», оно есть в выборе слева. Просто: Режим работы

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "Input {{ letter }}{{ in_num }} Debounce (ms)": "Время защиты от дребезга входа {{ letter }}{{ in_num }} (мс)",
Аналогично, не надо писать для какого входа (смотрим на реле, например). Параметр должен называться «Время подавления дребезга (мс)» и подсказка: «Вносит задержку в реакцию, рекомендовано 50 мс»

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "leak_mode_name": "Режим \"Протечка\"",
Это же используется в настройках входов? Давай тут тоже «Оповещение о протечке»
![изображение](https://github.com/wirenboard/wb-mqtt-serial/assets/77433258/54f9e68b-cccf-4a6c-8013-9a1c9304698d)

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +
Решили, что не будем писать тут по умолчанию и диапазон. Диапазон надо указать в параметре через max/min, а подпись взять из реле:
«Если за указанное время второго нажатия не было - считаем нажатие одиночным. 0 - отключит все нажатия кроме короткого и длинного. Вносит задержку в реакцию на короткое нажатие, рекомендовано 300 мс»

Тире тоже везде в интерфейсе у нас дефисом — так программистам легче.

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "lp_hold_time_description": "Если нажатие длится больше указанного времени — считаем его длинным. 500 — 5000 мс, 1000 по умолчанию.",
Также — диапазоны задавать в min/max параметра, по умолчанию называем рекомендованным:
«Если нажатие длится больше указанного времени - считаем его длинным. Рекомендовано 1000 мс»

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "wet_cleaning_mode_timer_description": "1 — 360 мин, 20 по умолчанию",
Диапазон добавить в min/max, по умолчанию заменить на рекомендовано

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "wet_cleaning_mode_description": "Режим \"Влажная уборка\" используется для отключения реакции на датчики протечки при влажной уборке помещения. При запуске/остановке режима издаётся
Заменить на:
«В режиме "Влажная уборка" модуль не реагирует заданное время на датчики протечки, а индикаторы входов коротко мигают. Включение и выключение режима сопровождается звуковой индикацией.

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "outputs_safe_state_description": "Состояние для безопасного режима и настройки \"Состояния реле при подаче питания\". По умолчанию безопасный режим отключен, а настройки безопасных с
Оставляем только первую часть:
«Состояние для безопасного режима и настройки "Состояния реле при подаче питания"»

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "safety_mode_description": "При потере связи по RS-485 модуль защиты от протечек будет работать автономно. Однако есть возможность задать определенное состояние выходов и режима \"Про
Упрощаем:
«При потере связи по RS-485 модуль защиты от протечек будет работать автономно.  Также пользователь может задать состояние выходов и оповещения о протечке с помощью безопасного режима»

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "poll_timeout_description": "Параметр определяет время отсутствия опроса в секундах, после которого будет активирован безопасный режим. 1 — 65534 с, 10 по умолчанию.",
Аналогично, диапазон выносим в min/max, по умолчанию меняем на рекомендовано

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "Actions for \"Leak\" mode": "Действия для режима \"Протечка\"",
Действие для оповещения о протечке

2024-03-13 09:49 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "leak_mode_name": "Режим \"Протечка\"",
А вот канал можно назвать просто Протечка
![изображение](https://github.com/wirenboard/wb-mqtt-serial/assets/77433258/4279eb7a-7b29-425c-853c-f309f6486400)

2024-03-13 11:02 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                "Counter {{ lp_in_num }}": "Счётчик {{ lp_in_num }}",
я заметил, а почему так и почему бы не начать писать ё?

2024-03-13 11:04 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                "counter_offset_description": "Начальное значение счётчика в литрах",
В литрах, пересчитается. Можешь проверить счётчики кстати, вдруг где ошибка, никто кроме меня не проверял

2024-03-13 11:06 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                "leak_mode_name": "Режим \"Протечка\"",
Но тогда в панели управления устройством будет тумблер "Протчека" и как-то странно включать протчеку

2024-03-13 11:08 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +
а по правилам русского дефис вместо тире разве норм?

2024-03-13 11:09 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                "wet_cleaning_mode_timer_description": "1 — 360 мин, 20 по умолчанию",
По-моему странно рекомендовать значение для тйамера режима уборки, тут именно по умолчанию

2024-03-13 11:11 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                "poll_timeout_description": "Параметр определяет время отсутствия опроса в секундах, после которого будет активирован безопасный режим. 1 — 65534 с, 10 по умолчанию.",
Точно рекомендовано? Может по умолчнию оставить?

2024-03-13 11:13 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "counter_offset_description": "Начальное значение счётчика в литрах",
ок

2024-03-13 11:14 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "Counter {{ lp_in_num }}": "Счётчик {{ lp_in_num }}",
Станет отличаться от остальных шаблонов и половина людей будет писать, а половина нет. Лучше пока нигде не писать.

2024-03-13 11:15 UTC, aadegtyarev commented on templates/config-wb-mwac2.json.jinja
> +                "poll_timeout_description": "Параметр определяет время отсутствия опроса в секундах, после которого будет активирован безопасный режим. 1 — 65534 с, 10 по умолчанию.",
Да, рекомендовано. Меньше — можно словить переключение туда/сюда, больше — смысла нет. А в чем сомнение?

2024-03-13 11:16 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                "Counter {{ lp_in_num }}": "Счётчик {{ lp_in_num }}",
ок

2024-03-14 06:20 UTC, ad7718 commented
> 1. Нужено обновить ChangeLog
> 
>     2. Новые каналы надо добавиь в тест
>        ![Screenshot_20231116_100745](https://private-user-images.githubusercontent.com/86825564/283327317-cf1cc722-31ff-4d3e-ad43-eecc1a96e0e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTM0NTUsIm5iZiI6MTcxMDM1MzE1NSwicGF0aCI6Ii84NjgyNTU2NC8yODMzMjczMTctY2YxY2M3MjItMzFmZi00ZDNlLWFkNDMtZWVjYzFhOTZlMGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE4MDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YTU5ZTc4NmE0NTg0OWIzZTEzZmJjOGRmOGFlMGJiN2VkNzJmMTAwMmUyZWE1MDMwOTg1MjkwNmUxNGM2NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hOXWxiE1niZPDhIMs8oIN8IptpLVzhCPGigi7n7ntPQ)
> 
>     3. Почему для старого шаблона удалили запись 5-ого регистра?

Старый шаблон теперь в отдельном ПР, тесты поправил

2024-03-14 08:12 UTC, aadegtyarev approved these changes
Много обсуждали, смотрели, вливаем.

2024-03-14 09:16 UTC, sikmir commented on templates/config-wb-mwac2.json.jinja
> +                    "9600 kbps",
Во остальных шаблонах у нас без ` kbps`, для единообразности.

2024-03-14 09:22 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                    "9600 kbps",
Это сегодня Яша с Женей предложили

2024-03-14 11:11 UTC, sikmir approved these changes

2024-03-14 11:19 UTC, KraPete requested changes

2024-03-14 11:19 UTC, KraPete commented on templates/config-wb-mwac2.json.jinja
> +                "name": "Input {{ letter }}{{ in_num }} sensor presence (only for Larnitech sensors)",
Предлагаю тут сделать ещё
```
"id": "Input {{ letter }}{{ in_num }} sensor presence"
```
Иметь в названии канала в MQTT строку со скобочками странно. Комментарий нужен только в интерфейсе настройки. Аналогично стоит и в остальных топиках сделать

2024-03-14 11:19 UTC, KraPete commented on test/TDeviceTemplatesTest.Validate.dat
> +	battery_state  =>  battery_state
Название канала странное. Надо понимать, что в таком виде оно пойдёт в конфиг и в название топика MQTT

2024-03-14 11:19 UTC, KraPete commented on test/TDeviceTemplatesTest.Validate.dat
> +	leakage_mode_name  =>  leakage_mode_name
Ещё странное название канала

2024-03-14 11:19 UTC, KraPete commented on test/TDeviceTemplatesTest.Validate.dat
> +	wet_cleaning_mode_name  =>  wet_cleaning_mode_name
И тут

2024-03-14 16:09 UTC, ad7718 commented on test/TDeviceTemplatesTest.Validate.dat
> +	battery_state  =>  battery_state
а каковы правила именования каналов?

2024-03-15 05:09 UTC, KraPete commented on test/TDeviceTemplatesTest.Validate.dat
> +	battery_state  =>  battery_state
@aadegtyarev Порекомендуешь что-нибудь?

2024-03-15 12:41 UTC, nikitoz236 commented on test/TDeviceTemplatesTest.Validate.dat
> +	battery_state  =>  battery_state
> а каковы правила именования каналов?

чтобы было понятное. и это текст видимый пользователем а не имя переменной

2024-03-15 13:14 UTC, KraPete commented on test/TDeviceTemplatesTest.Validate.dat
> +	battery_state  =>  battery_state
На самом деле всё немного сложнее.
Если в шаблоне только `name` у канала, то его значение используется в конфиге как ключ и из него делается имя топика MQTT. Оно же попадает в надписи в веб-интерфейсе.
Если для него задан перевод, то он отображается в веб-интерфейсе, при этом в конфиге и в MQTT всё ещё висит оригинальная строка.

2024-03-15 13:15 UTC, KraPete commented on test/TDeviceTemplatesTest.Validate.dat
> +	battery_state  =>  battery_state
Если задан `id`, то он используется для формирования топика в MQTT. При этом в конфиге всё ещё значение `name`.

2024-03-15 13:19 UTC, KraPete commented on test/TDeviceTemplatesTest.Validate.dat
> +	battery_state  =>  battery_state
Вероятно, стоит руководствоваться здравым смыслом. Конфиг руками мало кто заполняет, а уж писать ключи каналов точно никто не станет, но вот почитать его можно. Топики MQTT используют постоянно, их прописывают во всяком стороннем ПО. Кажется логичным, что имена в MQTT для одного устройства должны формироваться похоже. Ещё кажется, что аналогичные топики у разных типов устройств должны называться одинаково

2024-03-18 08:53 UTC, ad7718 commented on test/TDeviceTemplatesTest.Validate.dat
> +	wet_cleaning_mode_name  =>  wet_cleaning_mode_name
добавил id

2024-03-18 08:53 UTC, ad7718 commented on test/TDeviceTemplatesTest.Validate.dat
> +	leakage_mode_name  =>  leakage_mode_name
добавил id

2024-03-18 08:53 UTC, ad7718 commented on test/TDeviceTemplatesTest.Validate.dat
> +	battery_state  =>  battery_state
добавил id

2024-03-18 08:53 UTC, ad7718 commented on templates/config-wb-mwac2.json.jinja
> +                "name": "Input {{ letter }}{{ in_num }} sensor presence (only for Larnitech sensors)",
добавил id

2024-03-18 11:09 UTC, KraPete approved these changes

2024-03-18 11:18 UTC, merged