Feature/69032 led dimmer out events
wirenboard/wb-mqtt-serial pull request #672
Opened 2023-11-20 10:57 UTC by sfDaniil

2023-11-20 11:12 UTC, pgasheev requested changes

2023-11-20 11:12 UTC, pgasheev commented on templates/config-wb-led.json.jinja
> +                "type": "range",// ? а почему не было ранее ?
Потому что по умолчанию тут type = value. Почему ты решил, что должно быть range?

2023-11-20 11:12 UTC, pgasheev commented on templates/config-wb-mrgbw-d-fw3.json.jinja
> +                "type": "range",// ? а почему не было ранее ?
Так же

2023-11-20 11:13 UTC, KraPete requested changes

2023-11-21 18:34 UTC, sfDaniil commented on templates/config-wb-led.json.jinja
> +                "type": "range",// ? а почему не было ранее ?
значения по умолчанию не было, его не хватало явно прописанным,
предлагаю прописать явно:, а именно  "type": "value",
решил что будет range - так как все регистры подобного типа именно такие, и не понятно чем этот отличается.

2023-11-21 18:34 UTC, sfDaniil commented on templates/config-wb-led.json.jinja
> +                "type": "range",// ? а почему не было ранее ?
предлагаю прописать явно:, а именно "type": "value",  - одобряешь ?

2023-11-21 18:35 UTC, sfDaniil commented on templates/config-wb-led.json.jinja
> +                "type": "range",// ? а почему не было ранее ?
чтобы обсудать - а что именно там должно быть и почему не было, обсуждаю выше с Павлом.

2023-11-21 18:45 UTC, pgasheev commented on templates/config-wb-led.json.jinja
> +                "type": "range",// ? а почему не было ранее ?
> предлагаю прописать явно:, а именно "type": "value", - одобряешь ?

Да.

Почему тут value - потому что диапазон от 3 до 10000 и мышкой двигать range мышкой тут неудобно

2023-11-22 11:31 UTC, pgasheev approved these changes

2023-11-22 11:37 UTC, pgasheev approved these changes

2023-11-28 07:39 UTC, KraPete approved these changes

2023-11-28 15:55 UTC, merged