Add Dauerhaft CM5 template
wirenboard/wb-mqtt-serial pull request #693
Opened 2024-02-12 22:20 UTC by sikmir

<img width="454" alt="Näyttökuva 2024-2-13 kello 1 33 12" src="https://github.com/wirenboard/wb-mqtt-serial/assets/688044/759ea2c2-2fa8-4671-a758-63732082658d">
<img width="1048" alt="Näyttökuva 2024-2-13 kello 1 33 25" src="https://github.com/wirenboard/wb-mqtt-serial/assets/688044/d75b93ae-1707-47db-8637-11fd36c50480">
<img width="1049" alt="Näyttökuva 2024-2-13 kello 1 33 51" src="https://github.com/wirenboard/wb-mqtt-serial/assets/688044/95825566-146c-4af3-906d-932afca29ff9">

2024-02-13 03:49 UTC, KraPete requested changes
Может, не делать 2 группы? Параметров и каналов мало, кажется, что можно просто одним списком всё вывести

2024-02-13 03:49 UTC, KraPete commented on templates/config-dauerhaft-cm5.json
> +                "Speed": "Скорость",
`Скорость` и `Скорость обмена` рядом у меня вызвали замешательство. Не сразу понял, что это скорость движения мотора. Может, более детально назвать параметр?

2024-02-14 14:31 UTC, sikmir commented on templates/config-dauerhaft-cm5.json
> +                "Speed": "Скорость",
поправил

2024-02-15 04:53 UTC, KraPete requested changes

2024-02-15 04:53 UTC, KraPete commented on templates/config-dauerhaft-35-45.json
> +        "id": "dauerhaft-35-45",
А тут же сменится топик? Т.е. старые инсталляции перестанут работать

2024-02-15 04:53 UTC, KraPete commented on templates/config-dauerhaft-35-45.json
> +                "description": "baud_rate_description",
Перевод на русский забыл

2024-02-15 06:41 UTC, sikmir commented on templates/config-dauerhaft-35-45.json
> +        "id": "dauerhaft-35-45",
Тогда оставить старый шаблон как есть, но пометить deprecated?

2024-02-15 06:47 UTC, KraPete commented on templates/config-dauerhaft-35-45.json
> +        "id": "dauerhaft-35-45",
@aadegtyarev Что скажешь?

2024-02-15 06:57 UTC, sikmir commented on templates/config-dauerhaft-35-45.json
> +                "description": "baud_rate_description",
добавил

2024-02-21 06:45 UTC, aadegtyarev commented on templates/config-dauerhaft-35-45.json
> +        "id": "dauerhaft-35-45",
Да, старый надо пометить deprecated. А мы не хотим сделать один шаблон на две шторы, но внутри дать выбор модели привода? Каналов немного вроде и названия топиков не должны пострадать.

2024-02-26 06:56 UTC, sikmir commented on templates/config-dauerhaft-35-45.json
> +        "id": "dauerhaft-35-45",
Оставил как deprecated. А чем один шаблон удобнее? Сейчас модели 2, различий довольно много, а так будет куча условий в шаблоне.

2024-02-27 08:31 UTC, KraPete approved these changes

2024-02-28 20:39 UTC, sikmir commented
<img width="456" alt="Näyttökuva 2024-2-29 kello 0 37 57" src="https://github.com/wirenboard/wb-mqtt-serial/assets/688044/9f40d885-9344-45fb-a1dd-42bbbbe34549">

2024-02-28 21:19 UTC, merged