Add support for enums in templates
wirenboard/wb-mqtt-serial pull request #700
Opened 2024-03-07 13:19 UTC by sikmir

Implements https://github.com/wirenboard/conventions/pull/7

`echo "deb http://deb.wirenboard.com/all experimental.enum main" > /etc/apt/sources.list.d/enum.list`

2024-03-11 04:43 UTC, KraPete requested changes

2024-03-11 04:43 UTC, KraPete commented on src/serial_config.cpp
> +                throw TConfigParserException("enum and enum_titles should have the same size -- " +
Может, warning вывести, а то тут сразу всё упадёт?

2024-03-11 04:43 UTC, KraPete commented on test/configs/config-s2k-test.json
> +              "enum": [0, 1],
Давай, лучше отдельный тест для enum сделаем. Как-то не очень очевидно их проверять в тесте какого-то произвольно устройства

2024-03-11 07:54 UTC, KraPete commented on src/serial_config.cpp
> +                throw TConfigParserException("enum and enum_titles should have the same size -- " +
С другой стороны на работу сервиса это вообще не влияет, ну будут в опциях вместо названий числа выводиться, не страшно.

2024-03-11 08:01 UTC, sikmir commented on src/serial_config.cpp
> +                throw TConfigParserException("enum and enum_titles should have the same size -- " +
Тоже верно

2024-03-12 06:17 UTC, sikmir commented on src/serial_config.cpp
> +                throw TConfigParserException("enum and enum_titles should have the same size -- " +
поправил

2024-03-12 06:17 UTC, sikmir commented on test/configs/config-s2k-test.json
> +              "enum": [0, 1],
вынес в отдельный тест

2024-03-12 06:20 UTC, KraPete approved these changes

2024-03-12 06:20 UTC, KraPete commented on src/serial_config.cpp
> +                LOG(Warn) << "enum and enum_titles should have the same size -- " << device_config->DeviceType;
Давай, ещё название канала сюда

2024-03-12 06:30 UTC, sikmir commented on src/serial_config.cpp
> +                LOG(Warn) << "enum and enum_titles should have the same size -- " << device_config->DeviceType;
добавил

2024-03-12 06:55 UTC, KraPete approved these changes

2024-03-12 07:51 UTC, merged