Update wmac v1 template
wirenboard/wb-mqtt-serial pull request #703
Opened 2024-03-13 13:33 UTC by ad7718

2024-03-18 07:15 UTC, KraPete requested changes
Удалили топики `K1` и `K2`. У клиентов на них могла быть завязана логика, в результате она тихо сломается, ещё и настройки опроса не применятся.
Кстати, случаем параметры не поменяли идентификаторы?

2024-03-18 07:15 UTC, KraPete commented on test/TDeviceTemplatesTest.Validate.dat
> +	wet_cleaning_mode_name  =>  wet_cleaning_mode_name
Странное название. Оно попадёт в конфиг и станет частью топика MQTT

2024-04-08 04:34 UTC, alexey-gamov commented on test/TDeviceTemplatesTest.Validate.dat
> +	wet_cleaning_mode_name  =>  wet_cleaning_mode_name
Следует заменить `wet_cleaning_mode_name -> Cleaning Mode` как в шаблоне WB-MWAC v.2

2024-05-14 09:14 UTC, ad7718 commented on test/TDeviceTemplatesTest.Validate.dat
> +	wet_cleaning_mode_name  =>  wet_cleaning_mode_name
исправил

2024-05-14 16:14 UTC, ad7718 commented
> Удалили топики `K1` и `K2`. У клиентов на них могла быть завязана логика, в результате она тихо сломается, ещё и настройки опроса не применятся. Кстати, случаем параметры не поменяли идентификаторы?

Параметры проверил, имена совпадают

2024-05-15 03:48 UTC, KraPete requested changes

2024-05-15 03:48 UTC, KraPete commented on test/TDeviceTemplatesTest.Validate.dat
> +	Output K1  =>  K1
Всё ещё плохо. Ты поменял название канала с `K1` на `Output K1`. Добавил `id`, это правильно, топик в mqtt не изменился. Но название канала в файле настроек изменилось. Если у клиента были какие-то настройки для этого канала, они не применятся. Если хочешь изменить название канала в web-интерфейсе, используй переводы.
```
...
"name": "K1"
...
"translations": {
  "en": {
    "K1": "Output K1"
  },
  "ru": {
    "K1": "Выход K1"
  }
}
```

2024-05-15 07:07 UTC, ad7718 commented on test/TDeviceTemplatesTest.Validate.dat
> +	Output K1  =>  K1
вернул оригинальные имена

2024-05-16 00:49 UTC, alexey-gamov commented on test/TDeviceTemplatesTest.Validate.dat
> +	Output K1  =>  K1
Режим уборки переименуйте для совместимости)

2024-05-20 09:22 UTC, KraPete approved these changes

2024-05-20 09:35 UTC, merged