Start service with invalid config to provide functions for wb-mqtt-homeui
wirenboard/wb-mqtt-serial pull request #716
Opened 2024-03-27 07:33 UTC by KraPete

2024-03-28 15:45 UTC, webconn reviewed
Попробовал вживую. Если положить поломанный JSON или пустой файл, в интерфейсе появляется такое:

![image](https://github.com/wirenboard/wb-mqtt-serial/assets/1550335/37ceba39-09bd-4892-a8d4-08b359c44a00)

Если положить `{}` в конфиг, будет ошибка ` TypeError: e.ports is null`.

Сервис wb-mqtt-serial в обоих случаях отвечает редактору конфигов, но не отвечает сканеру (я так понимаю, это ожидаемое поведение сейчас).

Чинить ошибки, как я понимаю, надо во фронтенде, тут вроде ничего не затронуто

2024-03-28 15:45 UTC, webconn commented on src/config_schema_generator.cpp
> +    class TDeviceTypeValidator
я правильно понимаю, что этот класс - это многословная обёртка над методом `Validate` внутри, чтобы поменьше аргументов передавать?

2024-03-28 15:45 UTC, webconn commented on src/confed_config_generator.cpp
> -            if (device["slave_id"].isBool()) {
оно раньше тоже было не нужно?

2024-03-29 06:40 UTC, KraPete commented on src/config_schema_generator.cpp
> +    class TDeviceTypeValidator
Да

2024-03-29 06:40 UTC, KraPete commented on src/confed_config_generator.cpp
> -            if (device["slave_id"].isBool()) {
Не нужно. Это осталось от моих старых экспериментов с редактором адреса для устройств с поддержкой широковещательных сообщений

2024-03-29 06:56 UTC, KraPete commented
Во фронте поправил https://github.com/wirenboard/homeui/pull/531

2024-03-29 07:49 UTC, webconn commented
По-моему с обработкой ошибок стало хуже. То есть сейчас если конфиг сломан, редактор откроется с пустым как ни в чём не бывало, и даже никак не подскажет выше, что есть ошибка. Уже предвкушаю гневные посты на форуме :)

Я думаю, не стоит сломанный конфиг выводить как пустой. Пусть лучше сейчас выводится только ошибка (но адекватная, с указанием сходить в файл ручками и посмотреть, что с ним не так). Следующим этапом попробуем всё-таки сделать текстовый редактор для json и выводить его в случае ошибок в конфиге.

Фикс в фронт про ports, думаю, адекватный, тем не менее.

2024-03-29 07:49 UTC, webconn requested changes
про обработку ошибок написал коммент мимо ревью

2024-03-29 08:49 UTC, KraPete commented
Вернул проброс исключений

2024-04-01 07:10 UTC, webconn approved these changes
в целом мне всё нравится, но появилась идея про короткую ссылку на вики в логах. Я бы на самом деле прямо сейчас её туда добавил и страничку сделал с редиректом на инструкцию. Вроде делается не очень долго, а практика хорошая, позволит быстро сориентироваться и не писать инструкции в логах

2024-04-02 03:45 UTC, merged