Feature/72590 template reset input countres
wirenboard/wb-mqtt-serial pull request #727
Opened 2024-04-16 12:07 UTC by SupersADF

добавил кнопку сброса дискретных счетчиков в шаблон

2024-04-16 13:22 UTC, pgasheev requested changes

2024-04-16 13:22 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Reset all counters",
Нужен ещё перевод

2024-04-16 13:22 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "address": 100,
value лучше тоже явно прописать

2024-04-16 13:22 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "group": "g_general"
И ещё наверно нужно condition? Показывать канал только если выбран режим дискретного входа хотя бы на одном входе. Плюс я бы по умолчанию сделал enabled: false, иначе канал появится у всех, в том числе и у тех, кому он не нужен

2024-04-16 17:12 UTC, pgasheev requested changes

2024-04-16 17:12 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "condition": "in{{in_num}}_mode==1"
Так, а это же один канал для всех входов, его надо вынести из цикла. А вот поле condition формировать как раз циклом

2024-04-16 17:12 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "Reset input counters": "Сброс счетчиков цифровых входов"
Перевод и имя канала сделай в соответствии с шаблоном МСМ8

2024-04-16 17:12 UTC, pgasheev commented on templates/config-wb-m1w2-buttons.json.jinja
> +                "name": "Reset input counters",
Имя канала должно быть по правилам capitalization, т.е. каждое слово с большой буквы. т.к. это название

2024-04-17 09:59 UTC, pgasheev approved these changes

2024-04-17 10:23 UTC, sikmir approved these changes

2024-04-17 11:33 UTC, merged