Update config-wb-domofon-mb.json
wirenboard/wb-mqtt-serial pull request #735
Opened 2024-05-03 09:29 UTC by matveevrj

Исправил опечатку в переводах

2024-05-03 09:30 UTC, KraPete requested changes
Надо changelog обновить

2024-05-17 08:40 UTC, alexey-gamov commented
Не думаю что привидятся еще шаблоны из этой категории. Может переименовать в "Устройства специального назначения"?

2024-05-31 05:06 UTC, KraPete approved these changes

2024-06-04 19:33 UTC, sikmir approved these changes

2024-07-10 12:13 UTC, merged