WB-MDM3: add light scenes support
wirenboard/wb-mqtt-serial pull request #751
Opened 2024-05-23 07:58 UTC by Ilia1S

Добавлена поддержка световых сцен для WB-MDM3
Тикет 73050

@nikitoz236 @pgasheev

2024-05-23 08:35 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "Channel {{ch_number}} Switch": "Channel {{ch_number}}",
Это тут наверно не нужно? Со сценами вроде не связано. Проверь по шаблону, есть ли такие названия, для которых ты добавил этот перевод

2024-05-23 08:35 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "Channel {{ch_number}} Switch": "Канал {{ch_number}}",
Не нужно

2024-05-23 09:22 UTC, Ilia1S commented on templates/config-wb-mdm3.json.jinja
> +                "Channel {{ch_number}} Switch": "Channel {{ch_number}}",
Исправил

2024-05-23 09:22 UTC, Ilia1S commented on templates/config-wb-mdm3.json.jinja
> +                "Channel {{ch_number}} Switch": "Канал {{ch_number}}",
Исправил

2024-05-31 05:05 UTC, KraPete approved these changes

2024-05-31 06:22 UTC, pgasheev requested changes

2024-05-31 06:22 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "required": true,
Нельзя делать новые параметры с required: true, т.к. это ломает загрузку старых конфигов. Посмотри, как в МАО4 сделано

2024-05-31 06:22 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "required": true,
@KraPete напомни, пожалуйста. Мы это голосом обсуждали, но ведь ещё не сделали? Я имею в виду загрузку конфига, если в нём нет обязательных параметров

2024-05-31 06:27 UTC, KraPete commented on templates/config-wb-mdm3.json.jinja
> +                "required": true,
Нет, не сделали

2024-05-31 17:38 UTC, pgasheev commented
Всё ок, теперь ещё задание по шаблону:
Нужно группу "Режим работы входов" спрятать в группу "Общие". Там написать написать коммент, что 1-кнопочный и 2-х кнопочный режимы оставлены исключительно для совместимости со старыми версиями прошивки до 2.7.0.
Во входах изменить condition таким образом, чтобы при невыбранном режиме работы входа отображались параметры для настройки нажатий

2024-06-04 06:36 UTC, pgasheev requested changes

2024-06-04 06:36 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "inputs_mode_description": "Пользовательский режим позволяет задать действия для каждого входа и типа нажатия. Доступно с версии прошивки 2.7.0. Однокнопочный и двухкнопочный режимы о
Название группы заменить на:
Режим работы входов (для прошивок до 2.6.6 включительно)

Описание:
В прошивках до 2.6.6 поддерживался только 1-кнопочный и 2-кнопочный режимы работы входов без возможности свободной привязки входов и выходов и обработки различных типов нажатий. Начиная с прошивки 2.7.0 выбирать режим работы входов нет необходимости. Можно связывать входы и выходы в произвольных комбинациях

2024-06-04 06:36 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "condition": "input_{{ch_number + 1}}_mode==0"
Не так. Настройка нажатий должна отображаться, если
- режим работы входов (с вкладки общие) не выбран или выбран пользовательский
- режим работы входа (кнопка/выключатель) не выбран или выбран "Кнопка"

Смотри шаблон МАО4 для примера

2024-06-04 06:39 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "condition": "input_{{ch_number + 1}}_mode==0"
То есть тут достаточно заменить на `!=1` и должно заработать, попробуй

2024-06-04 08:37 UTC, pgasheev requested changes

2024-06-04 08:37 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "title": "Inputs Mode",
Legacy Inputs Mode

2024-06-04 08:37 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "id": "g_mode",
`gg_mode`, т.к. стала подшруппой

2024-06-04 08:37 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "id": "baud_rate",
General Parameters
gg_general_parameters

2024-06-04 08:37 UTC, pgasheev commented on templates/config-wb-mdm3.json.jinja
> +                "id": "acln",
General Channels
gg_general_channels

2024-06-04 08:59 UTC, pgasheev approved these changes

2024-06-06 08:09 UTC, merged