Somfy SDN: add tilting support
wirenboard/wb-mqtt-serial pull request #761
Opened 2024-06-13 07:55 UTC by sikmir

Пока еще с железкой не проверяли, поэтому драфт.

2024-07-09 08:24 UTC, KraPete requested changes

2024-07-09 08:24 UTC, KraPete commented on debian/changelog
> +wb-mqtt-serial (2.130.1) stable; urgency=medium
Может, `2.131.0` сделать?

2024-07-09 08:24 UTC, KraPete commented on templates/config-somfy-sdn.json
> +                "name": "Tilting angle of the slats",
Можно ли перефразировать? А то оно со всеми этими `of the` попадает в название MQTT топика

2024-07-09 08:24 UTC, KraPete commented on src/devices/curtains/somfy_sdn_device.cpp
> +                       {0x07, static_cast<uint8_t>(position & 0xFF), 0x00, 0x00, 0x00, 0x00});
Кажется, мы сломаем совместимость с другими типами моторов. Можешь описать, почему тут запрос поменялся?

2024-07-09 08:58 UTC, sikmir commented on debian/changelog
> +wb-mqtt-serial (2.130.1) stable; urgency=medium
да

2024-07-11 07:24 UTC, sikmir commented on src/devices/curtains/somfy_sdn_device.cpp
> +                       {0x07, static_cast<uint8_t>(position & 0xFF), 0x00, 0x00, 0x00, 0x00});
0x04 - выставить положение
0x07 - выставить положение и текущий угол (если применимо)
То есть другие моторы должны работать игнорируя угол. Но так как с остальными нет возможности это проверить, то да, надо вынести это в шаблон похоже.

2024-07-11 07:25 UTC, sikmir commented on templates/config-somfy-sdn.json
> +                "name": "Tilting angle of the slats",
Может просто Tilting оставить

2024-07-11 07:35 UTC, KraPete commented on src/devices/curtains/somfy_sdn_device.cpp
> +                       {0x07, static_cast<uint8_t>(position & 0xFF), 0x00, 0x00, 0x00, 0x00});
Да, предлагаю сделать отдельные параметры для разных типов запросов

2024-07-12 07:54 UTC, sikmir commented on src/devices/curtains/somfy_sdn_device.cpp
> +                       {0x07, static_cast<uint8_t>(position & 0xFF), 0x00, 0x00, 0x00, 0x00});
Поправил чтобы только для AC_40 использовалось. 0x07, для остальных 0x04

2024-07-15 07:42 UTC, KraPete approved these changes

2024-07-15 07:47 UTC, merged