Feature/add template apc
wirenboard/wb-mqtt-serial pull request #782
Opened 2024-07-10 13:38 UTC by matveevrj

2024-07-12 05:14 UTC, KraPete requested changes

2024-07-12 05:14 UTC, KraPete commented on templates/config-apc-nmc2.json
> +                "scale": 1.0,
Зачем `scale: 1.0` оно и так целочисленное. И так во многих параметрах

2024-07-12 05:14 UTC, KraPete commented on templates/config-apc-nmc2.json
> +                "name": "Version 2.6",
В Сашиной инструкции описано, что надо избегать знаков припенания в названиях каналов. Можешь описать, что здесь ожидается вычитать из регистра. Может заменить на `enum` и `enum_titles`?

2024-07-12 05:14 UTC, KraPete commented on templates/config-apc-nmc2.json
> +                "name": "Number Of Faulty Batteries",
Можно ли перефразировать без `Of`?

2024-07-12 05:14 UTC, KraPete commented on templates/config-apc-nmc2.json
> +                "name": "Number Of Batteries",
Можно ли перефразировать без `Of`?

2024-07-12 05:14 UTC, KraPete commented on templates/config-apc-nmc2.json
> +                "name": "Current Output Voltage",
Предлагаю оставить просто `Output Voltage`

2024-07-12 05:14 UTC, KraPete commented on templates/config-apc-nmc2.json
> +                "name": "Current Input Voltage",
Предлагаю оставить просто `Input Voltage`

2024-07-12 05:14 UTC, KraPete commented on templates/config-apc-nmc2.json
> +                "name": "Current Frequency",
Предлагаю оставить просто `Frequency`

2024-07-12 05:14 UTC, KraPete commented on templates/config-apc-nmc2.json
> +                "name": "Work",
Можешь более детально объяснить, что это за параметр?

2024-07-16 04:20 UTC, KraPete commented on templates/config-apc-nmc2.json
> +                "name": "Work",
Тут не очень понятно, это ИБП питает подключенное оборудование, или он просто включен и нет никаких проблем или что-то ещё.

2024-07-17 13:46 UTC, sikmir commented on templates/config-apc-nmc2.json
> +                "format": "u16",
```suggestion
                "format": "u16",
                "units": "min",
```

2024-07-17 13:49 UTC, sikmir commented on templates/config-apc-nmc2.json
> +                "template_title": "UPS NMC2 AP9630"
можно не выносить в translations, если перевод не требуется

2024-07-22 05:31 UTC, KraPete commented on templates/config-apc-nmc2.json
> +                "scale": 1.0,
А в остальных местах не исправил

2024-07-31 04:08 UTC, KraPete approved these changes

2024-07-31 08:24 UTC, merged