WB-MRWM2: Add support for voltage control function and delays
wirenboard/wb-mqtt-serial pull request #785
Opened 2024-07-12 09:05 UTC by Ilia1S

Ticket 75020

@nikitoz236 @pgasheev

2024-07-15 19:03 UTC, pgasheev commented on templates/config-wb-mrwm2.json.jinja
> +                "name": " K{{out_num}}",
Два канала отличаются пробелом в названии? Причем с пробела начинается? Это точно так задумано?

2024-07-17 13:41 UTC, sikmir commented on debian/changelog
> + wb-mqtt-serial (2.133.0) stable; urgency=medium
```suggestion
wb-mqtt-serial (2.133.0) stable; urgency=medium
```

2024-07-22 05:39 UTC, KraPete requested changes

2024-07-22 05:39 UTC, KraPete commented on templates/config-wb-mrwm2.json.jinja
> +                "id": "Real state K{{out_num}}",
Вот ту сломали обратную совместимость, в MQTT было `/devices/+/controls/K1`, стало `/devices/+/controls/Real state K1`.

2024-07-22 05:39 UTC, KraPete commented on templates/config-wb-mrwm2.json.jinja
> +                "id": "Desired state K{{out_num}}",
Вроде, договорились все слова с заглавной

2024-07-24 06:23 UTC, pgasheev requested changes
@Ilia1S 
Посмотри на параметры
```
out{{out_num}}_safe_state
out{{out_num}}_safety_behaviour
out{{out_num}}_safety_input_control
```
Они зачем-то завернуты в цикл по входам и дублируются в итоговом json. Давай это поправим тоже

2024-07-30 06:54 UTC, pgasheev commented on templates/config-wb-mrwm2.json.jinja
> +            "startup_delay1_{{out_num}}": {
С @KraPete посмотрели, одинаковые id в этом случае не работают из-за особенностей в homeui, так что используем разные. Поправь названия только

2024-07-30 07:00 UTC, Ilia1S commented on templates/config-wb-mrwm2.json.jinja
> +                "id": "Desired state K{{out_num}}",
ОК

2024-07-30 07:00 UTC, Ilia1S commented on templates/config-wb-mrwm2.json.jinja
> +                "id": "Real state K{{out_num}}",
ОК

2024-07-30 07:01 UTC, Ilia1S commented on debian/changelog
> + wb-mqtt-serial (2.133.0) stable; urgency=medium
ОК

2024-07-30 07:01 UTC, Ilia1S commented on templates/config-wb-mrwm2.json.jinja
> +                "name": " K{{out_num}}",
Исправил

2024-07-30 07:03 UTC, Ilia1S commented on templates/config-wb-mrwm2.json.jinja
> +            "startup_delay1_{{out_num}}": {
Делаем более развернутые названия

2024-07-30 07:04 UTC, Ilia1S commented on templates/config-wb-mrwm2.json.jinja
> +                "name": "Urms Normal K{{out_num}}",
С Дмитрием решили, что запрос по дефолту ВКЛючен.

2024-07-30 07:04 UTC, Ilia1S commented on templates/config-wb-mrwm2.json.jinja
> +                "name": " K{{out_num}}",
Сейчас каналы имеют разное название, без пробела перед началом

2024-07-30 07:24 UTC, pgasheev requested changes

2024-07-30 07:24 UTC, pgasheev commented on templates/config-wb-mrwm2.json.jinja
> +                "BLOCKED": "ЗАБЛОКИРОВАН",
Вот это лишнее кажется

2024-07-30 07:31 UTC, Ilia1S commented on templates/config-wb-mrwm2.json.jinja
> +                "BLOCKED": "ЗАБЛОКИРОВАН",
Удалил

2024-07-30 07:37 UTC, pgasheev approved these changes

2024-07-31 04:15 UTC, KraPete approved these changes

2024-07-31 06:43 UTC, merged