Feature/add template veda
wirenboard/wb-mqtt-serial pull request #787
Opened 2024-07-16 13:58 UTC by matveevrj

2024-07-16 15:04 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "type": "current",
```suggestion
                "type": "value",
                "units": "A",
```

2024-07-16 15:05 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "type": "voltage",
```suggestion
                "type": "value",
                "units": "volts",
```

2024-07-16 15:05 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "type": "voltage",
```suggestion
                "type": "value",
                "units": "volts",
```

2024-07-16 15:09 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "type": "temperature",
```suggestion
                "type": "value",
                "units": "deg C",
```

2024-07-16 15:11 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "template_title": "Veda VF 51",
```suggestion
            "ru": {
```
template_title нигде не используется

2024-07-16 15:14 UTC, sikmir commented
+ поправить тесты

2024-07-17 13:36 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "units": "Hz",
У нас нет в конвенции Hz (https://github.com/wirenboard/conventions?tab=readme-ov-file#units)

2024-07-17 13:37 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "units": "rpm",
rpm тоже нет в конвенции

2024-07-17 13:37 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "type": "voltage",
```suggestion
                "type": "value",
                "units": "V",
```

2024-07-17 13:38 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "type": "temperature",
```suggestion
                "type": "value",
                "units": "deg C",
```

2024-07-17 13:38 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "type": "voltage",
```suggestion
                "type": "value",
                "units": "V",
```

2024-07-18 07:32 UTC, sikmir commented on templates/config-veda-vf51.json
> +                "units": "Hz",
Добавим в конвенцию тогда

2024-07-22 05:43 UTC, KraPete requested changes

2024-07-22 05:43 UTC, KraPete commented on debian/changelog
> +
Лишняя строка

2024-07-22 05:43 UTC, KraPete commented on templates/config-veda-vf51.json
> +        "frame_timeout_ms": 8,
Почему именно так?

2024-07-22 05:43 UTC, KraPete commented on templates/config-veda-vf51.json
> +                "scale": 1.0,
Не надо `scale : 1.0`

2024-07-22 05:43 UTC, KraPete commented on templates/config-veda-vf51.json
> +                "scale": 1.0,
Тут тоже не нужно

2024-07-22 05:43 UTC, KraPete commented on templates/config-veda-vf51.json
> +                "scale": 1.0,
И тут

2024-07-31 04:07 UTC, KraPete approved these changes

2024-07-31 08:58 UTC, merged