Feature/add template ptex
wirenboard/wb-mqtt-serial pull request #789
Opened 2024-07-16 18:33 UTC by matveevrj

2024-07-22 05:47 UTC, KraPete requested changes

2024-07-22 05:47 UTC, KraPete commented on debian/changelog
> + wb-mqtt-serial (2.133.0) stable; urgency=medium
```suggestion
wb-mqtt-serial (2.133.0) stable; urgency=medium
```
Из-за этого не собиралось

2024-07-22 05:47 UTC, KraPete commented on templates/config-ptex.json
> +					"Const.",
А зачем точка?

2024-07-22 05:47 UTC, KraPete commented on templates/config-ptex.json
> +				"name": "Min. Pump Operating Time",
Договорились же без знаков припенания в названиях каналов

2024-07-22 20:17 UTC, sikmir commented on templates/config-ptex.json
> +				"type": "value",
может units добавить?

2024-07-22 20:19 UTC, sikmir commented on templates/config-ptex.json
> +				"units": "liters",
литров у нас нет в конвенции

2024-08-01 04:38 UTC, KraPete approved these changes

2024-08-01 07:07 UTC, merged