Feature/int-104 add template kaplestop
wirenboard/wb-mqtt-serial pull request #795
Opened 2024-07-25 12:49 UTC by BurchuMikhail

2024-07-26 12:37 UTC, sikmir commented on templates/config-kaplestop.json.jinja
> +{% set title_en = title_en | default("SDM-KapleStop v.4.12") -%}
А что дает такой вынос в переменные?

2024-07-26 13:05 UTC, BurchuMikhail commented on templates/config-kaplestop.json.jinja
> +{% set title_en = title_en | default("SDM-KapleStop v.4.12") -%}
Указание значения по умолчанию?
За основу взят шаблон от WB-MAI6.
Решил использовать такой же механизм.

2024-07-29 06:16 UTC, KraPete requested changes

2024-07-29 06:16 UTC, KraPete commented on debian/changelog
> +wb-mqtt-serial (2.133.6) stable; urgency=medium
```suggestion
wb-mqtt-serial (2.134.0) stable; urgency=medium
```

2024-07-29 06:16 UTC, KraPete commented on templates/config-kaplestop.json.jinja
> +{% set title_en = title_en | default("SDM-KapleStop v.4.12") -%}
Там это было сделано, т.к. потом из этого шаблона делается шаблон для MAI6 и для ONI. У них другие названия, потому и дополнительная параметризация. Тут же это перебор. Предлагаю упростить

2024-07-29 06:16 UTC, KraPete commented on templates/config-kaplestop.json.jinja
> +                "Zone Level13 (kOhm)": "0 - признак окончания цепочки",
Тут точно так надо. Очень английский вариант от русского отличается

2024-07-29 07:12 UTC, BurchuMikhail commented on templates/config-kaplestop.json.jinja
> +                "Zone Level13 (kOhm)": "0 - признак окончания цепочки",
Исправил. Было некорректно переведено.

2024-07-29 12:16 UTC, KraPete approved these changes

2024-07-29 12:43 UTC, merged