fix RGB Strip Hue
wirenboard/wb-mqtt-serial pull request #807
Opened 2024-09-04 14:38 UTC by SupersADF

[багрепорт](https://wirenboard.youtrack.cloud/issue/FW-656/Bagreport-nekorrektnaya-rabota-WB-LED)

2024-09-04 16:22 UTC, KraPete requested changes
Ничего не понял, но очень интересно. Мы говорим прошивке включить события для регистра с адресом 2014, прошивка рапортует, что события включены, но не шлёт их. Если я прав, зачем править шаблон? Надо идти к коллегам и править прошивку

2024-09-05 08:18 UTC, SupersADF commented
@KraPete Если включить события по hue changing, то оно этими постоянными событиями положит шину

2024-09-05 08:28 UTC, KraPete commented
Я снова ничего не понял. Вот ты в задаче пишешь `Поправил шаблон, так как в веб не изменялся RGB Strip Hue, когда включен Hue Changing. Создал PR.` А потом тут пишешь, что всё ок - события есть.

2024-09-05 09:25 UTC, KraPete approved these changes

2024-09-05 11:11 UTC, pgasheev approved these changes
@SupersADF в тикете всё очень подробно опиши, ссылку на тикет прикрепи в описание PR

2024-09-05 12:04 UTC, merged