add template for breezart lux sb
wirenboard/wb-mqtt-serial pull request #820
Opened 2024-10-08 11:06 UTC by BurchuMikhail

2024-10-08 12:08 UTC, sikmir commented on templates/config-breezart-lux.json
> +            },
Тут лучше через jinja шаблон сделать.

2024-10-09 05:03 UTC, KraPete requested changes
Я бы всё, что сейчас написано в "id" каналов, перенёс в "name", а то, что в "name" - в переводы. "id" бы везде исчезло, и в wb-mqtt-serial.conf попадали бы имена каналов такие же, как в MQTT

2024-10-09 08:50 UTC, KraPete approved these changes

2024-10-09 10:13 UTC, sikmir approved these changes

2024-10-09 10:14 UTC, merged